"""
This type stub file was generated by pyright.
"""

__logger__ = ...
__all__ = ["cdict", "ContraDict"]
def cdict(*args, **kwargs) -> ContraDict:
    """
    factory function
    """
    ...

class ContraDict(dict):
    """
    directly inherited from dict

    accessible by attribute. o.x == o['x']
    This works also for all corner cases.

    native json.dumps and json.loads work with it

    names like "keys", "update", "values" etc won't overwrite the methods,
    but will just be available using dict lookup notation obj['items'] instead of obj.items

    all key names are converted to snake_case
    hyphen's (-), dot's (.) or whitespaces are replaced by underscore (_)

    autocomplete works even if the objects comes from a list

    recursive action. dict assignments will be converted too.
    """
    __module__ = ...
    def __init__(self, *args, **kwargs) -> None:
        ...

    def __setitem__(self, key, value) -> None:
        ...

    def __setattr__(self, key, value) -> None:
        ...

    def __getitem__(self, item) -> dict[Any, dict[Any, dict[Any, Any] | Any] | Any]:
        """
        when used with an int it will return the item on that index (that means a dict of {key: value}
        otherwise it works as usual and returns the value corresponding to item
        :param item:
        :type item:
        :return:
        :rtype:
        """
        ...

    def __getattribute__(self, attribute) -> dict[Any, dict[Any, dict[Any, Any] | Any] | Any] | Any:
        ...



_warning_names = ...
_warning_names_message = ...
