"""
This type stub file was generated by pyright.
"""

import asyncio
import http.cookiejar
from typing import List, Tuple, Union
from .. import cdp
from . import tab
from .config import Config, PathLike
from .connection import Connection

logger = ...
class Browser(Connection):
    """
    The Browser object is the "root" of the hierarchy and contains a reference
    to the browser parent process.
    there should usually be only 1 instance of this.

    All opened tabs, extra browser screens and resources will not cause a new Browser process,
    but rather create additional :class:`nodriver.Tab` objects.

    So, besides starting your instance and first/additional tabs, you don't actively use it a lot under normal conditions.

    Tab objects will represent and control
     - tabs (as you know them)
     - browser windows (new window)
     - iframe
     - background processes

    note:
    the Browser object is not instantiated by __init__ but using the asynchronous :meth:`nodriver.Browser.create` method.

    note:
    in Chromium based browsers, there is a parent process which keeps running all the time, even if
    there are no visible browser windows. sometimes it's stubborn to close it, so make sure after using
    this library, the browser is correctly and fully closed/exited/killed.

    """
    _process: asyncio.subprocess.Process
    _process_pid: int
    _http: HTTPApi = ...
    _cookies: CookieJar = ...
    config: Config
    @classmethod
    async def create(cls, config: Config = ..., *, user_data_dir: PathLike = ..., headless: bool = ..., browser_executable_path: PathLike = ..., browser_args: List[str] = ..., sandbox: bool = ..., host: str = ..., port: int = ..., **kwargs) -> Browser:
        """
        entry point for creating an instance
        """
        ...

    def __init__(self, config: Config, **kwargs) -> None:
        """
        constructor. to create a instance, use :py:meth:`Browser.create(...)`

        :param config:
        """
        ...

    @property
    def main_tab(self) -> tab.Tab:
        """returns the target which was launched with the browser"""
        ...

    @property
    def targets(self) -> List[Connection]:
        ...

    @property
    def tabs(self) -> List[tab.Connection]:
        ...

    @property
    def cookies(self) -> CookieJar:
        ...

    @property
    def stopped(self) -> bool:
        ...

    async def wait(self, time: Union[float, int] = ...) -> None:
        """wait for <time> seconds. important to use, especially in between page navigation

        :param time:
        :return:
        """
        ...

    sleep = ...
    async def get(self, url=..., new_tab: bool = ..., new_window: bool = ...) -> tab.Tab:
        """top level get. utilizes the first tab to retrieve given url.

        convenience function known from selenium.
        this function handles waits/sleeps and detects when DOM events fired, so it's the safest
        way of navigating.

        :param url: the url to navigate to
        :param new_tab: open new tab
        :param new_window:  open new window
        :return: Page
        """
        ...

    async def create_context(self, url: str = ..., new_tab: bool = ..., new_window: bool = ..., dispose_on_detach: bool = ..., proxy_server: str = ..., proxy_bypass_list: List[str] = ..., origins_with_universal_network_access: List[str] = ..., proxy_ssl_context=...) -> tab.Tab:
        """
        creates a new browser context - mostly useful if you want to use proxies for different browser instances
        since chrome usually can only use 1 proxy per browser.
        socks5 with authentication is supported by using a forwarder proxy, the
        correct string to use socks proxy with username/password auth is socks://USERNAME:PASSWORD@SERVER:PORT
        http/https proxies with authentication are also supported: http://USERNAME:PASSWORD@SERVER:PORT

        dispose_on_detach – (EXPERIMENTAL) (Optional) If specified, disposes this context when debugging session disconnects.
        proxy_server – (EXPERIMENTAL) (Optional) Proxy server, similar to the one passed to –proxy-server
        proxy_bypass_list – (EXPERIMENTAL) (Optional) Proxy bypass list, similar to the one passed to –proxy-bypass-list
        origins_with_universal_network_access – (EXPERIMENTAL) (Optional) An optional list of origins to grant unlimited cross-origin access to. Parts of the URL other than those constituting origin are ignored.
        proxy_ssl_context – (Optional) Custom SSL context for HTTPS proxy connections. If None, a default context is used.

        :param new_window:
        :type new_window:
        :param new_tab:
        :type new_tab:
        :param url:
        :type url:
        :param dispose_on_detach:
        :type dispose_on_detach:
        :param proxy_server:
        :type proxy_server:
        :param proxy_bypass_list:
        :type proxy_bypass_list:
        :param origins_with_universal_network_access:
        :type origins_with_universal_network_access:
        :param proxy_ssl_context:
        :type proxy_ssl_context: ssl.SSLContext
        :return:
        :rtype:
        """
        ...

    async def start(self=...) -> Browser:
        """launches the actual browser"""
        ...

    async def grant_all_permissions(self) -> None:
        """
        grant permissions for:
            accessibilityEvents
            audioCapture
            backgroundSync
            backgroundFetch
            clipboardReadWrite
            clipboardSanitizedWrite
            displayCapture
            durableStorage
            geolocation
            idleDetection
            localFonts
            midi
            midiSysex
            nfc
            notifications
            paymentHandler
            periodicBackgroundSync
            protectedMediaIdentifier
            sensors
            storageAccess
            topLevelStorageAccess
            videoCapture
            videoCapturePanTiltZoom
            wakeLockScreen
            wakeLockSystem
            windowManagement
        """
        ...

    async def tile_windows(self, windows=..., max_columns: int = ...) -> list[Any] | None:
        ...

    async def update_targets(self) -> None:
        ...

    def __iter__(self) -> Self:
        ...

    def __getitem__(self, item: Union[str, int, slice]) -> Union[tab.Tab, List[tab.Tab], None]:
        """
        allows to get py:obj:`tab.Tab` instances by using browser[0], browser[1], etc.
        a string is also allowed. it will then return the first tab where the py:obj:`cdp.target.TargetInfo` object
        (as json string) contains the given key, or the first tab in case no matches are found. eg:
        `browser["google"]` gives the first tab which has "google" in it's serialized target object.

        :param item:
        :type item:
        :return:
        :rtype: tab.Tab
        """
        ...

    def __reversed__(self) -> Iterator[Connection]:
        ...

    def __next__(self) -> tab.Tab | tab.Connection | None:
        ...

    def stop(self) -> None:
        ...

    def __await__(self) -> Generator[Any, None, None]:
        ...

    def __del__(self) -> None:
        ...



class CookieJar:
    def __init__(self, browser: Browser) -> None:
        ...

    async def get_all(self, requests_cookie_format: bool = ...) -> List[Union[cdp.network.Cookie, http.cookiejar.Cookie]]:
        """
        get all cookies

        :param requests_cookie_format: when True, returns python http.cookiejar.Cookie objects, compatible  with requests library and many others.
        :type requests_cookie_format: bool
        :return:
        :rtype:

        """
        ...

    async def set_all(self, cookies: List[cdp.network.CookieParam]) -> None:
        """
        set cookies

        :param cookies: list of cookies
        :type cookies:
        :return:
        :rtype:
        """
        ...

    async def save(self, file: PathLike = ..., pattern: str = ...) -> None:
        """
        save all cookies (or a subset, controlled by `pattern`) to a file to be restored later

        :param file:
        :type file:
        :param pattern: regex style pattern string.
               any cookie that has a  domain, key or value field which matches the pattern will be included.
               default (param not specified) = ".*"  (all)

               eg: the pattern "(cf|.com|nowsecure)" will include those cookies which:
                    - have a string "cf" (cloudflare)
                    - have ".com" in them, in either domain, key or value field.
                    - contain "nowsecure"
        :type pattern: str
        :return:
        :rtype:
        """
        ...

    async def load(self, file: PathLike = ..., pattern: str = ...) -> None:
        """
        load all cookies (or a subset, controlled by `pattern`) from a file created by :py:meth:`~save_cookies`.

        :param file:
        :type file:
        :param pattern: regex style pattern string.
               any cookie that has a  domain, key or value field which matches the pattern will be included.
               default (param not specified)  = ".*"  (all)

               eg: the pattern "(cf|.com|nowsecure)" will include those cookies which:
                    - have a string "cf" (cloudflare)
                    - have ".com" in them, in either domain, key or value field.
                    - contain "nowsecure"
        :type pattern: str
        :return:
        :rtype:
        """
        ...

    async def clear(self) -> None:
        """
        clear current cookies

        note: this includes all open tabs/windows for this browser

        :return:
        :rtype:
        """
        ...



class HTTPApi:
    def __init__(self, addr: Tuple[str, int]) -> None:
        ...

    @classmethod
    def from_target(cls, target: Target) -> Self:
        ...

    async def get(self, endpoint: str) -> Any:
        ...

    async def post(self, endpoint, data) -> Any:
        ...



class BrowserContext:
    def __init__(self, config: Config = ..., *, user_data_dir: PathLike = ..., headless: bool = ..., browser_executable_path: PathLike = ..., browser_args: List[str] = ..., sandbox: bool = ..., host: str = ..., port: int = ..., keep_open: bool = ..., **kwargs) -> None:
        ...

    async def __aenter__(self) -> Browser:
        ...

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        ...
