"""
This type stub file was generated by pyright.
"""

import pathlib
from typing import List, Optional, TypeVar

__all__ = ["Config", "find_chrome_executable", "temp_profile_dir", "is_root", "is_posix", "PathLike"]
logger = ...
is_posix = ...
PathLike = TypeVar("PathLike", bound=str | pathlib.Path)
AUTO = ...
class Config:
    """
    Config object
    """
    def __init__(self, user_data_dir: Optional[PathLike] = ..., headless: Optional[bool] = ..., browser_executable_path: Optional[PathLike] = ..., browser_args: Optional[List[str]] = ..., sandbox: Optional[bool] = ..., lang: Optional[str] = ..., host: str = ..., port: int = ..., expert: bool = ..., **kwargs: dict) -> None:
        """
        creates a config object.
        Can be called without any arguments to generate a best-practice config, which is recommended.

        calling the object, eg :  myconfig() , will return the list of arguments which
        are provided to the browser.

        additional arguments can be added using the :py:obj:`~add_argument method`

        Instances of this class are usually not instantiated by end users.

        :param user_data_dir: the data directory to use
        :param headless: set to True for headless mode
        :param browser_executable_path: specify browser executable, instead of using autodetect
        :param browser_args: forwarded to browser executable. eg : ["--some-chromeparam=somevalue", "some-other-param=someval"]
        :param sandbox: disables sandbox
        :param autodiscover_targets: use autodiscovery of targets
        :param lang: language string to use other than the default "en-US,en;q=0.9"
        :param expert: when set to True, enabled "expert" mode.
               This conveys, the inclusion of parameters:  ----disable-site-isolation-trials,
               as well as some scripts and patching useful for debugging (for example, ensuring shadow-root is always in "open" mode)

        :param kwargs:

        :type user_data_dir: PathLike
        :type headless: bool
        :type browser_executable_path: PathLike
        :type browser_args: list[str]
        :type sandbox: bool
        :type lang: str
        :type kwargs: dict
        """
        ...

    @property
    def browser_args(self) -> list[str]:
        ...

    @property
    def user_data_dir(self) -> str:
        ...

    @user_data_dir.setter
    def user_data_dir(self, path: PathLike) -> None:
        ...

    @property
    def uses_custom_data_dir(self) -> bool:
        ...

    def add_extension(self, extension_path: PathLike) -> None:
        """
        adds an extension to load, you could point extension_path
        to a folder (containing the manifest), or extension file (crx)

        :param extension_path:
        :type extension_path:
        :return:
        :rtype:
        """
        ...

    def __call__(self) -> list[str]:
        ...

    def add_argument(self, arg: str) -> None:
        ...

    def __repr__(self) -> str:
        ...



def is_root() -> bool | Any:
    """
    helper function to determine if user trying to launch chrome
    under linux as root, which needs some alternative handling
    :return:
    :rtype:
    """
    ...

def temp_profile_dir() -> str:
    """generate a temp dir (path)"""
    ...

def find_chrome_executable(return_all=...) -> list[Any]:
    """
    Finds the chrome, beta, canary, chromium executable
    and returns the disk path
    """
    ...
