"""
This type stub file was generated by pyright.
"""

import asyncio
import websockets.asyncio.client
from typing import Any, Callable, Generator, TypeVar, Union
from .. import cdp

T = TypeVar("T")
GLOBAL_DELAY = ...
MAX_SIZE: int = ...
PING_TIMEOUT: int = ...
TargetType = Union[cdp.target.TargetInfo, cdp.target.TargetID, str]
logger = ...
class ProtocolException(Exception):
    def __init__(self, *args, **kwargs) -> None:
        ...

    def __str__(self) -> str:
        ...



class Transaction:
    def __init__(self, request: dict) -> None:
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self) -> str:
        ...



class Connection:
    socket: websockets.asyncio.client.ClientConnection | None
    websocket_url: str = ...
    @property
    def attached(self) -> bool:
        ...

    @property
    def transactions(self) -> List[Transaction]:
        """
        simple array that holds recent transactions.
        each transaction consist of a response, request, result, events fields
        the latest transaction is the last element in the list.
        """
        ...

    @property
    def last_transaction(self) -> Transaction:
        """
        simple alias to get the last transaction to inspect.
        """
        ...

    def add_handler(self, event_type: type, callback: Callable) -> None:
        """Register an event callback for a parsed CDP event type."""
        ...

    def remove_handler(self, event_type: type, callback: Callable) -> bool:
        """Remove an event callback; returns True when a handler was removed."""
        ...

    def __init__(self, target: TargetType = ..., parent: Connection = ..., auto_attach: bool = ..., **kwargs) -> None:
        ...

    async def aopen(self) -> None:
        """ """
        ...

    async def aclose(self) -> None:
        """ """
        ...

    async def attach(self, target: TargetType = ...) -> None:
        """ " """
        ...

    async def detach(self) -> None:
        ...

    async def send(self, cdp_obj: Generator[dict[str, Any], dict[str, Any], Any], _attach: bool = ..., **kwargs) -> Any:
        ...

    async def process_event(self, message: dict, tx_id: int | None = ...) -> None:
        """ """
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self) -> str:
        ...
