"""
This type stub file was generated by pyright.
"""

import asyncio
import typing
from typing import Any, Generator, List, Optional, Tuple, Union
from .. import cdp
from . import element
from .config import PathLike
from .connection import Connection

logger = ...
class Tab(Connection):
    """
    :ref:`tab` is the controlling mechanism/connection to a 'target',
    for most of us 'target' can be read as 'tab'. however it could also
    be an iframe, serviceworker or background script for example,
    although there isn't much to control for those.

    if you open a new window by using :py:meth:`browser.get(..., new_window=True)`
    your url will open a new window. this window is a 'tab'.
    When you browse to another page, the tab will be the same (it is an browser view).

    So it's important to keep some reference to tab objects, in case you're
    done interacting with elements and want to operate on the page level again.

    Custom CDP commands
    ---------------------------
    Tab object provide many useful and often-used methods. It is also
    possible to utilize the included cdp classes to to something totally custom.

    the cdp package is a set of so-called "domains" with each having methods, events and types.
    to send a cdp method, for example :py:obj:`cdp.page.navigate`, you'll have to check
    whether the method accepts any parameters and whether they are required or not.

    you can use

    ```python
    await tab.send(cdp.page.navigate(url='https://yoururlhere'))
    ```

    so tab.send() accepts a generator object, which is created by calling a cdp method.
    this way you can build very detailed and customized commands.
    (note: finding correct command combo's can be a time consuming task, luckily i added a whole bunch
    of useful methods, preferably having the same api's or lookalikes, as in selenium)


    some useful, often needed and simply required methods
    ===================================================================


    :py:meth:`~find`  |  find(text)
    ----------------------------------------
    find and returns a single element by text match. by default returns the first element found.
    much more powerful is the best_match flag, although also much more expensive.
    when no match is found, it will retry for <timeout> seconds (default: 10), so
    this is also suitable to use as wait condition.


    :py:meth:`~find` |  find(text, best_match=True) or find(text, True)
    ---------------------------------------------------------------------------------
    Much more powerful (and expensive!!) than the above, is the use of the `find(text, best_match=True)` flag.
    It will still return 1 element, but when multiple matches are found, picks the one having the
    most similar text length.
    How would that help?
    For example, you search for "login", you'd probably want the "login" button element,
    and not thousands of scripts,meta,headings which happens to contain a string of "login".

    when no match is found, it will retry for <timeout> seconds (default: 10), so
    this is also suitable to use as wait condition.


    :py:meth:`~select` | select(selector)
    ----------------------------------------
    find and returns a single element by css selector match.
    when no match is found, it will retry for <timeout> seconds (default: 10), so
    this is also suitable to use as wait condition.


    :py:meth:`~select_all` | select_all(selector)
    ------------------------------------------------
    find and returns all elements by css selector match.
    when no match is found, it will retry for <timeout> seconds (default: 10), so
    this is also suitable to use as wait condition.


    await :py:obj:`Tab`
    ---------------------------
    calling `await tab` will do a lot of stuff under the hood, and ensures all references
    are up to date. also it allows for the script to "breathe", as it is oftentime faster than your browser or
    webpage. So whenever you get stuck and things crashes or element could not be found, you should probably let
    it "breathe"  by calling `await page`  and/or `await page.sleep()`

    also, it's ensuring :py:obj:`~url` will be updated to the most recent one, which is quite important in some
    other methods.

    attempts to find the location of given template image in the current viewport
    the only real use case for this is bot-detection systems.
    you can find for example the location of a 'verify'-checkbox,
    which are hidden from dom using shadow-root's or workers.



    await :py:obj:`Tab.template_location` (and await :py:obj:`Tab.verify_cf`)
    ------------------------------------------------------------------------------

    attempts to find the location of given template image in the current viewport.
    the only real use case for this is bot-detection systems.
    you can find, for example the location of a ‘verify’-checkbox, which are hidden from dom
    using shadow-root’s or/or workers and cannot be controlled by normal methods.

    template_image can be custom (for example your language, included is english only),
    but you need to create the template image yourself, which is just a cropped
    image of the area, see example image, where the target is exactly in the center.
    template_image can be custom (for example your language), but you need to
    create the template image yourself, where the target is exactly in the center.


    example (111x71)
    ---------
    this includes the white space on the left, to make the box center

    .. image:: template_example.png
        :width: 111
        :alt: example template image


    Using other and custom CDP commands
    ======================================================
    using the included cdp module, you can easily craft commands, which will always return an generator object.
    this generator object can be easily sent to the :py:meth:`~send`  method.

    :py:meth:`~send`
    ---------------------------
    this is probably THE most important method, although you won't ever call it, unless you want to
    go really custom. the send method accepts a :py:obj:`cdp` command. Each of which can be found in the
    cdp section.

    when you import * from this package, cdp will be in your namespace, and contains all domains/actions/events
    you can act upon.
    """
    _download_behavior: List[str] = ...
    @property
    def browser(self) -> nodriver.Browser | Connection | None:
        ...

    def __init__(self, target: cdp.target.TargetInfo | cdp.target.TargetID | str = ..., parent: Connection = ..., **kwargs) -> None:
        ...

    async def get_frames(self) -> List[IFrame]:
        """find any 'connectable' frames.
        mostly used for iframes. but this does NOT return :py:obj:`nodriver.Element` 's that are iframe.
        it returns a list of  `py:obj:`nodriver.core.tab.IFrame`if these are available.
        this does not guarantee to return any iframe, as some are
        isolated by security, origins, workers or other trickery.

        """
        ...

    @property
    def inspector_url(self) -> str:
        """
        get the inspector url. this url can be used in another browser to show you the devtools interface for
        current tab. useful for debugging (and headless)
        :return:
        :rtype:
        """
        ...

    def inspector_open(self) -> None:
        ...

    async def open_external_inspector(self) -> None:
        """
        opens the system's browser containing the devtools inspector page
        for this tab. could be handy, especially to debug in headless mode.
        """
        ...

    async def feed_cdp(self, cmd: Generator[dict[str, Any], dict[str, Any], Any]) -> asyncio.Future:
        ...

    async def get(self, url: str = ..., new_tab: bool = ..., new_window: bool = ...) -> Tab:
        ...

    async def find(self, text: str, best_match: bool = ..., return_enclosing_element=..., timeout: Union[int, float] = ...) -> Element | None:
        """
        find single element by text
        can also be used to wait for such element to appear.

        :param text: text to search for. note: script contents are also considered text
        :type text: str
        :param best_match:  :param best_match:  when True (default), it will return the element which has the most
                                               comparable string length. this could help tremendously, when for example
                                               you search for "login", you'd probably want the login button element,
                                               and not thousands of scripts,meta,headings containing a string of "login".
                                               When False, it will return naively just the first match (but is way faster).
         :type best_match: bool
         :param return_enclosing_element:
                 since we deal with nodes instead of elements, the find function most often returns
                 so called text nodes, which is actually a element of plain text, which is
                 the somehow imaginary "child" of a "span", "p", "script" or any other elements which have text between their opening
                 and closing tags.
                 most often when we search by text, we actually aim for the element containing the text instead of
                 a lousy plain text node, so by default the containing element is returned.

                 however, there are (why not) exceptions, for example elements that use the "placeholder=" property.
                 this text is rendered, but is not a pure text node. in that case you can set this flag to False.
                 since in this case we are probably interested in just that element, and not it's parent.


                 # todo, automatically determine node type
                 # ignore the return_enclosing_element flag if the found node is NOT a text node but a
                 # regular element (one having a tag) in which case that is exactly what we need.
         :type return_enclosing_element: bool
        :param timeout: raise timeout exception when after this many seconds nothing is found.
        :type timeout: float,int
        """
        ...

    async def select(self, selector: str, timeout: Union[int, float] = ...) -> nodriver.Element:
        """
        find single element by css selector.
        can also be used to wait for such element to appear.

        :param selector: css selector, eg a[href], button[class*=close], a > img[src]
        :type selector: str

        :param timeout: raise timeout exception when after this many seconds nothing is found.
        :type timeout: float,int

        """
        ...

    async def find_all(self, text: str, timeout: Union[int, float] = ...) -> List[nodriver.Element]:
        """
        find multiple elements by text
        can also be used to wait for such element to appear.

        :param text: text to search for. note: script contents are also considered text
        :type text: str

        :param timeout: raise timeout exception when after this many seconds nothing is found.
        :type timeout: float,int
        """
        ...

    async def select_all(self, selector: str, timeout: Union[int, float] = ..., include_frames=...) -> List[nodriver.Element]:
        """
        find multiple elements by css selector.
        can also be used to wait for such element to appear.


        :param selector: css selector, eg a[href], button[class*=close], a > img[src]
        :type selector: str
        :param timeout: raise timeout exception when after this many seconds nothing is found.
        :type timeout: float,int
        :param include_frames: whether to include results in iframes.
        :type include_frames: bool
        """
        ...

    async def sleep(self, t: float | int = ...) -> None:
        ...

    async def xpath(self, xpath: str, timeout: float = ...) -> List[Optional[nodriver.Element]]:
        """
        find elements by xpath string.
        if not immediately found, retries are attempted until :ref:`timeout` is reached (default 2.5 seconds).
        in case nothing is found, it returns an empty list. It will not raise.
        this timeout mechanism helps when relying on some element to appear before continuing your script.


        .. code-block:: python

             # find all the inline scripts (script elements without src attribute )
             await tab.xpath('//script[not(@src)]')

             # or here, more complex, but my personal favorite to case-insensitive text search

             await tab.xpath('//text()[ contains( translate(., "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz"),"test")]')


        :param xpath:
        :type xpath: str
        :param timeout: 2.5
        :type timeout: float
        :return:List[nodriver.Element] or []
        :rtype:
        """
        ...

    async def get(self, url=..., new_tab: bool = ..., new_window: bool = ...) -> Tab | Self:
        """top level get. utilizes the first tab to retrieve given url.

        convenience function known from selenium.
        this function handles waits/sleeps and detects when DOM events fired, so it's the safest
        way of navigating.

        :param url: the url to navigate to
        :param new_tab: open new tab
        :param new_window:  open new window
        :return: Page
        """
        ...

    async def query_selector_all(self, selector: str, _node: Optional[Union[cdp.dom.Node, element.Element]] = ...) -> list[Any] | None:
        """
        equivalent of javascripts document.querySelectorAll.
        this is considered one of the main methods to use in this package.

        it returns all matching :py:obj:`nodriver.Element` objects.

        :param selector: css selector. (first time? => https://www.w3schools.com/cssref/css_selectors.php )
        :type selector: str
        :param _node: internal use
        :type _node:
        :return:
        :rtype:
        """
        ...

    async def query_selector(self, selector: str, _node: Optional[Union[cdp.dom.Node, element.Element]] = ...) -> list[Any] | Element | None:
        """
        find single element based on css selector string

        :param selector: css selector(s)
        :type selector: str
        :return:
        :rtype:
        """
        ...

    async def find_elements_by_text(self, text: str, tag_hint: Optional[str] = ...) -> List[element.Element]:
        """
        returns element which match the given text.
        returns element which match the given text.
        please note: this may (or will) also return any other element (like inline scripts),
        which happen to contain that text.

        :param text:
        :type text:
        :param tag_hint: when provided, narrows down search to only elements which match given tag eg: a, div, script, span
        :type tag_hint: str
        :return:
        :rtype:
        """
        ...

    async def find_element_by_text(self, text: str, best_match: Optional[bool] = ..., return_enclosing_element: Optional[bool] = ...) -> Union[element.Element, None]:
        """
        finds and returns the first element containing <text>, or best match

        :param text:
        :type text:
        :param best_match:  when True, which is MUCH more expensive (thus much slower),
                            will find the closest match based on length.
                            this could help tremendously, when for example you search for "login", you'd probably want the login button element,
                            and not thousands of scripts,meta,headings containing a string of "login".

        :type best_match: bool
        :param return_enclosing_element:
        :type return_enclosing_element:
        :return:
        :rtype:
        """
        ...

    async def back(self) -> None:
        """
        history back
        """
        ...

    async def forward(self) -> None:
        """
        history forward
        """
        ...

    async def reload(self, ignore_cache: Optional[bool] = ..., script_to_evaluate_on_load: Optional[str] = ...) -> None:
        """
        Reloads the page

        :param ignore_cache: when set to True (default), it ignores cache, and re-downloads the items
        :type ignore_cache:
        :param script_to_evaluate_on_load: script to run on load. I actually haven't experimented with this one, so no guarantees.
        :type script_to_evaluate_on_load:
        :return:
        :rtype:
        """
        ...

    async def evaluate(self, expression: str, await_promise=..., return_by_value=...) -> Union[str, Union[str, Any], Tuple[cdp.runtime.RemoteObject, cdp.runtime.ExceptionDetails | None],]:
        ...

    async def js_dumps(self, obj_name: str, return_by_value: Optional[bool] = ...) -> typing.Union[typing.Dict, typing.Tuple[cdp.runtime.RemoteObject, cdp.runtime.ExceptionDetails],]:
        """
        dump given js object with its properties and values as a dict

        note: complex objects might not be serializable, therefore this method is not a "source of thruth"

        :param obj_name: the js object to dump
        :type obj_name: str

        :param return_by_value: if you want an tuple of cdp objects (returnvalue, errors), set this to False
        :type return_by_value: bool

        example
        ------

        x = await self.js_dumps('window')
        print(x)
            '...{
            'pageYOffset': 0,
            'visualViewport': {},
            'screenX': 10,
            'screenY': 10,
            'outerWidth': 1050,
            'outerHeight': 832,
            'devicePixelRatio': 1,
            'screenLeft': 10,
            'screenTop': 10,
            'styleMedia': {},
            'onsearch': None,
            'isSecureContext': True,
            'trustedTypes': {},
            'performance': {'timeOrigin': 1707823094767.9,
            'timing': {'connectStart': 0,
            'navigationStart': 1707823094768,
            ]...
            '
        """
        ...

    async def close(self) -> None:
        """
        close the current target (ie: tab,window,page)
        :return:
        :rtype:
        """
        ...

    async def get_window(self) -> Tuple[cdp.browser.WindowID, cdp.browser.Bounds]:
        """
        get the window Bounds
        :return:
        :rtype:
        """
        ...

    async def get_content(self) -> Any:
        """
        gets the current page source content (html)
        :return:
        :rtype:
        """
        ...

    async def maximize(self) -> None:
        """
        maximize page/tab/window
        """
        ...

    async def minimize(self) -> None:
        """
        minimize page/tab/window
        """
        ...

    async def fullscreen(self) -> None:
        """
        minimize page/tab/window
        """
        ...

    async def medimize(self) -> None:
        ...

    async def set_window_size(self, left=..., top=..., width=..., height=...) -> None:
        """
        set window size and position

        :param left: pixels from the left of the screen to the window top-left corner
        :type left:
        :param top: pixels from the top of the screen to the window top-left corner
        :type top:
        :param width: width of the window in pixels
        :type width:
        :param height: height of the window in pixels
        :type height:
        :return:
        :rtype:
        """
        ...

    async def activate(self) -> None:
        """
        active this target (ie: tab,window,page)
        """
        ...

    async def bring_to_front(self) -> None:
        """
        alias to self.activate
        """
        ...

    async def set_window_state(self, left=..., top=..., width=..., height=..., state=...) -> None:
        """
        sets the window size or state.

        for state you can provide the full name like minimized, maximized, normal, fullscreen, or
        something which leads to either of those, like min, mini, mi,  max, ma, maxi, full, fu, no, nor
        in case state is set other than "normal", the left, top, width, and height are ignored.

        :param left:
            desired offset from left, in pixels
        :type left: int

        :param top:
            desired offset from the top, in pixels
        :type top: int

        :param width:
            desired width in pixels
        :type width: int

        :param height:
            desired height in pixels
        :type height: int

        :param state:
            can be one of the following strings:
                - normal
                - fullscreen
                - maximized
                - minimized

        :type state: str

        """
        ...

    async def scroll_down(self, amount=...) -> None:
        """
        scrolls down maybe

        :param amount: number in percentage. 25 is a quarter of page, 50 half, and 1000 is 10x the page
        :type amount: int
        :return:
        :rtype:
        """
        ...

    async def scroll_up(self, amount=...) -> None:
        """
        scrolls up maybe

        :param amount: number in percentage. 25 is a quarter of page, 50 half, and 1000 is 10x the page
        :type amount: int

        :return:
        :rtype:
        """
        ...

    async def wait(self, t: Union[int, float] = ...) -> None:
        ...

    def __await__(self) -> Generator[Any, None, None]:
        ...

    async def wait_for(self, selector: Optional[str] = ..., text: Optional[str] = ..., timeout: Optional[Union[int, float]] = ...) -> element.Element:
        """
        variant on query_selector_all and find_elements_by_text
        this variant takes either selector or text, and will block until
        the requested element(s) are found.

        it will block for a maximum of <timeout> seconds, after which
        an TimeoutError will be raised

        :param selector: css selector
        :type selector:
        :param text: text
        :type text:
        :param timeout:
        :type timeout:
        :return:
        :rtype: Element
        :raises: asyncio.TimeoutError
        """
        ...

    async def download_file(self, url: str, filename: Optional[PathLike] = ...) -> None:
        """
        downloads file by given url.

        :param url: url of the file
        :param filename: the name for the file. if not specified the name is composed from the url file name
        """
        ...

    async def save_screenshot(self, filename: Optional[PathLike] = ..., format: Optional[str] = ..., full_page: Optional[bool] = ..., as_base64: Optional[bool] = ...) -> str:
        """
        Saves a screenshot of the page.
        This is not the same as :py:obj:`Element.save_screenshot`, which saves a screenshot of a single element only

        :param filename: uses this as the save path
        :type filename: PathLike
        :param format: jpeg or png (defaults to jpeg)
        :type format: str
        :param full_page: when False (default) it captures the current viewport. when True, it captures the entire page
        :type full_page: bool
        :param as_base64: whether to return a base64 string. this will ignore path, and will not write to a file
        :return: the path/filename of saved screenshot
        :rtype: str
        """
        ...

    async def set_download_path(self, path: Union[str, PathLike]) -> None:
        """
        sets the download path and allows downloads
        this is required for any download function to work (well not entirely, since when unset we set a default folder)

        :param path:
        :type path:
        :return:
        :rtype:
        """
        ...

    async def get_all_linked_sources(self) -> List[nodriver.Element]:
        """
        get all elements of tag: link, a, img, scripts meta, video, audio

        :return:
        """
        ...

    async def get_all_urls(self, absolute=...) -> List[str]:
        """
        convenience function, which returns all links (a,link,img,script,meta)

        :param absolute: try to build all the links in absolute form instead of "as is", often relative
        :return: list of urls
        """
        ...

    async def get_local_storage(self) -> dict[Any, Any]:
        """
        get local storage items as dict of strings (careful!, proper deserialization needs to be done if needed)

        :return:
        :rtype:
        """
        ...

    async def set_local_storage(self, items: dict) -> None:
        """
        set local storage.
        dict items must be strings. simple types will be converted to strings automatically.

        :param items: dict containing {key:str, value:str}
        :type items: dict[str,str]
        :return:
        :rtype:
        """
        ...

    def __call__(self, text: Optional[str] = ..., selector: Optional[str] = ..., timeout: Optional[Union[int, float]] = ...) -> CoroutineType[Any, Any, Element]:
        """
        alias to query_selector_all or find_elements_by_text, depending
        on whether text= is set or selector= is set

        :param selector: css selector string
        :type selector: str
        :return:
        :rtype:
        """
        ...

    async def get_frame_tree(self) -> cdp.page.FrameTree:
        """
        retrieves the frame tree for current tab
        There seems no real difference between :ref:`Tab.get_frame_resource_tree()`
        :return:
        :rtype:
        """
        ...

    async def get_frame_resource_tree(self) -> cdp.page.FrameResourceTree:
        """
        retrieves the frame resource tree for current tab.
        There seems no real difference between :ref:`Tab.get_frame_tree()`
        but still it returns a different object
        :return:
        :rtype:
        """
        ...

    async def get_frame_resource_urls(self) -> List[str]:
        """
        gets the urls of resources
        :return:
        :rtype:
        """
        ...

    async def search_frame_resources(self, query: str) -> typing.Dict[str, List[cdp.debugger.SearchMatch]]:
        ...

    async def verify_cf(self, template_image: str = ..., flash=...) -> None:
        """
        convenience function to verify cf checkbox

        template_image can be custom (for example your language, included is english only),
        but you need to create the template image yourself, which is just a cropped
        image of the area, see example image, where the target is exactly in the center.

        example (111x71)
        ---------
        this includes the white space on the left, to make the box center

        .. image:: template_example.png
            :width: 111
            :alt: example template image

        :param template_image:
            template_image can be custom (for example your language, included is english only),
            but you need to create the template image yourself, which is just a cropped
            image of the area, where the target is exactly in the center. see example on
            (https://ultrafunkamsterdam.github.io/nodriver/nodriver/classes/tab.html#example-111x71),

        :type template_image:
        :param flash: whether to show an indicator where the mouse is clicking.
        :type flash:
        :return:
        :rtype:
        """
        ...

    async def template_location(self, template_image: PathLike = ...) -> Union[Tuple[int, int], None]:
        """
        attempts to find the location of given template image in the current viewport
        the only real use case for this is bot-detection systems.
        you can find for example the location of a 'verify'-checkbox,
        which are hidden from dom using shadow-root's or workers.

        template_image can be custom (for example your language, included is english only),
        but you need to create the template image yourself, which is just a cropped
        image of the area, see example image, where the target is exactly in the center.
        template_image can be custom (for example your language), but you need to
        create the template image yourself, where the target is exactly in the center.

        example (111x71)
        ---------
        this includes the white space on the left, to make the box center

        .. image:: template_example.png
            :width: 111
            :alt: example template image


        :param template_image:
        :type template_image:
        :return:
        :rtype:
        """
        ...

    async def bypass_insecure_connection_warning(self) -> None:
        """
        when you enter a site where the certificate is invalid
        you get a warning. call this function to "proceed"
        :return:
        :rtype:
        """
        ...

    async def mouse_move(self, x: float, y: float, steps=..., flash=...) -> None:
        ...

    async def scroll_bottom_reached(self) -> Any | None:
        """
        returns True if scroll is at the bottom of the page
        handy when you need to scroll over paginated pages of different lengths
        :return:
        :rtype:
        """
        ...

    async def mouse_click(self, x: float, y: float, button: str = ..., buttons: typing.Optional[int] = ..., modifiers: typing.Optional[int] = ..., _until_event: typing.Optional[type] = ...) -> None:
        """native click on position x,y
        :param y:
        :type y:
        :param x:
        :type x:
        :param button: str (default = "left")
        :param buttons: which button (default 1 = left)
        :param modifiers: *(Optional)* Bit field representing pressed modifier keys.
                Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).
        :param _until_event: internal. event to wait for before returning
        :return:
        """
        ...

    async def mouse_drag(self, source_point: tuple[float, float], dest_point: tuple[float, float], relative: bool = ..., steps: int = ...) -> None:
        """
        drag mouse from one point to another. holding button pressed
        you are probably looking for :py:meth:`element.Element.mouse_drag` method. where you
        can drag on the element

        :param dest_point:
        :type dest_point:
        :param source_point:
        :type source_point:
        :param relative: when True, treats point as relative. for example (-100, 200) will move left 100px and down 200px
        :type relative:

        :param steps: move in <steps> points, this could make it look more "natural" (default 1),
               but also a lot slower.
               for very smooth action use 50-100
        :type steps: int
        :return:
        :rtype:
        """
        ...

    async def flash_point(self, x, y, duration=..., size=...) -> None:
        ...

    def __eq__(self, other: Tab) -> bool:
        ...

    def __getattr__(self, item) -> Any:
        ...



class IFrame(Tab):
    """
    a iframe is like a `nodriver.Tab`, a connection to an iframe
    """
    def __init__(self, target: cdp.target.TargetID | cdp.target.TargetInfo, parent: Connection, **kwargs) -> None:
        ...
