name: overheadadsb

services:
  overheadadsb:
    image: ${REGISTRY}/${REGISTRY_USER}/overheadadsb:${IMAGE_TAG}
    #    Building locally is not compatible with the provided ansible playbooks
    #    build:
    #      context: ./
    #      target: runtime
    #      dockerfile: Dockerfile
    container_name: overheadadsb
    environment:
      TZ: ${TZ}
      LAT: ${LAT}
      LON: ${LON}
      RAD_NM: ${RAD_NM}
      POLL_INT: ${POLL_INT}
      PORT: ${PORT}
      UVICORN_PORT: ${UVICORN_PORT}
      HTTP_TIMEOUT: ${HTTP_TIMEOUT}
      OWNER_POLL_CACHE_MAX: ${OWNER_POLL_CACHE_MAX}
    ports:
      - '${HOST_IP}:8003:${PORT}/tcp'
    #    Using a reverse proxy instead of exposing ports is recommended
    #    networks:
    #      - traefik
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

#    Optional traefik, grafana alloy and glannce labels
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.overheadadsb.rule=Host(`overheadadsb.${DOMAIN}`)"
#      - "traefik.http.routers.overheadadsb.entrypoints=websecure"
#      - "traefik.http.services.overheadadsb.loadbalancer.server.port=${PORT}"
#      - "uptime.enable=true"
#      - "uptime.address=https://overheadadsb.${DOMAIN}"
# Reuse existing traefik network if applicable
# networks:
#  traefik:
#    external: true
