[project]
name = "OverheadADS-B"
revision = "1.0"

[providers]
sops = "sops://secrets.enc.yaml?age_key_file=/home/Lea/.config/age/key.txt&age_recipients=age12tu4039uelzd6ywtuykv53y9rhz7elyyzxqkd9jfxfksuw0txfvsncsl0d
age12tu4039uelzd6ywtuykv53y9rhz7elyyzxqkd9jfxfksuw0txfvsncsl0d"

[profiles.default.defaults]
providers = ["sops_age"]
