"""
This type stub file was generated by pyright.
"""

import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
from . import dom, runtime

@dataclass
class Animation:
    '''
    Animation instance.
    '''
    id_: str
    name: str
    paused_state: bool
    play_state: str
    playback_rate: float
    start_time: float
    current_time: float
    type_: str
    source: typing.Optional[AnimationEffect] = ...
    css_id: typing.Optional[str] = ...
    view_or_scroll_timeline: typing.Optional[ViewOrScrollTimeline] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Animation:
        ...



@dataclass
class ViewOrScrollTimeline:
    '''
    Timeline instance
    '''
    axis: dom.ScrollOrientation
    source_node_id: typing.Optional[dom.BackendNodeId] = ...
    start_offset: typing.Optional[float] = ...
    end_offset: typing.Optional[float] = ...
    subject_node_id: typing.Optional[dom.BackendNodeId] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ViewOrScrollTimeline:
        ...



@dataclass
class AnimationEffect:
    '''
    AnimationEffect instance
    '''
    delay: float
    end_delay: float
    iteration_start: float
    duration: float
    direction: str
    fill: str
    easing: str
    iterations: typing.Optional[float] = ...
    backend_node_id: typing.Optional[dom.BackendNodeId] = ...
    keyframes_rule: typing.Optional[KeyframesRule] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AnimationEffect:
        ...



@dataclass
class KeyframesRule:
    '''
    Keyframes Rule
    '''
    keyframes: typing.List[KeyframeStyle]
    name: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> KeyframesRule:
        ...



@dataclass
class KeyframeStyle:
    '''
    Keyframe Style
    '''
    offset: str
    easing: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> KeyframeStyle:
        ...



def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disables animation domain notifications.
    '''
    ...

def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables animation domain notifications.
    '''
    ...

def get_current_time(id_: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, float]:
    '''
    Returns the current time of the an animation.

    :param id_: Id of animation.
    :returns: Current time of the page.
    '''
    ...

def get_playback_rate() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, float]:
    '''
    Gets the playback rate of the document timeline.

    :returns: Playback rate for animations on page.
    '''
    ...

def release_animations(animations: typing.List[str]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Releases a set of animations to no longer be manipulated.

    :param animations: List of animation ids to seek.
    '''
    ...

def resolve_animation(animation_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, runtime.RemoteObject]:
    '''
    Gets the remote object of the Animation.

    :param animation_id: Animation id.
    :returns: Corresponding remote object.
    '''
    ...

def seek_animations(animations: typing.List[str], current_time: float) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Seek a set of animations to a particular time within each animation.

    :param animations: List of animation ids to seek.
    :param current_time: Set the current time of each animation.
    '''
    ...

def set_paused(animations: typing.List[str], paused: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets the paused state of a set of animations.

    :param animations: Animations to set the pause state of.
    :param paused: Paused state to set to.
    '''
    ...

def set_playback_rate(playback_rate: float) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets the playback rate of the document timeline.

    :param playback_rate: Playback rate for animations on page
    '''
    ...

def set_timing(animation_id: str, duration: float, delay: float) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets the timing of an animation node.

    :param animation_id: Animation id.
    :param duration: Duration of the animation.
    :param delay: Delay of the animation.
    '''
    ...

@event_class('Animation.animationCanceled')
@dataclass
class AnimationCanceled:
    '''
    Event for when an animation has been cancelled.
    '''
    id_: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AnimationCanceled:
        ...



@event_class('Animation.animationCreated')
@dataclass
class AnimationCreated:
    '''
    Event for each animation that has been created.
    '''
    id_: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AnimationCreated:
        ...



@event_class('Animation.animationStarted')
@dataclass
class AnimationStarted:
    '''
    Event for animation that has been started.
    '''
    animation: Animation
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AnimationStarted:
        ...



@event_class('Animation.animationUpdated')
@dataclass
class AnimationUpdated:
    '''
    Event for animation that has been updated.
    '''
    animation: Animation
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AnimationUpdated:
        ...
