"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
from . import dom, page

@dataclass
class CreditCard:
    number: str
    name: str
    expiry_month: str
    expiry_year: str
    cvc: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CreditCard:
        ...



@dataclass
class AddressField:
    name: str
    value: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AddressField:
        ...



@dataclass
class AddressFields:
    '''
    A list of address fields.
    '''
    fields: typing.List[AddressField]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AddressFields:
        ...



@dataclass
class Address:
    fields: typing.List[AddressField]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Address:
        ...



@dataclass
class AddressUI:
    '''
    Defines how an address can be displayed like in chrome://settings/addresses.
    Address UI is a two dimensional array, each inner array is an "address information line", and when rendered in a UI surface should be displayed as such.
    The following address UI for instance:
    [[{name: "GIVE_NAME", value: "Jon"}, {name: "FAMILY_NAME", value: "Doe"}], [{name: "CITY", value: "Munich"}, {name: "ZIP", value: "81456"}]]
    should allow the receiver to render:
    Jon Doe
    Munich 81456
    '''
    address_fields: typing.List[AddressFields]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AddressUI:
        ...



class FillingStrategy(enum.Enum):
    '''
    Specified whether a filled field was done so by using the html autocomplete attribute or autofill heuristics.
    '''
    AUTOCOMPLETE_ATTRIBUTE = ...
    AUTOFILL_INFERRED = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> FillingStrategy:
        ...



@dataclass
class FilledField:
    html_type: str
    id_: str
    name: str
    value: str
    autofill_type: str
    filling_strategy: FillingStrategy
    frame_id: page.FrameId
    field_id: dom.BackendNodeId
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> FilledField:
        ...



def trigger(field_id: dom.BackendNodeId, frame_id: typing.Optional[page.FrameId] = ..., card: typing.Optional[CreditCard] = ..., address: typing.Optional[Address] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Trigger autofill on a form identified by the fieldId.
    If the field and related form cannot be autofilled, returns an error.

    :param field_id: Identifies a field that serves as an anchor for autofill.
    :param frame_id: *(Optional)* Identifies the frame that field belongs to.
    :param card: *(Optional)* Credit card information to fill out the form. Credit card data is not saved.  Mutually exclusive with ```address````.
    :param address: *(Optional)* Address to fill out the form. Address data is not saved. Mutually exclusive with ````card```.
    '''
    ...

def set_addresses(addresses: typing.List[Address]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Set addresses so that developers can verify their forms implementation.

    :param addresses:
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disables autofill domain notifications.
    '''
    ...

def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables autofill domain notifications.
    '''
    ...

@event_class('Autofill.addressFormFilled')
@dataclass
class AddressFormFilled:
    '''
    Emitted when an address form is filled.
    '''
    filled_fields: typing.List[FilledField]
    address_ui: AddressUI
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AddressFormFilled:
        ...
