"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
from . import network, service_worker

class ServiceName(enum.Enum):
    '''
    The Background Service that will be associated with the commands/events.
    Every Background Service operates independently, but they share the same
    API.
    '''
    BACKGROUND_FETCH = ...
    BACKGROUND_SYNC = ...
    PUSH_MESSAGING = ...
    NOTIFICATIONS = ...
    PAYMENT_HANDLER = ...
    PERIODIC_BACKGROUND_SYNC = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ServiceName:
        ...



@dataclass
class EventMetadata:
    '''
    A key-value pair for additional event information to pass along.
    '''
    key: str
    value: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> EventMetadata:
        ...



@dataclass
class BackgroundServiceEvent:
    timestamp: network.TimeSinceEpoch
    origin: str
    service_worker_registration_id: service_worker.RegistrationID
    service: ServiceName
    event_name: str
    instance_id: str
    event_metadata: typing.List[EventMetadata]
    storage_key: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BackgroundServiceEvent:
        ...



def start_observing(service: ServiceName) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables event updates for the service.

    :param service:
    '''
    ...

def stop_observing(service: ServiceName) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disables event updates for the service.

    :param service:
    '''
    ...

def set_recording(should_record: bool, service: ServiceName) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Set the recording state for the service.

    :param should_record:
    :param service:
    '''
    ...

def clear_events(service: ServiceName) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Clears all stored data for the service.

    :param service:
    '''
    ...

@event_class('BackgroundService.recordingStateChanged')
@dataclass
class RecordingStateChanged:
    '''
    Called when the recording state for the service has been updated.
    '''
    is_recording: bool
    service: ServiceName
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RecordingStateChanged:
        ...



@event_class('BackgroundService.backgroundServiceEventReceived')
@dataclass
class BackgroundServiceEventReceived:
    '''
    Called with all existing backgroundServiceEvents when enabled, and all new
    events afterwards if enabled and recording.
    '''
    background_service_event: BackgroundServiceEvent
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BackgroundServiceEventReceived:
        ...
