"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class

class CentralState(enum.Enum):
    '''
    Indicates the various states of Central.
    '''
    ABSENT = ...
    POWERED_OFF = ...
    POWERED_ON = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CentralState:
        ...



class GATTOperationType(enum.Enum):
    '''
    Indicates the various types of GATT event.
    '''
    CONNECTION = ...
    DISCOVERY = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> GATTOperationType:
        ...



class CharacteristicWriteType(enum.Enum):
    '''
    Indicates the various types of characteristic write.
    '''
    WRITE_DEFAULT_DEPRECATED = ...
    WRITE_WITH_RESPONSE = ...
    WRITE_WITHOUT_RESPONSE = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CharacteristicWriteType:
        ...



class CharacteristicOperationType(enum.Enum):
    '''
    Indicates the various types of characteristic operation.
    '''
    READ = ...
    WRITE = ...
    SUBSCRIBE_TO_NOTIFICATIONS = ...
    UNSUBSCRIBE_FROM_NOTIFICATIONS = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CharacteristicOperationType:
        ...



class DescriptorOperationType(enum.Enum):
    '''
    Indicates the various types of descriptor operation.
    '''
    READ = ...
    WRITE = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> DescriptorOperationType:
        ...



@dataclass
class ManufacturerData:
    '''
    Stores the manufacturer data
    '''
    key: int
    data: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ManufacturerData:
        ...



@dataclass
class ScanRecord:
    '''
    Stores the byte data of the advertisement packet sent by a Bluetooth device.
    '''
    name: typing.Optional[str] = ...
    uuids: typing.Optional[typing.List[str]] = ...
    appearance: typing.Optional[int] = ...
    tx_power: typing.Optional[int] = ...
    manufacturer_data: typing.Optional[typing.List[ManufacturerData]] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScanRecord:
        ...



@dataclass
class ScanEntry:
    '''
    Stores the advertisement packet information that is sent by a Bluetooth device.
    '''
    device_address: str
    rssi: int
    scan_record: ScanRecord
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScanEntry:
        ...



@dataclass
class CharacteristicProperties:
    '''
    Describes the properties of a characteristic. This follows Bluetooth Core
    Specification BT 4.2 Vol 3 Part G 3.3.1. Characteristic Properties.
    '''
    broadcast: typing.Optional[bool] = ...
    read: typing.Optional[bool] = ...
    write_without_response: typing.Optional[bool] = ...
    write: typing.Optional[bool] = ...
    notify: typing.Optional[bool] = ...
    indicate: typing.Optional[bool] = ...
    authenticated_signed_writes: typing.Optional[bool] = ...
    extended_properties: typing.Optional[bool] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CharacteristicProperties:
        ...



def enable(state: CentralState, le_supported: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enable the BluetoothEmulation domain.

    :param state: State of the simulated central.
    :param le_supported: If the simulated central supports low-energy.
    '''
    ...

def set_simulated_central_state(state: CentralState) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Set the state of the simulated central.

    :param state: State of the simulated central.
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disable the BluetoothEmulation domain.
    '''
    ...

def simulate_preconnected_peripheral(address: str, name: str, manufacturer_data: typing.List[ManufacturerData], known_service_uuids: typing.List[str]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Simulates a peripheral with ``address``, ``name`` and ``knownServiceUuids``
    that has already been connected to the system.

    :param address:
    :param name:
    :param manufacturer_data:
    :param known_service_uuids:
    '''
    ...

def simulate_advertisement(entry: ScanEntry) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Simulates an advertisement packet described in ``entry`` being received by
    the central.

    :param entry:
    '''
    ...

def simulate_gatt_operation_response(address: str, type_: GATTOperationType, code: int) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Simulates the response code from the peripheral with ``address`` for a
    GATT operation of ``type``. The ``code`` value follows the HCI Error Codes from
    Bluetooth Core Specification Vol 2 Part D 1.3 List Of Error Codes.

    :param address:
    :param type_:
    :param code:
    '''
    ...

def simulate_characteristic_operation_response(characteristic_id: str, type_: CharacteristicOperationType, code: int, data: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Simulates the response from the characteristic with ``characteristicId`` for a
    characteristic operation of ``type``. The ``code`` value follows the Error
    Codes from Bluetooth Core Specification Vol 3 Part F 3.4.1.1 Error Response.
    The ``data`` is expected to exist when simulating a successful read operation
    response.

    :param characteristic_id:
    :param type_:
    :param code:
    :param data: *(Optional)*
    '''
    ...

def simulate_descriptor_operation_response(descriptor_id: str, type_: DescriptorOperationType, code: int, data: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Simulates the response from the descriptor with ``descriptorId`` for a
    descriptor operation of ``type``. The ``code`` value follows the Error
    Codes from Bluetooth Core Specification Vol 3 Part F 3.4.1.1 Error Response.
    The ``data`` is expected to exist when simulating a successful read operation
    response.

    :param descriptor_id:
    :param type_:
    :param code:
    :param data: *(Optional)*
    '''
    ...

def add_service(address: str, service_uuid: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
    '''
    Adds a service with ``serviceUuid`` to the peripheral with ``address``.

    :param address:
    :param service_uuid:
    :returns: An identifier that uniquely represents this service.
    '''
    ...

def remove_service(service_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Removes the service respresented by ``serviceId`` from the simulated central.

    :param service_id:
    '''
    ...

def add_characteristic(service_id: str, characteristic_uuid: str, properties: CharacteristicProperties) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
    '''
    Adds a characteristic with ``characteristicUuid`` and ``properties`` to the
    service represented by ``serviceId``.

    :param service_id:
    :param characteristic_uuid:
    :param properties:
    :returns: An identifier that uniquely represents this characteristic.
    '''
    ...

def remove_characteristic(characteristic_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Removes the characteristic respresented by ``characteristicId`` from the
    simulated central.

    :param characteristic_id:
    '''
    ...

def add_descriptor(characteristic_id: str, descriptor_uuid: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
    '''
    Adds a descriptor with ``descriptorUuid`` to the characteristic respresented
    by ``characteristicId``.

    :param characteristic_id:
    :param descriptor_uuid:
    :returns: An identifier that uniquely represents this descriptor.
    '''
    ...

def remove_descriptor(descriptor_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Removes the descriptor with ``descriptorId`` from the simulated central.

    :param descriptor_id:
    '''
    ...

def simulate_gatt_disconnection(address: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Simulates a GATT disconnection from the peripheral with ``address``.

    :param address:
    '''
    ...

@event_class('BluetoothEmulation.gattOperationReceived')
@dataclass
class GattOperationReceived:
    '''
    Event for when a GATT operation of ``type`` to the peripheral with ``address``
    happened.
    '''
    address: str
    type_: GATTOperationType
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> GattOperationReceived:
        ...



@event_class('BluetoothEmulation.characteristicOperationReceived')
@dataclass
class CharacteristicOperationReceived:
    '''
    Event for when a characteristic operation of ``type`` to the characteristic
    respresented by ``characteristicId`` happened. ``data`` and ``writeType`` is
    expected to exist when ``type`` is write.
    '''
    characteristic_id: str
    type_: CharacteristicOperationType
    data: typing.Optional[str]
    write_type: typing.Optional[CharacteristicWriteType]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CharacteristicOperationReceived:
        ...



@event_class('BluetoothEmulation.descriptorOperationReceived')
@dataclass
class DescriptorOperationReceived:
    '''
    Event for when a descriptor operation of ``type`` to the descriptor
    respresented by ``descriptorId`` happened. ``data`` is expected to exist when
    ``type`` is write.
    '''
    descriptor_id: str
    type_: DescriptorOperationType
    data: typing.Optional[str]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DescriptorOperationReceived:
        ...
