"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
from . import page, target
from deprecated.sphinx import deprecated

class BrowserContextID(str):
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> BrowserContextID:
        ...

    def __repr__(self) -> str:
        ...



class WindowID(int):
    def to_json(self) -> int:
        ...

    @classmethod
    def from_json(cls, json: int) -> WindowID:
        ...

    def __repr__(self) -> str:
        ...



class WindowState(enum.Enum):
    '''
    The state of the browser window.
    '''
    NORMAL = ...
    MINIMIZED = ...
    MAXIMIZED = ...
    FULLSCREEN = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> WindowState:
        ...



@dataclass
class Bounds:
    '''
    Browser window bounds information
    '''
    left: typing.Optional[int] = ...
    top: typing.Optional[int] = ...
    width: typing.Optional[int] = ...
    height: typing.Optional[int] = ...
    window_state: typing.Optional[WindowState] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Bounds:
        ...



class PermissionType(enum.Enum):
    AR = ...
    AUDIO_CAPTURE = ...
    AUTOMATIC_FULLSCREEN = ...
    BACKGROUND_FETCH = ...
    BACKGROUND_SYNC = ...
    CAMERA_PAN_TILT_ZOOM = ...
    CAPTURED_SURFACE_CONTROL = ...
    CLIPBOARD_READ_WRITE = ...
    CLIPBOARD_SANITIZED_WRITE = ...
    DISPLAY_CAPTURE = ...
    DURABLE_STORAGE = ...
    GEOLOCATION = ...
    HAND_TRACKING = ...
    IDLE_DETECTION = ...
    KEYBOARD_LOCK = ...
    LOCAL_FONTS = ...
    LOCAL_NETWORK = ...
    LOCAL_NETWORK_ACCESS = ...
    LOOPBACK_NETWORK = ...
    MIDI = ...
    MIDI_SYSEX = ...
    NFC = ...
    NOTIFICATIONS = ...
    PAYMENT_HANDLER = ...
    PERIODIC_BACKGROUND_SYNC = ...
    POINTER_LOCK = ...
    PROTECTED_MEDIA_IDENTIFIER = ...
    SENSORS = ...
    SMART_CARD = ...
    SPEAKER_SELECTION = ...
    STORAGE_ACCESS = ...
    TOP_LEVEL_STORAGE_ACCESS = ...
    VIDEO_CAPTURE = ...
    VR = ...
    WAKE_LOCK_SCREEN = ...
    WAKE_LOCK_SYSTEM = ...
    WEB_APP_INSTALLATION = ...
    WEB_PRINTING = ...
    WINDOW_MANAGEMENT = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> PermissionType:
        ...



class PermissionSetting(enum.Enum):
    GRANTED = ...
    DENIED = ...
    PROMPT = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> PermissionSetting:
        ...



@dataclass
class PermissionDescriptor:
    '''
    Definition of PermissionDescriptor defined in the Permissions API:
    https://w3c.github.io/permissions/#dom-permissiondescriptor.
    '''
    name: str
    sysex: typing.Optional[bool] = ...
    user_visible_only: typing.Optional[bool] = ...
    allow_without_sanitization: typing.Optional[bool] = ...
    allow_without_gesture: typing.Optional[bool] = ...
    pan_tilt_zoom: typing.Optional[bool] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PermissionDescriptor:
        ...



class BrowserCommandId(enum.Enum):
    '''
    Browser command ids used by executeBrowserCommand.
    '''
    OPEN_TAB_SEARCH = ...
    CLOSE_TAB_SEARCH = ...
    OPEN_GLIC = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> BrowserCommandId:
        ...



@dataclass
class Bucket:
    '''
    Chrome histogram bucket.
    '''
    low: int
    high: int
    count: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Bucket:
        ...



@dataclass
class Histogram:
    '''
    Chrome histogram.
    '''
    name: str
    sum_: int
    count: int
    buckets: typing.List[Bucket]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Histogram:
        ...



class PrivacySandboxAPI(enum.Enum):
    BIDDING_AND_AUCTION_SERVICES = ...
    TRUSTED_KEY_VALUE = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> PrivacySandboxAPI:
        ...



def set_permission(permission: PermissionDescriptor, setting: PermissionSetting, origin: typing.Optional[str] = ..., embedded_origin: typing.Optional[str] = ..., browser_context_id: typing.Optional[BrowserContextID] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Set permission settings for given embedding and embedded origins.

    **EXPERIMENTAL**

    :param permission: Descriptor of permission to override.
    :param setting: Setting of the permission.
    :param origin: *(Optional)* Embedding origin the permission applies to, all origins if not specified.
    :param embedded_origin: *(Optional)* Embedded origin the permission applies to. It is ignored unless the embedding origin is present and valid. If the embedding origin is provided but the embedded origin isn't, the embedding origin is used as the embedded origin.
    :param browser_context_id: *(Optional)* Context to override. When omitted, default browser context is used.
    '''
    ...

@deprecated(version="1.3")
def grant_permissions(permissions: typing.List[PermissionType], origin: typing.Optional[str] = ..., browser_context_id: typing.Optional[BrowserContextID] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Grant specific permissions to the given origin and reject all others. Deprecated. Use
    setPermission instead.

    .. deprecated:: 1.3

    **EXPERIMENTAL**

    :param permissions:
    :param origin: *(Optional)* Origin the permission applies to, all origins if not specified.
    :param browser_context_id: *(Optional)* BrowserContext to override permissions. When omitted, default browser context is used.
    '''
    ...

def reset_permissions(browser_context_id: typing.Optional[BrowserContextID] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Reset all permission management for all origins.

    :param browser_context_id: *(Optional)* BrowserContext to reset permissions. When omitted, default browser context is used.
    '''
    ...

def set_download_behavior(behavior: str, browser_context_id: typing.Optional[BrowserContextID] = ..., download_path: typing.Optional[str] = ..., events_enabled: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Set the behavior when downloading a file.

    **EXPERIMENTAL**

    :param behavior: Whether to allow all or deny all download requests, or use default Chrome behavior if available (otherwise deny). ``allowAndName`` allows download and names files according to their download guids.
    :param browser_context_id: *(Optional)* BrowserContext to set download behavior. When omitted, default browser context is used.
    :param download_path: *(Optional)* The default path to save downloaded files to. This is required if behavior is set to 'allow' or 'allowAndName'.
    :param events_enabled: *(Optional)* Whether to emit download events (defaults to false).
    '''
    ...

def cancel_download(guid: str, browser_context_id: typing.Optional[BrowserContextID] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Cancel a download if in progress

    **EXPERIMENTAL**

    :param guid: Global unique identifier of the download.
    :param browser_context_id: *(Optional)* BrowserContext to perform the action in. When omitted, default browser context is used.
    '''
    ...

def close() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Close browser gracefully.
    '''
    ...

def crash() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Crashes browser on the main thread.

    **EXPERIMENTAL**
    '''
    ...

def crash_gpu_process() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Crashes GPU process.

    **EXPERIMENTAL**
    '''
    ...

def get_version() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[str, str, str, str, str]]:
    '''
    Returns version information.

    :returns: A tuple with the following items:

        0. **protocolVersion** - Protocol version.
        1. **product** - Product name.
        2. **revision** - Product revision.
        3. **userAgent** - User-Agent.
        4. **jsVersion** - V8 version.
    '''
    ...

def get_browser_command_line() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[str]]:
    '''
    Returns the command line switches for the browser process if, and only if
    --enable-automation is on the commandline.

    **EXPERIMENTAL**

    :returns: Commandline parameters
    '''
    ...

def get_histograms(query: typing.Optional[str] = ..., delta: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[Histogram]]:
    '''
    Get Chrome histograms.

    **EXPERIMENTAL**

    :param query: *(Optional)* Requested substring in name. Only histograms which have query as a substring in their name are extracted. An empty or absent query returns all histograms.
    :param delta: *(Optional)* If true, retrieve delta since last delta call.
    :returns: Histograms.
    '''
    ...

def get_histogram(name: str, delta: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, Histogram]:
    '''
    Get a Chrome histogram by name.

    **EXPERIMENTAL**

    :param name: Requested histogram name.
    :param delta: *(Optional)* If true, retrieve delta since last delta call.
    :returns: Histogram.
    '''
    ...

def get_window_bounds(window_id: WindowID) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, Bounds]:
    '''
    Get position and size of the browser window.

    **EXPERIMENTAL**

    :param window_id: Browser window id.
    :returns: Bounds information of the window. When window state is 'minimized', the restored window position and size are returned.
    '''
    ...

def get_window_for_target(target_id: typing.Optional[target.TargetID] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[WindowID, Bounds]]:
    '''
    Get the browser window that contains the devtools target.

    **EXPERIMENTAL**

    :param target_id: *(Optional)* Devtools agent host id. If called as a part of the session, associated targetId is used.
    :returns: A tuple with the following items:

        0. **windowId** - Browser window id.
        1. **bounds** - Bounds information of the window. When window state is 'minimized', the restored window position and size are returned.
    '''
    ...

def set_window_bounds(window_id: WindowID, bounds: Bounds) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Set position and/or size of the browser window.

    **EXPERIMENTAL**

    :param window_id: Browser window id.
    :param bounds: New window bounds. The 'minimized', 'maximized' and 'fullscreen' states cannot be combined with 'left', 'top', 'width' or 'height'. Leaves unspecified fields unchanged.
    '''
    ...

def set_contents_size(window_id: WindowID, width: typing.Optional[int] = ..., height: typing.Optional[int] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Set size of the browser contents resizing browser window as necessary.

    **EXPERIMENTAL**

    :param window_id: Browser window id.
    :param width: *(Optional)* The window contents width in DIP. Assumes current width if omitted. Must be specified if 'height' is omitted.
    :param height: *(Optional)* The window contents height in DIP. Assumes current height if omitted. Must be specified if 'width' is omitted.
    '''
    ...

def set_dock_tile(badge_label: typing.Optional[str] = ..., image: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Set dock tile details, platform-specific.

    **EXPERIMENTAL**

    :param badge_label: *(Optional)*
    :param image: *(Optional)* Png encoded image. (Encoded as a base64 string when passed over JSON)
    '''
    ...

def execute_browser_command(command_id: BrowserCommandId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Invoke custom browser commands used by telemetry.

    **EXPERIMENTAL**

    :param command_id:
    '''
    ...

def add_privacy_sandbox_enrollment_override(url: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Allows a site to use privacy sandbox features that require enrollment
    without the site actually being enrolled. Only supported on page targets.

    :param url:
    '''
    ...

def add_privacy_sandbox_coordinator_key_config(api: PrivacySandboxAPI, coordinator_origin: str, key_config: str, browser_context_id: typing.Optional[BrowserContextID] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Configures encryption keys used with a given privacy sandbox API to talk
    to a trusted coordinator.  Since this is intended for test automation only,
    coordinatorOrigin must be a .test domain. No existing coordinator
    configuration for the origin may exist.

    :param api:
    :param coordinator_origin:
    :param key_config:
    :param browser_context_id: *(Optional)* BrowserContext to perform the action in. When omitted, default browser context is used.
    '''
    ...

@event_class('Browser.downloadWillBegin')
@dataclass
class DownloadWillBegin:
    '''
    **EXPERIMENTAL**

    Fired when page is about to start a download.
    '''
    frame_id: page.FrameId
    guid: str
    url: str
    suggested_filename: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DownloadWillBegin:
        ...



@event_class('Browser.downloadProgress')
@dataclass
class DownloadProgress:
    '''
    **EXPERIMENTAL**

    Fired when download makes progress. Last call has ``done`` == true.
    '''
    guid: str
    total_bytes: float
    received_bytes: float
    state: str
    file_path: typing.Optional[str]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DownloadProgress:
        ...
