"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT
from . import storage

class CacheId(str):
    '''
    Unique identifier of the Cache object.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CacheId:
        ...

    def __repr__(self) -> str:
        ...



class CachedResponseType(enum.Enum):
    '''
    type of HTTP response cached
    '''
    BASIC = ...
    CORS = ...
    DEFAULT = ...
    ERROR = ...
    OPAQUE_RESPONSE = ...
    OPAQUE_REDIRECT = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CachedResponseType:
        ...



@dataclass
class DataEntry:
    '''
    Data entry.
    '''
    request_url: str
    request_method: str
    request_headers: typing.List[Header]
    response_time: float
    response_status: int
    response_status_text: str
    response_type: CachedResponseType
    response_headers: typing.List[Header]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DataEntry:
        ...



@dataclass
class Cache:
    '''
    Cache identifier.
    '''
    cache_id: CacheId
    security_origin: str
    storage_key: str
    cache_name: str
    storage_bucket: typing.Optional[storage.StorageBucket] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Cache:
        ...



@dataclass
class Header:
    name: str
    value: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Header:
        ...



@dataclass
class CachedResponse:
    '''
    Cached response
    '''
    body: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CachedResponse:
        ...



def delete_cache(cache_id: CacheId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Deletes a cache.

    :param cache_id: Id of cache for deletion.
    '''
    ...

def delete_entry(cache_id: CacheId, request: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Deletes a cache entry.

    :param cache_id: Id of cache where the entry will be deleted.
    :param request: URL spec of the request.
    '''
    ...

def request_cache_names(security_origin: typing.Optional[str] = ..., storage_key: typing.Optional[str] = ..., storage_bucket: typing.Optional[storage.StorageBucket] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[Cache]]:
    '''
    Requests cache names.

    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    :returns: Caches for the security origin.
    '''
    ...

def request_cached_response(cache_id: CacheId, request_url: str, request_headers: typing.List[Header]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, CachedResponse]:
    '''
    Fetches cache entry.

    :param cache_id: Id of cache that contains the entry.
    :param request_url: URL spec of the request.
    :param request_headers: headers of the request.
    :returns: Response read from the cache.
    '''
    ...

def request_entries(cache_id: CacheId, skip_count: typing.Optional[int] = ..., page_size: typing.Optional[int] = ..., path_filter: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[typing.List[DataEntry], float]]:
    '''
    Requests data from cache.

    :param cache_id: ID of cache to get entries from.
    :param skip_count: *(Optional)* Number of records to skip.
    :param page_size: *(Optional)* Number of records to fetch.
    :param path_filter: *(Optional)* If present, only return the entries containing this substring in the path
    :returns: A tuple with the following items:

        0. **cacheDataEntries** - Array of object store data entries.
        1. **returnCount** - Count of returned entries from this storage. If pathFilter is empty, it is the count of all entries from this storage.
    '''
    ...
