"""
This type stub file was generated by pyright.
"""

import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class

@dataclass
class Sink:
    name: str
    id_: str
    session: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Sink:
        ...



def enable(presentation_url: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Starts observing for sinks that can be used for tab mirroring, and if set,
    sinks compatible with ``presentationUrl`` as well. When sinks are found, a
    ``sinksUpdated`` event is fired.
    Also starts observing for issue messages. When an issue is added or removed,
    an ``issueUpdated`` event is fired.

    :param presentation_url: *(Optional)*
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Stops observing for sinks and issues.
    '''
    ...

def set_sink_to_use(sink_name: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets a sink to be used when the web page requests the browser to choose a
    sink via Presentation API, Remote Playback API, or Cast SDK.

    :param sink_name:
    '''
    ...

def start_desktop_mirroring(sink_name: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Starts mirroring the desktop to the sink.

    :param sink_name:
    '''
    ...

def start_tab_mirroring(sink_name: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Starts mirroring the tab to the sink.

    :param sink_name:
    '''
    ...

def stop_casting(sink_name: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Stops the active Cast session on the sink.

    :param sink_name:
    '''
    ...

@event_class('Cast.sinksUpdated')
@dataclass
class SinksUpdated:
    '''
    This is fired whenever the list of available sinks changes. A sink is a
    device or a software surface that you can cast to.
    '''
    sinks: typing.List[Sink]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SinksUpdated:
        ...



@event_class('Cast.issueUpdated')
@dataclass
class IssueUpdated:
    '''
    This is fired whenever the outstanding issue/error message changes.
    ``issueMessage`` is empty if there is no issue.
    '''
    issue_message: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> IssueUpdated:
        ...
