"""
This type stub file was generated by pyright.
"""

import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class

@dataclass
class ConsoleMessage:
    '''
    Console message.
    '''
    source: str
    level: str
    text: str
    url: typing.Optional[str] = ...
    line: typing.Optional[int] = ...
    column: typing.Optional[int] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ConsoleMessage:
        ...



def clear_messages() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Does nothing.
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disables console domain, prevents further console messages from being reported to the client.
    '''
    ...

def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables console domain, sends the messages collected so far to the client by means of the
    ``messageAdded`` notification.
    '''
    ...

@event_class('Console.messageAdded')
@dataclass
class MessageAdded:
    '''
    Issued when new console message is added.
    '''
    message: ConsoleMessage
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> MessageAdded:
        ...
