"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
from . import runtime
from deprecated.sphinx import deprecated

class BreakpointId(str):
    '''
    Breakpoint identifier.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> BreakpointId:
        ...

    def __repr__(self) -> str:
        ...



class CallFrameId(str):
    '''
    Call frame identifier.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CallFrameId:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class Location:
    '''
    Location in the source code.
    '''
    script_id: runtime.ScriptId
    line_number: int
    column_number: typing.Optional[int] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Location:
        ...



@dataclass
class ScriptPosition:
    '''
    Location in the source code.
    '''
    line_number: int
    column_number: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScriptPosition:
        ...



@dataclass
class LocationRange:
    '''
    Location range within one script.
    '''
    script_id: runtime.ScriptId
    start: ScriptPosition
    end: ScriptPosition
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LocationRange:
        ...



@dataclass
class CallFrame:
    '''
    JavaScript call frame. Array of call frames form the call stack.
    '''
    call_frame_id: CallFrameId
    function_name: str
    location: Location
    url: str
    scope_chain: typing.List[Scope]
    this: runtime.RemoteObject
    function_location: typing.Optional[Location] = ...
    return_value: typing.Optional[runtime.RemoteObject] = ...
    can_be_restarted: typing.Optional[bool] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CallFrame:
        ...



@dataclass
class Scope:
    '''
    Scope description.
    '''
    type_: str
    object_: runtime.RemoteObject
    name: typing.Optional[str] = ...
    start_location: typing.Optional[Location] = ...
    end_location: typing.Optional[Location] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Scope:
        ...



@dataclass
class SearchMatch:
    '''
    Search match for resource.
    '''
    line_number: float
    line_content: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SearchMatch:
        ...



@dataclass
class BreakLocation:
    script_id: runtime.ScriptId
    line_number: int
    column_number: typing.Optional[int] = ...
    type_: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BreakLocation:
        ...



@dataclass
class WasmDisassemblyChunk:
    lines: typing.List[str]
    bytecode_offsets: typing.List[int]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WasmDisassemblyChunk:
        ...



class ScriptLanguage(enum.Enum):
    '''
    Enum of possible script languages.
    '''
    JAVA_SCRIPT = ...
    WEB_ASSEMBLY = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ScriptLanguage:
        ...



@dataclass
class DebugSymbols:
    '''
    Debug symbols available for a wasm script.
    '''
    type_: str
    external_url: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DebugSymbols:
        ...



@dataclass
class ResolvedBreakpoint:
    breakpoint_id: BreakpointId
    location: Location
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ResolvedBreakpoint:
        ...



def continue_to_location(location: Location, target_call_frames: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Continues execution until specific location is reached.

    :param location: Location to continue to.
    :param target_call_frames: *(Optional)*
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disables debugger for given page.
    '''
    ...

def enable(max_scripts_cache_size: typing.Optional[float] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, runtime.UniqueDebuggerId]:
    '''
    Enables debugger for the given page. Clients should not assume that the debugging has been
    enabled until the result for this command is received.

    :param max_scripts_cache_size: **(EXPERIMENTAL)** *(Optional)* The maximum size in bytes of collected scripts (not referenced by other heap objects) the debugger can hold. Puts no limit if parameter is omitted.
    :returns: Unique identifier of the debugger.
    '''
    ...

def evaluate_on_call_frame(call_frame_id: CallFrameId, expression: str, object_group: typing.Optional[str] = ..., include_command_line_api: typing.Optional[bool] = ..., silent: typing.Optional[bool] = ..., return_by_value: typing.Optional[bool] = ..., generate_preview: typing.Optional[bool] = ..., throw_on_side_effect: typing.Optional[bool] = ..., timeout: typing.Optional[runtime.TimeDelta] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[runtime.RemoteObject, typing.Optional[runtime.ExceptionDetails]]]:
    '''
    Evaluates expression on a given call frame.

    :param call_frame_id: Call frame identifier to evaluate on.
    :param expression: Expression to evaluate.
    :param object_group: *(Optional)* String object group name to put result into (allows rapid releasing resulting object handles using ```releaseObjectGroup````).
    :param include_command_line_api: *(Optional)* Specifies whether command line API should be available to the evaluated expression, defaults to false.
    :param silent: *(Optional)* In silent mode exceptions thrown during evaluation are not reported and do not pause execution. Overrides ````setPauseOnException``` state.
    :param return_by_value: *(Optional)* Whether the result is expected to be a JSON object that should be sent by value.
    :param generate_preview: **(EXPERIMENTAL)** *(Optional)* Whether preview should be generated for the result.
    :param throw_on_side_effect: *(Optional)* Whether to throw an exception if side effect cannot be ruled out during evaluation.
    :param timeout: **(EXPERIMENTAL)** *(Optional)* Terminate execution after timing out (number of milliseconds).
    :returns: A tuple with the following items:

        0. **result** - Object wrapper for the evaluation result.
        1. **exceptionDetails** - *(Optional)* Exception details.
    '''
    ...

def get_possible_breakpoints(start: Location, end: typing.Optional[Location] = ..., restrict_to_function: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[BreakLocation]]:
    '''
    Returns possible locations for breakpoint. scriptId in start and end range locations should be
    the same.

    :param start: Start of range to search possible breakpoint locations in.
    :param end: *(Optional)* End of range to search possible breakpoint locations in (excluding). When not specified, end of scripts is used as end of range.
    :param restrict_to_function: *(Optional)* Only consider locations which are in the same (non-nested) function as start.
    :returns: List of the possible breakpoint locations.
    '''
    ...

def get_script_source(script_id: runtime.ScriptId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[str, typing.Optional[str]]]:
    '''
    Returns source for the script with given id.

    :param script_id: Id of the script to get source for.
    :returns: A tuple with the following items:

        0. **scriptSource** - Script source (empty in case of Wasm bytecode).
        1. **bytecode** - *(Optional)* Wasm bytecode. (Encoded as a base64 string when passed over JSON)
    '''
    ...

def disassemble_wasm_module(script_id: runtime.ScriptId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[typing.Optional[str], int, typing.List[int], WasmDisassemblyChunk]]:
    '''


    **EXPERIMENTAL**

    :param script_id: Id of the script to disassemble
    :returns: A tuple with the following items:

        0. **streamId** - *(Optional)* For large modules, return a stream from which additional chunks of disassembly can be read successively.
        1. **totalNumberOfLines** - The total number of lines in the disassembly text.
        2. **functionBodyOffsets** - The offsets of all function bodies, in the format [start1, end1, start2, end2, ...] where all ends are exclusive.
        3. **chunk** - The first chunk of disassembly.
    '''
    ...

def next_wasm_disassembly_chunk(stream_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, WasmDisassemblyChunk]:
    '''
    Disassemble the next chunk of lines for the module corresponding to the
    stream. If disassembly is complete, this API will invalidate the streamId
    and return an empty chunk. Any subsequent calls for the now invalid stream
    will return errors.

    **EXPERIMENTAL**

    :param stream_id:
    :returns: The next chunk of disassembly.
    '''
    ...

@deprecated(version="1.3")
def get_wasm_bytecode(script_id: runtime.ScriptId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
    '''
    This command is deprecated. Use getScriptSource instead.

    .. deprecated:: 1.3

    :param script_id: Id of the Wasm script to get source for.
    :returns: Script source. (Encoded as a base64 string when passed over JSON)
    '''
    ...

def get_stack_trace(stack_trace_id: runtime.StackTraceId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, runtime.StackTrace]:
    '''
    Returns stack trace with given ``stackTraceId``.

    **EXPERIMENTAL**

    :param stack_trace_id:
    :returns:
    '''
    ...

def pause() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Stops on the next JavaScript statement.
    '''
    ...

@deprecated(version="1.3")
def pause_on_async_call(parent_stack_trace_id: runtime.StackTraceId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''


    .. deprecated:: 1.3

    **EXPERIMENTAL**

    :param parent_stack_trace_id: Debugger will pause when async call with given stack trace is started.
    '''
    ...

def remove_breakpoint(breakpoint_id: BreakpointId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Removes JavaScript breakpoint.

    :param breakpoint_id:
    '''
    ...

def restart_frame(call_frame_id: CallFrameId, mode: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[typing.List[CallFrame], typing.Optional[runtime.StackTrace], typing.Optional[runtime.StackTraceId]]]:
    '''
    Restarts particular call frame from the beginning. The old, deprecated
    behavior of ``restartFrame`` is to stay paused and allow further CDP commands
    after a restart was scheduled. This can cause problems with restarting, so
    we now continue execution immediatly after it has been scheduled until we
    reach the beginning of the restarted frame.

    To stay back-wards compatible, ``restartFrame`` now expects a ``mode``
    parameter to be present. If the ``mode`` parameter is missing, ``restartFrame``
    errors out.

    The various return values are deprecated and ``callFrames`` is always empty.
    Use the call frames from the ``Debugger#paused`` events instead, that fires
    once V8 pauses at the beginning of the restarted function.

    :param call_frame_id: Call frame identifier to evaluate on.
    :param mode: **(EXPERIMENTAL)** *(Optional)* The ```mode```` parameter must be present and set to 'StepInto', otherwise ````restartFrame``` will error out.
    :returns: A tuple with the following items:

        0. **callFrames** - New stack trace.
        1. **asyncStackTrace** - *(Optional)* Async stack trace, if any.
        2. **asyncStackTraceId** - *(Optional)* Async stack trace, if any.
    '''
    ...

def resume(terminate_on_resume: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Resumes JavaScript execution.

    :param terminate_on_resume: *(Optional)* Set to true to terminate execution upon resuming execution. In contrast to Runtime.terminateExecution, this will allows to execute further JavaScript (i.e. via evaluation) until execution of the paused code is actually resumed, at which point termination is triggered. If execution is currently not paused, this parameter has no effect.
    '''
    ...

def search_in_content(script_id: runtime.ScriptId, query: str, case_sensitive: typing.Optional[bool] = ..., is_regex: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[SearchMatch]]:
    '''
    Searches for given string in script content.

    :param script_id: Id of the script to search in.
    :param query: String to search for.
    :param case_sensitive: *(Optional)* If true, search is case sensitive.
    :param is_regex: *(Optional)* If true, treats string parameter as regex.
    :returns: List of search matches.
    '''
    ...

def set_async_call_stack_depth(max_depth: int) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables or disables async call stacks tracking.

    :param max_depth: Maximum depth of async call stacks. Setting to ```0``` will effectively disable collecting async call stacks (default).
    '''
    ...

def set_blackbox_execution_contexts(unique_ids: typing.List[str]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Replace previous blackbox execution contexts with passed ones. Forces backend to skip
    stepping/pausing in scripts in these execution contexts. VM will try to leave blackboxed script by
    performing 'step in' several times, finally resorting to 'step out' if unsuccessful.

    **EXPERIMENTAL**

    :param unique_ids: Array of execution context unique ids for the debugger to ignore.
    '''
    ...

def set_blackbox_patterns(patterns: typing.List[str], skip_anonymous: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Replace previous blackbox patterns with passed ones. Forces backend to skip stepping/pausing in
    scripts with url matching one of the patterns. VM will try to leave blackboxed script by
    performing 'step in' several times, finally resorting to 'step out' if unsuccessful.

    **EXPERIMENTAL**

    :param patterns: Array of regexps that will be used to check script url for blackbox state.
    :param skip_anonymous: *(Optional)* If true, also ignore scripts with no source url.
    '''
    ...

def set_blackboxed_ranges(script_id: runtime.ScriptId, positions: typing.List[ScriptPosition]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Makes backend skip steps in the script in blackboxed ranges. VM will try leave blacklisted
    scripts by performing 'step in' several times, finally resorting to 'step out' if unsuccessful.
    Positions array contains positions where blackbox state is changed. First interval isn't
    blackboxed. Array should be sorted.

    **EXPERIMENTAL**

    :param script_id: Id of the script.
    :param positions:
    '''
    ...

def set_breakpoint(location: Location, condition: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[BreakpointId, Location]]:
    '''
    Sets JavaScript breakpoint at a given location.

    :param location: Location to set breakpoint in.
    :param condition: *(Optional)* Expression to use as a breakpoint condition. When specified, debugger will only stop on the breakpoint if this expression evaluates to true.
    :returns: A tuple with the following items:

        0. **breakpointId** - Id of the created breakpoint for further reference.
        1. **actualLocation** - Location this breakpoint resolved into.
    '''
    ...

def set_instrumentation_breakpoint(instrumentation: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, BreakpointId]:
    '''
    Sets instrumentation breakpoint.

    :param instrumentation: Instrumentation name.
    :returns: Id of the created breakpoint for further reference.
    '''
    ...

def set_breakpoint_by_url(line_number: int, url: typing.Optional[str] = ..., url_regex: typing.Optional[str] = ..., script_hash: typing.Optional[str] = ..., column_number: typing.Optional[int] = ..., condition: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[BreakpointId, typing.List[Location]]]:
    '''
    Sets JavaScript breakpoint at given location specified either by URL or URL regex. Once this
    command is issued, all existing parsed scripts will have breakpoints resolved and returned in
    ``locations`` property. Further matching script parsing will result in subsequent
    ``breakpointResolved`` events issued. This logical breakpoint will survive page reloads.

    :param line_number: Line number to set breakpoint at.
    :param url: *(Optional)* URL of the resources to set breakpoint on.
    :param url_regex: *(Optional)* Regex pattern for the URLs of the resources to set breakpoints on. Either ```url```` or ````urlRegex``` must be specified.
    :param script_hash: *(Optional)* Script hash of the resources to set breakpoint on.
    :param column_number: *(Optional)* Offset in the line to set breakpoint at.
    :param condition: *(Optional)* Expression to use as a breakpoint condition. When specified, debugger will only stop on the breakpoint if this expression evaluates to true.
    :returns: A tuple with the following items:

        0. **breakpointId** - Id of the created breakpoint for further reference.
        1. **locations** - List of the locations this breakpoint resolved into upon addition.
    '''
    ...

def set_breakpoint_on_function_call(object_id: runtime.RemoteObjectId, condition: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, BreakpointId]:
    '''
    Sets JavaScript breakpoint before each call to the given function.
    If another function was created from the same source as a given one,
    calling it will also trigger the breakpoint.

    **EXPERIMENTAL**

    :param object_id: Function object id.
    :param condition: *(Optional)* Expression to use as a breakpoint condition. When specified, debugger will stop on the breakpoint if this expression evaluates to true.
    :returns: Id of the created breakpoint for further reference.
    '''
    ...

def set_breakpoints_active(active: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Activates / deactivates all breakpoints on the page.

    :param active: New value for breakpoints active state.
    '''
    ...

def set_pause_on_exceptions(state: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Defines pause on exceptions state. Can be set to stop on all exceptions, uncaught exceptions,
    or caught exceptions, no exceptions. Initial pause on exceptions state is ``none``.

    :param state: Pause on exceptions mode.
    '''
    ...

def set_return_value(new_value: runtime.CallArgument) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Changes return value in top frame. Available only at return break position.

    **EXPERIMENTAL**

    :param new_value: New return value.
    '''
    ...

def set_script_source(script_id: runtime.ScriptId, script_source: str, dry_run: typing.Optional[bool] = ..., allow_top_frame_editing: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[typing.Optional[typing.List[CallFrame]], typing.Optional[bool], typing.Optional[runtime.StackTrace], typing.Optional[runtime.StackTraceId], str, typing.Optional[runtime.ExceptionDetails]]]:
    '''
    Edits JavaScript source live.

    In general, functions that are currently on the stack can not be edited with
    a single exception: If the edited function is the top-most stack frame and
    that is the only activation of that function on the stack. In this case
    the live edit will be successful and a ``Debugger.restartFrame`` for the
    top-most function is automatically triggered.

    :param script_id: Id of the script to edit.
    :param script_source: New content of the script.
    :param dry_run: *(Optional)* If true the change will not actually be applied. Dry run may be used to get result description without actually modifying the code.
    :param allow_top_frame_editing: **(EXPERIMENTAL)** *(Optional)* If true, then ```scriptSource```` is allowed to change the function on top of the stack as long as the top-most stack frame is the only activation of that function.
    :returns: A tuple with the following items:

        0. **callFrames** - *(Optional)* New stack trace in case editing has happened while VM was stopped.
        1. **stackChanged** - *(Optional)* Whether current call stack  was modified after applying the changes.
        2. **asyncStackTrace** - *(Optional)* Async stack trace, if any.
        3. **asyncStackTraceId** - *(Optional)* Async stack trace, if any.
        4. **status** - Whether the operation was successful or not. Only `` Ok`` denotes a successful live edit while the other enum variants denote why the live edit failed.
        5. **exceptionDetails** - *(Optional)* Exception details if any. Only present when `` status`` is `` CompileError`.
    '''
    ...

def set_skip_all_pauses(skip: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Makes page not interrupt on any pauses (breakpoint, exception, dom exception etc).

    :param skip: New value for skip pauses state.
    '''
    ...

def set_variable_value(scope_number: int, variable_name: str, new_value: runtime.CallArgument, call_frame_id: CallFrameId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Changes value of variable in a callframe. Object-based scopes are not supported and must be
    mutated manually.

    :param scope_number: 0-based number of scope as was listed in scope chain. Only 'local', 'closure' and 'catch' scope types are allowed. Other scopes could be manipulated manually.
    :param variable_name: Variable name.
    :param new_value: New variable value.
    :param call_frame_id: Id of callframe that holds variable.
    '''
    ...

def step_into(break_on_async_call: typing.Optional[bool] = ..., skip_list: typing.Optional[typing.List[LocationRange]] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Steps into the function call.

    :param break_on_async_call: **(EXPERIMENTAL)** *(Optional)* Debugger will pause on the execution of the first async task which was scheduled before next pause.
    :param skip_list: **(EXPERIMENTAL)** *(Optional)* The skipList specifies location ranges that should be skipped on step into.
    '''
    ...

def step_out() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Steps out of the function call.
    '''
    ...

def step_over(skip_list: typing.Optional[typing.List[LocationRange]] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Steps over the statement.

    :param skip_list: **(EXPERIMENTAL)** *(Optional)* The skipList specifies location ranges that should be skipped on step over.
    '''
    ...

@deprecated(version="1.3")
@event_class('Debugger.breakpointResolved')
@dataclass
class BreakpointResolved:
    '''
    Fired when breakpoint is resolved to an actual script and location.
    Deprecated in favor of ``resolvedBreakpoints`` in the ``scriptParsed`` event.
    '''
    breakpoint_id: BreakpointId
    location: Location
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BreakpointResolved:
        ...



@event_class('Debugger.paused')
@dataclass
class Paused:
    '''
    Fired when the virtual machine stopped on breakpoint or exception or any other stop criteria.
    '''
    call_frames: typing.List[CallFrame]
    reason: str
    data: typing.Optional[dict]
    hit_breakpoints: typing.Optional[typing.List[str]]
    async_stack_trace: typing.Optional[runtime.StackTrace]
    async_stack_trace_id: typing.Optional[runtime.StackTraceId]
    async_call_stack_trace_id: typing.Optional[runtime.StackTraceId]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Paused:
        ...



@event_class('Debugger.resumed')
@dataclass
class Resumed:
    '''
    Fired when the virtual machine resumed execution.
    '''
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Resumed:
        ...



@event_class('Debugger.scriptFailedToParse')
@dataclass
class ScriptFailedToParse:
    '''
    Fired when virtual machine fails to parse the script.
    '''
    script_id: runtime.ScriptId
    url: str
    start_line: int
    start_column: int
    end_line: int
    end_column: int
    execution_context_id: runtime.ExecutionContextId
    hash_: str
    build_id: str
    execution_context_aux_data: typing.Optional[dict]
    source_map_url: typing.Optional[str]
    has_source_url: typing.Optional[bool]
    is_module: typing.Optional[bool]
    length: typing.Optional[int]
    stack_trace: typing.Optional[runtime.StackTrace]
    code_offset: typing.Optional[int]
    script_language: typing.Optional[ScriptLanguage]
    embedder_name: typing.Optional[str]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScriptFailedToParse:
        ...



@event_class('Debugger.scriptParsed')
@dataclass
class ScriptParsed:
    '''
    Fired when virtual machine parses script. This event is also fired for all known and uncollected
    scripts upon enabling debugger.
    '''
    script_id: runtime.ScriptId
    url: str
    start_line: int
    start_column: int
    end_line: int
    end_column: int
    execution_context_id: runtime.ExecutionContextId
    hash_: str
    build_id: str
    execution_context_aux_data: typing.Optional[dict]
    is_live_edit: typing.Optional[bool]
    source_map_url: typing.Optional[str]
    has_source_url: typing.Optional[bool]
    is_module: typing.Optional[bool]
    length: typing.Optional[int]
    stack_trace: typing.Optional[runtime.StackTrace]
    code_offset: typing.Optional[int]
    script_language: typing.Optional[ScriptLanguage]
    debug_symbols: typing.Optional[typing.List[DebugSymbols]]
    embedder_name: typing.Optional[str]
    resolved_breakpoints: typing.Optional[typing.List[ResolvedBreakpoint]]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScriptParsed:
        ...
