"""
This type stub file was generated by pyright.
"""

import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class

class RequestId(str):
    '''
    Device request id.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> RequestId:
        ...

    def __repr__(self) -> str:
        ...



class DeviceId(str):
    '''
    A device id.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> DeviceId:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class PromptDevice:
    '''
    Device information displayed in a user prompt to select a device.
    '''
    id_: DeviceId
    name: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PromptDevice:
        ...



def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enable events in this domain.
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disable events in this domain.
    '''
    ...

def select_prompt(id_: RequestId, device_id: DeviceId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Select a device in response to a DeviceAccess.deviceRequestPrompted event.

    :param id_:
    :param device_id:
    '''
    ...

def cancel_prompt(id_: RequestId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Cancel a prompt in response to a DeviceAccess.deviceRequestPrompted event.

    :param id_:
    '''
    ...

@event_class('DeviceAccess.deviceRequestPrompted')
@dataclass
class DeviceRequestPrompted:
    '''
    A device request opened a user prompt to select a device. Respond with the
    selectPrompt or cancelPrompt command.
    '''
    id_: RequestId
    devices: typing.List[PromptDevice]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DeviceRequestPrompted:
        ...
