"""
This type stub file was generated by pyright.
"""

import typing
from dataclasses import dataclass
from .util import T_JSON_DICT
from . import dom, dom_debugger, page
from deprecated.sphinx import deprecated

@dataclass
class DOMNode:
    '''
    A Node in the DOM tree.
    '''
    node_type: int
    node_name: str
    node_value: str
    backend_node_id: dom.BackendNodeId
    text_value: typing.Optional[str] = ...
    input_value: typing.Optional[str] = ...
    input_checked: typing.Optional[bool] = ...
    option_selected: typing.Optional[bool] = ...
    child_node_indexes: typing.Optional[typing.List[int]] = ...
    attributes: typing.Optional[typing.List[NameValue]] = ...
    pseudo_element_indexes: typing.Optional[typing.List[int]] = ...
    layout_node_index: typing.Optional[int] = ...
    document_url: typing.Optional[str] = ...
    base_url: typing.Optional[str] = ...
    content_language: typing.Optional[str] = ...
    document_encoding: typing.Optional[str] = ...
    public_id: typing.Optional[str] = ...
    system_id: typing.Optional[str] = ...
    frame_id: typing.Optional[page.FrameId] = ...
    content_document_index: typing.Optional[int] = ...
    pseudo_type: typing.Optional[dom.PseudoType] = ...
    shadow_root_type: typing.Optional[dom.ShadowRootType] = ...
    is_clickable: typing.Optional[bool] = ...
    event_listeners: typing.Optional[typing.List[dom_debugger.EventListener]] = ...
    current_source_url: typing.Optional[str] = ...
    origin_url: typing.Optional[str] = ...
    scroll_offset_x: typing.Optional[float] = ...
    scroll_offset_y: typing.Optional[float] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DOMNode:
        ...



@dataclass
class InlineTextBox:
    '''
    Details of post layout rendered text positions. The exact layout should not be regarded as
    stable and may change between versions.
    '''
    bounding_box: dom.Rect
    start_character_index: int
    num_characters: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> InlineTextBox:
        ...



@dataclass
class LayoutTreeNode:
    '''
    Details of an element in the DOM tree with a LayoutObject.
    '''
    dom_node_index: int
    bounding_box: dom.Rect
    layout_text: typing.Optional[str] = ...
    inline_text_nodes: typing.Optional[typing.List[InlineTextBox]] = ...
    style_index: typing.Optional[int] = ...
    paint_order: typing.Optional[int] = ...
    is_stacking_context: typing.Optional[bool] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LayoutTreeNode:
        ...



@dataclass
class ComputedStyle:
    '''
    A subset of the full ComputedStyle as defined by the request whitelist.
    '''
    properties: typing.List[NameValue]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ComputedStyle:
        ...



@dataclass
class NameValue:
    '''
    A name/value pair.
    '''
    name: str
    value: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> NameValue:
        ...



class StringIndex(int):
    '''
    Index of the string in the strings table.
    '''
    def to_json(self) -> int:
        ...

    @classmethod
    def from_json(cls, json: int) -> StringIndex:
        ...

    def __repr__(self) -> str:
        ...



class ArrayOfStrings(list):
    '''
    Index of the string in the strings table.
    '''
    def to_json(self) -> typing.List[StringIndex]:
        ...

    @classmethod
    def from_json(cls, json: typing.List[StringIndex]) -> ArrayOfStrings:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class RareStringData:
    '''
    Data that is only present on rare nodes.
    '''
    index: typing.List[int]
    value: typing.List[StringIndex]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RareStringData:
        ...



@dataclass
class RareBooleanData:
    index: typing.List[int]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RareBooleanData:
        ...



@dataclass
class RareIntegerData:
    index: typing.List[int]
    value: typing.List[int]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RareIntegerData:
        ...



class Rectangle(list):
    def to_json(self) -> typing.List[float]:
        ...

    @classmethod
    def from_json(cls, json: typing.List[float]) -> Rectangle:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class DocumentSnapshot:
    '''
    Document snapshot.
    '''
    document_url: StringIndex
    title: StringIndex
    base_url: StringIndex
    content_language: StringIndex
    encoding_name: StringIndex
    public_id: StringIndex
    system_id: StringIndex
    frame_id: StringIndex
    nodes: NodeTreeSnapshot
    layout: LayoutTreeSnapshot
    text_boxes: TextBoxSnapshot
    scroll_offset_x: typing.Optional[float] = ...
    scroll_offset_y: typing.Optional[float] = ...
    content_width: typing.Optional[float] = ...
    content_height: typing.Optional[float] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DocumentSnapshot:
        ...



@dataclass
class NodeTreeSnapshot:
    '''
    Table containing nodes.
    '''
    parent_index: typing.Optional[typing.List[int]] = ...
    node_type: typing.Optional[typing.List[int]] = ...
    shadow_root_type: typing.Optional[RareStringData] = ...
    node_name: typing.Optional[typing.List[StringIndex]] = ...
    node_value: typing.Optional[typing.List[StringIndex]] = ...
    backend_node_id: typing.Optional[typing.List[dom.BackendNodeId]] = ...
    attributes: typing.Optional[typing.List[ArrayOfStrings]] = ...
    text_value: typing.Optional[RareStringData] = ...
    input_value: typing.Optional[RareStringData] = ...
    input_checked: typing.Optional[RareBooleanData] = ...
    option_selected: typing.Optional[RareBooleanData] = ...
    content_document_index: typing.Optional[RareIntegerData] = ...
    pseudo_type: typing.Optional[RareStringData] = ...
    pseudo_identifier: typing.Optional[RareStringData] = ...
    is_clickable: typing.Optional[RareBooleanData] = ...
    current_source_url: typing.Optional[RareStringData] = ...
    origin_url: typing.Optional[RareStringData] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> NodeTreeSnapshot:
        ...



@dataclass
class LayoutTreeSnapshot:
    '''
    Table of details of an element in the DOM tree with a LayoutObject.
    '''
    node_index: typing.List[int]
    styles: typing.List[ArrayOfStrings]
    bounds: typing.List[Rectangle]
    text: typing.List[StringIndex]
    stacking_contexts: RareBooleanData
    paint_orders: typing.Optional[typing.List[int]] = ...
    offset_rects: typing.Optional[typing.List[Rectangle]] = ...
    scroll_rects: typing.Optional[typing.List[Rectangle]] = ...
    client_rects: typing.Optional[typing.List[Rectangle]] = ...
    blended_background_colors: typing.Optional[typing.List[StringIndex]] = ...
    text_color_opacities: typing.Optional[typing.List[float]] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LayoutTreeSnapshot:
        ...



@dataclass
class TextBoxSnapshot:
    '''
    Table of details of the post layout rendered text positions. The exact layout should not be regarded as
    stable and may change between versions.
    '''
    layout_index: typing.List[int]
    bounds: typing.List[Rectangle]
    start: typing.List[int]
    length: typing.List[int]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TextBoxSnapshot:
        ...



def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disables DOM snapshot agent for the given page.
    '''
    ...

def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables DOM snapshot agent for the given page.
    '''
    ...

@deprecated(version="1.3")
def get_snapshot(computed_style_whitelist: typing.List[str], include_event_listeners: typing.Optional[bool] = ..., include_paint_order: typing.Optional[bool] = ..., include_user_agent_shadow_tree: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[typing.List[DOMNode], typing.List[LayoutTreeNode], typing.List[ComputedStyle]]]:
    '''
    Returns a document snapshot, including the full DOM tree of the root node (including iframes,
    template contents, and imported documents) in a flattened array, as well as layout and
    white-listed computed style information for the nodes. Shadow DOM in the returned DOM tree is
    flattened.

    .. deprecated:: 1.3

    :param computed_style_whitelist: Whitelist of computed styles to return.
    :param include_event_listeners: *(Optional)* Whether or not to retrieve details of DOM listeners (default false).
    :param include_paint_order: *(Optional)* Whether to determine and include the paint order index of LayoutTreeNodes (default false).
    :param include_user_agent_shadow_tree: *(Optional)* Whether to include UA shadow tree in the snapshot (default false).
    :returns: A tuple with the following items:

        0. **domNodes** - The nodes in the DOM tree. The DOMNode at index 0 corresponds to the root document.
        1. **layoutTreeNodes** - The nodes in the layout tree.
        2. **computedStyles** - Whitelisted ComputedStyle properties for each node in the layout tree.
    '''
    ...

def capture_snapshot(computed_styles: typing.List[str], include_paint_order: typing.Optional[bool] = ..., include_dom_rects: typing.Optional[bool] = ..., include_blended_background_colors: typing.Optional[bool] = ..., include_text_color_opacities: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[typing.List[DocumentSnapshot], typing.List[str]]]:
    '''
    Returns a document snapshot, including the full DOM tree of the root node (including iframes,
    template contents, and imported documents) in a flattened array, as well as layout and
    white-listed computed style information for the nodes. Shadow DOM in the returned DOM tree is
    flattened.

    :param computed_styles: Whitelist of computed styles to return.
    :param include_paint_order: *(Optional)* Whether to include layout object paint orders into the snapshot.
    :param include_dom_rects: *(Optional)* Whether to include DOM rectangles (offsetRects, clientRects, scrollRects) into the snapshot
    :param include_blended_background_colors: **(EXPERIMENTAL)** *(Optional)* Whether to include blended background colors in the snapshot (default: false). Blended background color is achieved by blending background colors of all elements that overlap with the current element.
    :param include_text_color_opacities: **(EXPERIMENTAL)** *(Optional)* Whether to include text color opacity in the snapshot (default: false). An element might have the opacity property set that affects the text color of the element. The final text color opacity is computed based on the opacity of all overlapping elements.
    :returns: A tuple with the following items:

        0. **documents** - The nodes in the DOM tree. The DOMNode at index 0 corresponds to the root document.
        1. **strings** - Shared string table that all string properties refer to with indexes.
    '''
    ...
