"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT

class StorageArea(enum.Enum):
    '''
    Storage areas.
    '''
    SESSION = ...
    LOCAL = ...
    SYNC = ...
    MANAGED = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> StorageArea:
        ...



@dataclass
class ExtensionInfo:
    '''
    Detailed information about an extension.
    '''
    id_: str
    name: str
    version: str
    path: str
    enabled: bool
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ExtensionInfo:
        ...



def trigger_action(id_: str, target_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Runs an extension default action.

    :param id_: Extension id.
    :param target_id: A tab target ID to trigger the default extension action on.
    '''
    ...

def load_unpacked(path: str, enable_in_incognito: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
    '''
    Installs an unpacked extension from the filesystem similar to
    --load-extension CLI flags. Returns extension ID once the extension
    has been installed.

    :param path: Absolute file path.
    :param enable_in_incognito: *(Optional)* Enable the extension in incognito
    :returns: Extension id.
    '''
    ...

def get_extensions() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[ExtensionInfo]]:
    '''
    Gets a list of all unpacked extensions.

    :returns:
    '''
    ...

def uninstall(id_: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Uninstalls an unpacked extension (others not supported) from the profile.

    :param id_: Extension id.
    '''
    ...

def get_storage_items(id_: str, storage_area: StorageArea, keys: typing.Optional[typing.List[str]] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, dict]:
    '''
    Gets data from extension storage in the given ``storageArea``. If ``keys`` is
    specified, these are used to filter the result.

    :param id_: ID of extension.
    :param storage_area: StorageArea to retrieve data from.
    :param keys: *(Optional)* Keys to retrieve.
    :returns:
    '''
    ...

def remove_storage_items(id_: str, storage_area: StorageArea, keys: typing.List[str]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Removes ``keys`` from extension storage in the given ``storageArea``.

    :param id_: ID of extension.
    :param storage_area: StorageArea to remove data from.
    :param keys: Keys to remove.
    '''
    ...

def clear_storage_items(id_: str, storage_area: StorageArea) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Clears extension storage in the given ``storageArea``.

    :param id_: ID of extension.
    :param storage_area: StorageArea to remove data from.
    '''
    ...

def set_storage_items(id_: str, storage_area: StorageArea, values: dict) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets ``values`` in extension storage in the given ``storageArea``. The provided ``values``
    will be merged with existing values in the storage area.

    :param id_: ID of extension.
    :param storage_area: StorageArea to set data in.
    :param values: Values to set.
    '''
    ...
