"""
This type stub file was generated by pyright.
"""

import typing
from dataclasses import dataclass
from .util import T_JSON_DICT
from . import runtime, storage

@dataclass
class DatabaseWithObjectStores:
    '''
    Database with an array of object stores.
    '''
    name: str
    version: float
    object_stores: typing.List[ObjectStore]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DatabaseWithObjectStores:
        ...



@dataclass
class ObjectStore:
    '''
    Object store.
    '''
    name: str
    key_path: KeyPath
    auto_increment: bool
    indexes: typing.List[ObjectStoreIndex]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ObjectStore:
        ...



@dataclass
class ObjectStoreIndex:
    '''
    Object store index.
    '''
    name: str
    key_path: KeyPath
    unique: bool
    multi_entry: bool
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ObjectStoreIndex:
        ...



@dataclass
class Key:
    '''
    Key.
    '''
    type_: str
    number: typing.Optional[float] = ...
    string: typing.Optional[str] = ...
    date: typing.Optional[float] = ...
    array: typing.Optional[typing.List[Key]] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Key:
        ...



@dataclass
class KeyRange:
    '''
    Key range.
    '''
    lower_open: bool
    upper_open: bool
    lower: typing.Optional[Key] = ...
    upper: typing.Optional[Key] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> KeyRange:
        ...



@dataclass
class DataEntry:
    '''
    Data entry.
    '''
    key: runtime.RemoteObject
    primary_key: runtime.RemoteObject
    value: runtime.RemoteObject
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DataEntry:
        ...



@dataclass
class KeyPath:
    '''
    Key path.
    '''
    type_: str
    string: typing.Optional[str] = ...
    array: typing.Optional[typing.List[str]] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> KeyPath:
        ...



def clear_object_store(database_name: str, object_store_name: str, security_origin: typing.Optional[str] = ..., storage_key: typing.Optional[str] = ..., storage_bucket: typing.Optional[storage.StorageBucket] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Clears all entries from an object store.

    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    :param database_name: Database name.
    :param object_store_name: Object store name.
    '''
    ...

def delete_database(database_name: str, security_origin: typing.Optional[str] = ..., storage_key: typing.Optional[str] = ..., storage_bucket: typing.Optional[storage.StorageBucket] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Deletes a database.

    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    :param database_name: Database name.
    '''
    ...

def delete_object_store_entries(database_name: str, object_store_name: str, key_range: KeyRange, security_origin: typing.Optional[str] = ..., storage_key: typing.Optional[str] = ..., storage_bucket: typing.Optional[storage.StorageBucket] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Delete a range of entries from an object store

    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    :param database_name:
    :param object_store_name:
    :param key_range: Range of entry keys to delete
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disables events from backend.
    '''
    ...

def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables events from backend.
    '''
    ...

def request_data(database_name: str, object_store_name: str, skip_count: int, page_size: int, security_origin: typing.Optional[str] = ..., storage_key: typing.Optional[str] = ..., storage_bucket: typing.Optional[storage.StorageBucket] = ..., index_name: typing.Optional[str] = ..., key_range: typing.Optional[KeyRange] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[typing.List[DataEntry], bool]]:
    '''
    Requests data from object store or index.

    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    :param database_name: Database name.
    :param object_store_name: Object store name.
    :param index_name: *(Optional)* Index name. If not specified, it performs an object store data request.
    :param skip_count: Number of records to skip.
    :param page_size: Number of records to fetch.
    :param key_range: *(Optional)* Key range.
    :returns: A tuple with the following items:

        0. **objectStoreDataEntries** - Array of object store data entries.
        1. **hasMore** - If true, there are more entries to fetch in the given range.
    '''
    ...

def get_metadata(database_name: str, object_store_name: str, security_origin: typing.Optional[str] = ..., storage_key: typing.Optional[str] = ..., storage_bucket: typing.Optional[storage.StorageBucket] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[float, float]]:
    '''
    Gets metadata of an object store.

    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    :param database_name: Database name.
    :param object_store_name: Object store name.
    :returns: A tuple with the following items:

        0. **entriesCount** - the entries count
        1. **keyGeneratorValue** - the current value of key generator, to become the next inserted key into the object store. Valid if objectStore.autoIncrement is true.
    '''
    ...

def request_database(database_name: str, security_origin: typing.Optional[str] = ..., storage_key: typing.Optional[str] = ..., storage_bucket: typing.Optional[storage.StorageBucket] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, DatabaseWithObjectStores]:
    '''
    Requests database with given name in given frame.

    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    :param database_name: Database name.
    :returns: Database with an array of object stores.
    '''
    ...

def request_database_names(security_origin: typing.Optional[str] = ..., storage_key: typing.Optional[str] = ..., storage_bucket: typing.Optional[storage.StorageBucket] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[str]]:
    '''
    Requests database names for given security origin.

    :param security_origin: *(Optional)* At least and at most one of securityOrigin, storageKey, or storageBucket must be specified. Security origin.
    :param storage_key: *(Optional)* Storage key.
    :param storage_bucket: *(Optional)* Storage bucket. If not specified, it uses the default bucket.
    :returns: Database names for origin.
    '''
    ...
