"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT

class PressureLevel(enum.Enum):
    '''
    Memory pressure level.
    '''
    MODERATE = ...
    CRITICAL = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> PressureLevel:
        ...



@dataclass
class SamplingProfileNode:
    '''
    Heap profile sample.
    '''
    size: float
    total: float
    stack: typing.List[str]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SamplingProfileNode:
        ...



@dataclass
class SamplingProfile:
    '''
    Array of heap profile samples.
    '''
    samples: typing.List[SamplingProfileNode]
    modules: typing.List[Module]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SamplingProfile:
        ...



@dataclass
class Module:
    '''
    Executable module information
    '''
    name: str
    uuid: str
    base_address: str
    size: float
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Module:
        ...



@dataclass
class DOMCounter:
    '''
    DOM object counter data.
    '''
    name: str
    count: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DOMCounter:
        ...



def get_dom_counters() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[int, int, int]]:
    '''
    Retruns current DOM object counters.

    :returns: A tuple with the following items:

        0. **documents** -
        1. **nodes** -
        2. **jsEventListeners** -
    '''
    ...

def get_dom_counters_for_leak_detection() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[DOMCounter]]:
    '''
    Retruns DOM object counters after preparing renderer for leak detection.

    :returns: DOM object counters.
    '''
    ...

def prepare_for_leak_detection() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Prepares for leak detection by terminating workers, stopping spellcheckers,
    dropping non-essential internal caches, running garbage collections, etc.
    '''
    ...

def forcibly_purge_java_script_memory() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Simulate OomIntervention by purging V8 memory.
    '''
    ...

def set_pressure_notifications_suppressed(suppressed: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enable/disable suppressing memory pressure notifications in all processes.

    :param suppressed: If true, memory pressure notifications will be suppressed.
    '''
    ...

def simulate_pressure_notification(level: PressureLevel) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Simulate a memory pressure notification in all processes.

    :param level: Memory pressure level of the notification.
    '''
    ...

def start_sampling(sampling_interval: typing.Optional[int] = ..., suppress_randomness: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Start collecting native memory profile.

    :param sampling_interval: *(Optional)* Average number of bytes between samples.
    :param suppress_randomness: *(Optional)* Do not randomize intervals between samples.
    '''
    ...

def stop_sampling() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Stop collecting native memory profile.
    '''
    ...

def get_all_time_sampling_profile() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SamplingProfile]:
    '''
    Retrieve native memory allocations profile
    collected since renderer process startup.

    :returns:
    '''
    ...

def get_browser_sampling_profile() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SamplingProfile]:
    '''
    Retrieve native memory allocations profile
    collected since browser process startup.

    :returns:
    '''
    ...

def get_sampling_profile() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SamplingProfile]:
    '''
    Retrieve native memory allocations profile collected since last
    ``startSampling`` call.

    :returns:
    '''
    ...
