"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
from . import debugger, emulation, io, page, runtime, security
from deprecated.sphinx import deprecated

class ResourceType(enum.Enum):
    '''
    Resource type as it was perceived by the rendering engine.
    '''
    DOCUMENT = ...
    STYLESHEET = ...
    IMAGE = ...
    MEDIA = ...
    FONT = ...
    SCRIPT = ...
    TEXT_TRACK = ...
    XHR = ...
    FETCH = ...
    PREFETCH = ...
    EVENT_SOURCE = ...
    WEB_SOCKET = ...
    MANIFEST = ...
    SIGNED_EXCHANGE = ...
    PING = ...
    CSP_VIOLATION_REPORT = ...
    PREFLIGHT = ...
    FED_CM = ...
    OTHER = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ResourceType:
        ...



class LoaderId(str):
    '''
    Unique loader identifier.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> LoaderId:
        ...

    def __repr__(self) -> str:
        ...



class RequestId(str):
    '''
    Unique network request identifier.
    Note that this does not identify individual HTTP requests that are part of
    a network request.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> RequestId:
        ...

    def __repr__(self) -> str:
        ...



class InterceptionId(str):
    '''
    Unique intercepted request identifier.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> InterceptionId:
        ...

    def __repr__(self) -> str:
        ...



class ErrorReason(enum.Enum):
    '''
    Network level fetch failure reason.
    '''
    FAILED = ...
    ABORTED = ...
    TIMED_OUT = ...
    ACCESS_DENIED = ...
    CONNECTION_CLOSED = ...
    CONNECTION_RESET = ...
    CONNECTION_REFUSED = ...
    CONNECTION_ABORTED = ...
    CONNECTION_FAILED = ...
    NAME_NOT_RESOLVED = ...
    INTERNET_DISCONNECTED = ...
    ADDRESS_UNREACHABLE = ...
    BLOCKED_BY_CLIENT = ...
    BLOCKED_BY_RESPONSE = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ErrorReason:
        ...



class TimeSinceEpoch(float):
    '''
    UTC time in seconds, counted from January 1, 1970.
    '''
    def to_json(self) -> float:
        ...

    @classmethod
    def from_json(cls, json: float) -> TimeSinceEpoch:
        ...

    def __repr__(self) -> str:
        ...



class MonotonicTime(float):
    '''
    Monotonically increasing time in seconds since an arbitrary point in the past.
    '''
    def to_json(self) -> float:
        ...

    @classmethod
    def from_json(cls, json: float) -> MonotonicTime:
        ...

    def __repr__(self) -> str:
        ...



class Headers(dict):
    '''
    Request / response headers as keys / values of JSON object.
    '''
    def to_json(self) -> dict:
        ...

    @classmethod
    def from_json(cls, json: dict) -> Headers:
        ...

    def __repr__(self) -> str:
        ...



class ConnectionType(enum.Enum):
    '''
    The underlying connection technology that the browser is supposedly using.
    '''
    NONE = ...
    CELLULAR2G = ...
    CELLULAR3G = ...
    CELLULAR4G = ...
    BLUETOOTH = ...
    ETHERNET = ...
    WIFI = ...
    WIMAX = ...
    OTHER = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ConnectionType:
        ...



class CookieSameSite(enum.Enum):
    '''
    Represents the cookie's 'SameSite' status:
    https://tools.ietf.org/html/draft-west-first-party-cookies
    '''
    STRICT = ...
    LAX = ...
    NONE = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CookieSameSite:
        ...



class CookiePriority(enum.Enum):
    '''
    Represents the cookie's 'Priority' status:
    https://tools.ietf.org/html/draft-west-cookie-priority-00
    '''
    LOW = ...
    MEDIUM = ...
    HIGH = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CookiePriority:
        ...



class CookieSourceScheme(enum.Enum):
    '''
    Represents the source scheme of the origin that originally set the cookie.
    A value of "Unset" allows protocol clients to emulate legacy cookie scope for the scheme.
    This is a temporary ability and it will be removed in the future.
    '''
    UNSET = ...
    NON_SECURE = ...
    SECURE = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CookieSourceScheme:
        ...



@dataclass
class ResourceTiming:
    '''
    Timing information for the request.
    '''
    request_time: float
    proxy_start: float
    proxy_end: float
    dns_start: float
    dns_end: float
    connect_start: float
    connect_end: float
    ssl_start: float
    ssl_end: float
    worker_start: float
    worker_ready: float
    worker_fetch_start: float
    worker_respond_with_settled: float
    send_start: float
    send_end: float
    push_start: float
    push_end: float
    receive_headers_start: float
    receive_headers_end: float
    worker_router_evaluation_start: typing.Optional[float] = ...
    worker_cache_lookup_start: typing.Optional[float] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ResourceTiming:
        ...



class ResourcePriority(enum.Enum):
    '''
    Loading priority of a resource request.
    '''
    VERY_LOW = ...
    LOW = ...
    MEDIUM = ...
    HIGH = ...
    VERY_HIGH = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ResourcePriority:
        ...



class RenderBlockingBehavior(enum.Enum):
    '''
    The render-blocking behavior of a resource request.
    '''
    BLOCKING = ...
    IN_BODY_PARSER_BLOCKING = ...
    NON_BLOCKING = ...
    NON_BLOCKING_DYNAMIC = ...
    POTENTIALLY_BLOCKING = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> RenderBlockingBehavior:
        ...



@dataclass
class PostDataEntry:
    '''
    Post data entry for HTTP request
    '''
    bytes_: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PostDataEntry:
        ...



@dataclass
class Request:
    '''
    HTTP request data.
    '''
    url: str
    method: str
    headers: Headers
    initial_priority: ResourcePriority
    referrer_policy: str
    url_fragment: typing.Optional[str] = ...
    post_data: typing.Optional[str] = ...
    has_post_data: typing.Optional[bool] = ...
    post_data_entries: typing.Optional[typing.List[PostDataEntry]] = ...
    mixed_content_type: typing.Optional[security.MixedContentType] = ...
    is_link_preload: typing.Optional[bool] = ...
    trust_token_params: typing.Optional[TrustTokenParams] = ...
    is_same_site: typing.Optional[bool] = ...
    is_ad_related: typing.Optional[bool] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Request:
        ...



@dataclass
class SignedCertificateTimestamp:
    '''
    Details of a signed certificate timestamp (SCT).
    '''
    status: str
    origin: str
    log_description: str
    log_id: str
    timestamp: float
    hash_algorithm: str
    signature_algorithm: str
    signature_data: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SignedCertificateTimestamp:
        ...



@dataclass
class SecurityDetails:
    '''
    Security details about a request.
    '''
    protocol: str
    key_exchange: str
    cipher: str
    certificate_id: security.CertificateId
    subject_name: str
    san_list: typing.List[str]
    issuer: str
    valid_from: TimeSinceEpoch
    valid_to: TimeSinceEpoch
    signed_certificate_timestamp_list: typing.List[SignedCertificateTimestamp]
    certificate_transparency_compliance: CertificateTransparencyCompliance
    encrypted_client_hello: bool
    key_exchange_group: typing.Optional[str] = ...
    mac: typing.Optional[str] = ...
    server_signature_algorithm: typing.Optional[int] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SecurityDetails:
        ...



class CertificateTransparencyCompliance(enum.Enum):
    '''
    Whether the request complied with Certificate Transparency policy.
    '''
    UNKNOWN = ...
    NOT_COMPLIANT = ...
    COMPLIANT = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CertificateTransparencyCompliance:
        ...



class BlockedReason(enum.Enum):
    '''
    The reason why request was blocked.
    '''
    OTHER = ...
    CSP = ...
    MIXED_CONTENT = ...
    ORIGIN = ...
    INSPECTOR = ...
    INTEGRITY = ...
    SUBRESOURCE_FILTER = ...
    CONTENT_TYPE = ...
    COEP_FRAME_RESOURCE_NEEDS_COEP_HEADER = ...
    COOP_SANDBOXED_IFRAME_CANNOT_NAVIGATE_TO_COOP_PAGE = ...
    CORP_NOT_SAME_ORIGIN = ...
    CORP_NOT_SAME_ORIGIN_AFTER_DEFAULTED_TO_SAME_ORIGIN_BY_COEP = ...
    CORP_NOT_SAME_ORIGIN_AFTER_DEFAULTED_TO_SAME_ORIGIN_BY_DIP = ...
    CORP_NOT_SAME_ORIGIN_AFTER_DEFAULTED_TO_SAME_ORIGIN_BY_COEP_AND_DIP = ...
    CORP_NOT_SAME_SITE = ...
    SRI_MESSAGE_SIGNATURE_MISMATCH = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> BlockedReason:
        ...



class CorsError(enum.Enum):
    '''
    The reason why request was blocked.
    '''
    DISALLOWED_BY_MODE = ...
    INVALID_RESPONSE = ...
    WILDCARD_ORIGIN_NOT_ALLOWED = ...
    MISSING_ALLOW_ORIGIN_HEADER = ...
    MULTIPLE_ALLOW_ORIGIN_VALUES = ...
    INVALID_ALLOW_ORIGIN_VALUE = ...
    ALLOW_ORIGIN_MISMATCH = ...
    INVALID_ALLOW_CREDENTIALS = ...
    CORS_DISABLED_SCHEME = ...
    PREFLIGHT_INVALID_STATUS = ...
    PREFLIGHT_DISALLOWED_REDIRECT = ...
    PREFLIGHT_WILDCARD_ORIGIN_NOT_ALLOWED = ...
    PREFLIGHT_MISSING_ALLOW_ORIGIN_HEADER = ...
    PREFLIGHT_MULTIPLE_ALLOW_ORIGIN_VALUES = ...
    PREFLIGHT_INVALID_ALLOW_ORIGIN_VALUE = ...
    PREFLIGHT_ALLOW_ORIGIN_MISMATCH = ...
    PREFLIGHT_INVALID_ALLOW_CREDENTIALS = ...
    PREFLIGHT_MISSING_ALLOW_EXTERNAL = ...
    PREFLIGHT_INVALID_ALLOW_EXTERNAL = ...
    INVALID_ALLOW_METHODS_PREFLIGHT_RESPONSE = ...
    INVALID_ALLOW_HEADERS_PREFLIGHT_RESPONSE = ...
    METHOD_DISALLOWED_BY_PREFLIGHT_RESPONSE = ...
    HEADER_DISALLOWED_BY_PREFLIGHT_RESPONSE = ...
    REDIRECT_CONTAINS_CREDENTIALS = ...
    INSECURE_LOCAL_NETWORK = ...
    INVALID_LOCAL_NETWORK_ACCESS = ...
    NO_CORS_REDIRECT_MODE_NOT_FOLLOW = ...
    LOCAL_NETWORK_ACCESS_PERMISSION_DENIED = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CorsError:
        ...



@dataclass
class CorsErrorStatus:
    cors_error: CorsError
    failed_parameter: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CorsErrorStatus:
        ...



class ServiceWorkerResponseSource(enum.Enum):
    '''
    Source of serviceworker response.
    '''
    CACHE_STORAGE = ...
    HTTP_CACHE = ...
    FALLBACK_CODE = ...
    NETWORK = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ServiceWorkerResponseSource:
        ...



@dataclass
class TrustTokenParams:
    '''
    Determines what type of Trust Token operation is executed and
    depending on the type, some additional parameters. The values
    are specified in third_party/blink/renderer/core/fetch/trust_token.idl.
    '''
    operation: TrustTokenOperationType
    refresh_policy: str
    issuers: typing.Optional[typing.List[str]] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TrustTokenParams:
        ...



class TrustTokenOperationType(enum.Enum):
    ISSUANCE = ...
    REDEMPTION = ...
    SIGNING = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> TrustTokenOperationType:
        ...



class AlternateProtocolUsage(enum.Enum):
    '''
    The reason why Chrome uses a specific transport protocol for HTTP semantics.
    '''
    ALTERNATIVE_JOB_WON_WITHOUT_RACE = ...
    ALTERNATIVE_JOB_WON_RACE = ...
    MAIN_JOB_WON_RACE = ...
    MAPPING_MISSING = ...
    BROKEN = ...
    DNS_ALPN_H3_JOB_WON_WITHOUT_RACE = ...
    DNS_ALPN_H3_JOB_WON_RACE = ...
    UNSPECIFIED_REASON = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> AlternateProtocolUsage:
        ...



class ServiceWorkerRouterSource(enum.Enum):
    '''
    Source of service worker router.
    '''
    NETWORK = ...
    CACHE = ...
    FETCH_EVENT = ...
    RACE_NETWORK_AND_FETCH_HANDLER = ...
    RACE_NETWORK_AND_CACHE = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ServiceWorkerRouterSource:
        ...



@dataclass
class ServiceWorkerRouterInfo:
    rule_id_matched: typing.Optional[int] = ...
    matched_source_type: typing.Optional[ServiceWorkerRouterSource] = ...
    actual_source_type: typing.Optional[ServiceWorkerRouterSource] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ServiceWorkerRouterInfo:
        ...



@dataclass
class Response:
    '''
    HTTP response data.
    '''
    url: str
    status: int
    status_text: str
    headers: Headers
    mime_type: str
    charset: str
    connection_reused: bool
    connection_id: float
    encoded_data_length: float
    security_state: security.SecurityState
    headers_text: typing.Optional[str] = ...
    request_headers: typing.Optional[Headers] = ...
    request_headers_text: typing.Optional[str] = ...
    remote_ip_address: typing.Optional[str] = ...
    remote_port: typing.Optional[int] = ...
    from_disk_cache: typing.Optional[bool] = ...
    from_service_worker: typing.Optional[bool] = ...
    from_prefetch_cache: typing.Optional[bool] = ...
    from_early_hints: typing.Optional[bool] = ...
    service_worker_router_info: typing.Optional[ServiceWorkerRouterInfo] = ...
    timing: typing.Optional[ResourceTiming] = ...
    service_worker_response_source: typing.Optional[ServiceWorkerResponseSource] = ...
    response_time: typing.Optional[TimeSinceEpoch] = ...
    cache_storage_cache_name: typing.Optional[str] = ...
    protocol: typing.Optional[str] = ...
    alternate_protocol_usage: typing.Optional[AlternateProtocolUsage] = ...
    security_details: typing.Optional[SecurityDetails] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Response:
        ...



@dataclass
class WebSocketRequest:
    '''
    WebSocket request data.
    '''
    headers: Headers
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebSocketRequest:
        ...



@dataclass
class WebSocketResponse:
    '''
    WebSocket response data.
    '''
    status: int
    status_text: str
    headers: Headers
    headers_text: typing.Optional[str] = ...
    request_headers: typing.Optional[Headers] = ...
    request_headers_text: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebSocketResponse:
        ...



@dataclass
class WebSocketFrame:
    '''
    WebSocket message data. This represents an entire WebSocket message, not just a fragmented frame as the name suggests.
    '''
    opcode: float
    mask: bool
    payload_data: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebSocketFrame:
        ...



@dataclass
class CachedResource:
    '''
    Information about the cached resource.
    '''
    url: str
    type_: ResourceType
    body_size: float
    response: typing.Optional[Response] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CachedResource:
        ...



@dataclass
class Initiator:
    '''
    Information about the request initiator.
    '''
    type_: str
    stack: typing.Optional[runtime.StackTrace] = ...
    url: typing.Optional[str] = ...
    line_number: typing.Optional[float] = ...
    column_number: typing.Optional[float] = ...
    request_id: typing.Optional[RequestId] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Initiator:
        ...



@dataclass
class CookiePartitionKey:
    '''
    cookiePartitionKey object
    The representation of the components of the key that are created by the cookiePartitionKey class contained in net/cookies/cookie_partition_key.h.
    '''
    top_level_site: str
    has_cross_site_ancestor: bool
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CookiePartitionKey:
        ...



@dataclass
class Cookie:
    '''
    Cookie object
    '''
    name: str
    value: str
    domain: str
    path: str
    size: int
    http_only: bool
    secure: bool
    session: bool
    priority: CookiePriority
    source_scheme: CookieSourceScheme
    source_port: int
    expires: typing.Optional[float] = ...
    same_site: typing.Optional[CookieSameSite] = ...
    partition_key: typing.Optional[CookiePartitionKey] = ...
    partition_key_opaque: typing.Optional[bool] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Cookie:
        ...



class SetCookieBlockedReason(enum.Enum):
    '''
    Types of reasons why a cookie may not be stored from a response.
    '''
    SECURE_ONLY = ...
    SAME_SITE_STRICT = ...
    SAME_SITE_LAX = ...
    SAME_SITE_UNSPECIFIED_TREATED_AS_LAX = ...
    SAME_SITE_NONE_INSECURE = ...
    USER_PREFERENCES = ...
    THIRD_PARTY_PHASEOUT = ...
    THIRD_PARTY_BLOCKED_IN_FIRST_PARTY_SET = ...
    SYNTAX_ERROR = ...
    SCHEME_NOT_SUPPORTED = ...
    OVERWRITE_SECURE = ...
    INVALID_DOMAIN = ...
    INVALID_PREFIX = ...
    UNKNOWN_ERROR = ...
    SCHEMEFUL_SAME_SITE_STRICT = ...
    SCHEMEFUL_SAME_SITE_LAX = ...
    SCHEMEFUL_SAME_SITE_UNSPECIFIED_TREATED_AS_LAX = ...
    NAME_VALUE_PAIR_EXCEEDS_MAX_SIZE = ...
    DISALLOWED_CHARACTER = ...
    NO_COOKIE_CONTENT = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> SetCookieBlockedReason:
        ...



class CookieBlockedReason(enum.Enum):
    '''
    Types of reasons why a cookie may not be sent with a request.
    '''
    SECURE_ONLY = ...
    NOT_ON_PATH = ...
    DOMAIN_MISMATCH = ...
    SAME_SITE_STRICT = ...
    SAME_SITE_LAX = ...
    SAME_SITE_UNSPECIFIED_TREATED_AS_LAX = ...
    SAME_SITE_NONE_INSECURE = ...
    USER_PREFERENCES = ...
    THIRD_PARTY_PHASEOUT = ...
    THIRD_PARTY_BLOCKED_IN_FIRST_PARTY_SET = ...
    UNKNOWN_ERROR = ...
    SCHEMEFUL_SAME_SITE_STRICT = ...
    SCHEMEFUL_SAME_SITE_LAX = ...
    SCHEMEFUL_SAME_SITE_UNSPECIFIED_TREATED_AS_LAX = ...
    NAME_VALUE_PAIR_EXCEEDS_MAX_SIZE = ...
    PORT_MISMATCH = ...
    SCHEME_MISMATCH = ...
    ANONYMOUS_CONTEXT = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CookieBlockedReason:
        ...



class CookieExemptionReason(enum.Enum):
    '''
    Types of reasons why a cookie should have been blocked by 3PCD but is exempted for the request.
    '''
    NONE = ...
    USER_SETTING = ...
    TPCD_METADATA = ...
    TPCD_DEPRECATION_TRIAL = ...
    TOP_LEVEL_TPCD_DEPRECATION_TRIAL = ...
    TPCD_HEURISTICS = ...
    ENTERPRISE_POLICY = ...
    STORAGE_ACCESS = ...
    TOP_LEVEL_STORAGE_ACCESS = ...
    SCHEME = ...
    SAME_SITE_NONE_COOKIES_IN_SANDBOX = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CookieExemptionReason:
        ...



@dataclass
class BlockedSetCookieWithReason:
    '''
    A cookie which was not stored from a response with the corresponding reason.
    '''
    blocked_reasons: typing.List[SetCookieBlockedReason]
    cookie_line: str
    cookie: typing.Optional[Cookie] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BlockedSetCookieWithReason:
        ...



@dataclass
class ExemptedSetCookieWithReason:
    '''
    A cookie should have been blocked by 3PCD but is exempted and stored from a response with the
    corresponding reason. A cookie could only have at most one exemption reason.
    '''
    exemption_reason: CookieExemptionReason
    cookie_line: str
    cookie: Cookie
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ExemptedSetCookieWithReason:
        ...



@dataclass
class AssociatedCookie:
    '''
    A cookie associated with the request which may or may not be sent with it.
    Includes the cookies itself and reasons for blocking or exemption.
    '''
    cookie: Cookie
    blocked_reasons: typing.List[CookieBlockedReason]
    exemption_reason: typing.Optional[CookieExemptionReason] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AssociatedCookie:
        ...



@dataclass
class CookieParam:
    '''
    Cookie parameter object
    '''
    name: str
    value: str
    url: typing.Optional[str] = ...
    domain: typing.Optional[str] = ...
    path: typing.Optional[str] = ...
    secure: typing.Optional[bool] = ...
    http_only: typing.Optional[bool] = ...
    same_site: typing.Optional[CookieSameSite] = ...
    expires: typing.Optional[TimeSinceEpoch] = ...
    priority: typing.Optional[CookiePriority] = ...
    source_scheme: typing.Optional[CookieSourceScheme] = ...
    source_port: typing.Optional[int] = ...
    partition_key: typing.Optional[CookiePartitionKey] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CookieParam:
        ...



@dataclass
class AuthChallenge:
    '''
    Authorization challenge for HTTP status code 401 or 407.
    '''
    origin: str
    scheme: str
    realm: str
    source: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AuthChallenge:
        ...



@dataclass
class AuthChallengeResponse:
    '''
    Response to an AuthChallenge.
    '''
    response: str
    username: typing.Optional[str] = ...
    password: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AuthChallengeResponse:
        ...



class InterceptionStage(enum.Enum):
    '''
    Stages of the interception to begin intercepting. Request will intercept before the request is
    sent. Response will intercept after the response is received.
    '''
    REQUEST = ...
    HEADERS_RECEIVED = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> InterceptionStage:
        ...



@dataclass
class RequestPattern:
    '''
    Request pattern for interception.
    '''
    url_pattern: typing.Optional[str] = ...
    resource_type: typing.Optional[ResourceType] = ...
    interception_stage: typing.Optional[InterceptionStage] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RequestPattern:
        ...



@dataclass
class SignedExchangeSignature:
    '''
    Information about a signed exchange signature.
    https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl.html#rfc.section.3.1
    '''
    label: str
    signature: str
    integrity: str
    validity_url: str
    date: int
    expires: int
    cert_url: typing.Optional[str] = ...
    cert_sha256: typing.Optional[str] = ...
    certificates: typing.Optional[typing.List[str]] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SignedExchangeSignature:
        ...



@dataclass
class SignedExchangeHeader:
    '''
    Information about a signed exchange header.
    https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl.html#cbor-representation
    '''
    request_url: str
    response_code: int
    response_headers: Headers
    signatures: typing.List[SignedExchangeSignature]
    header_integrity: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SignedExchangeHeader:
        ...



class SignedExchangeErrorField(enum.Enum):
    '''
    Field type for a signed exchange related error.
    '''
    SIGNATURE_SIG = ...
    SIGNATURE_INTEGRITY = ...
    SIGNATURE_CERT_URL = ...
    SIGNATURE_CERT_SHA256 = ...
    SIGNATURE_VALIDITY_URL = ...
    SIGNATURE_TIMESTAMPS = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> SignedExchangeErrorField:
        ...



@dataclass
class SignedExchangeError:
    '''
    Information about a signed exchange response.
    '''
    message: str
    signature_index: typing.Optional[int] = ...
    error_field: typing.Optional[SignedExchangeErrorField] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SignedExchangeError:
        ...



@dataclass
class SignedExchangeInfo:
    '''
    Information about a signed exchange response.
    '''
    outer_response: Response
    has_extra_info: bool
    header: typing.Optional[SignedExchangeHeader] = ...
    security_details: typing.Optional[SecurityDetails] = ...
    errors: typing.Optional[typing.List[SignedExchangeError]] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SignedExchangeInfo:
        ...



class ContentEncoding(enum.Enum):
    '''
    List of content encodings supported by the backend.
    '''
    DEFLATE = ...
    GZIP = ...
    BR = ...
    ZSTD = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ContentEncoding:
        ...



@dataclass
class NetworkConditions:
    url_pattern: str
    latency: float
    download_throughput: float
    upload_throughput: float
    connection_type: typing.Optional[ConnectionType] = ...
    packet_loss: typing.Optional[float] = ...
    packet_queue_length: typing.Optional[int] = ...
    packet_reordering: typing.Optional[bool] = ...
    offline: typing.Optional[bool] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> NetworkConditions:
        ...



@dataclass
class BlockPattern:
    url_pattern: str
    block: bool
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BlockPattern:
        ...



class DirectSocketDnsQueryType(enum.Enum):
    IPV4 = ...
    IPV6 = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> DirectSocketDnsQueryType:
        ...



@dataclass
class DirectTCPSocketOptions:
    no_delay: bool
    keep_alive_delay: typing.Optional[float] = ...
    send_buffer_size: typing.Optional[float] = ...
    receive_buffer_size: typing.Optional[float] = ...
    dns_query_type: typing.Optional[DirectSocketDnsQueryType] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectTCPSocketOptions:
        ...



@dataclass
class DirectUDPSocketOptions:
    remote_addr: typing.Optional[str] = ...
    remote_port: typing.Optional[int] = ...
    local_addr: typing.Optional[str] = ...
    local_port: typing.Optional[int] = ...
    dns_query_type: typing.Optional[DirectSocketDnsQueryType] = ...
    send_buffer_size: typing.Optional[float] = ...
    receive_buffer_size: typing.Optional[float] = ...
    multicast_loopback: typing.Optional[bool] = ...
    multicast_time_to_live: typing.Optional[int] = ...
    multicast_allow_address_sharing: typing.Optional[bool] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectUDPSocketOptions:
        ...



@dataclass
class DirectUDPMessage:
    data: str
    remote_addr: typing.Optional[str] = ...
    remote_port: typing.Optional[int] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectUDPMessage:
        ...



class LocalNetworkAccessRequestPolicy(enum.Enum):
    ALLOW = ...
    BLOCK_FROM_INSECURE_TO_MORE_PRIVATE = ...
    WARN_FROM_INSECURE_TO_MORE_PRIVATE = ...
    PERMISSION_BLOCK = ...
    PERMISSION_WARN = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> LocalNetworkAccessRequestPolicy:
        ...



class IPAddressSpace(enum.Enum):
    LOOPBACK = ...
    LOCAL = ...
    PUBLIC = ...
    UNKNOWN = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> IPAddressSpace:
        ...



@dataclass
class ConnectTiming:
    request_time: float
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ConnectTiming:
        ...



@dataclass
class ClientSecurityState:
    initiator_is_secure_context: bool
    initiator_ip_address_space: IPAddressSpace
    local_network_access_request_policy: LocalNetworkAccessRequestPolicy
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ClientSecurityState:
        ...



@dataclass
class AdScriptIdentifier:
    '''
    Identifies the script on the stack that caused a resource or element to be
    labeled as an ad. For resources, this indicates the context that triggered
    the fetch. For elements, this indicates the context that caused the element
    to be appended to the DOM.
    '''
    script_id: runtime.ScriptId
    debugger_id: runtime.UniqueDebuggerId
    name: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AdScriptIdentifier:
        ...



@dataclass
class AdAncestry:
    '''
    Encapsulates the script ancestry and the root script filter list rule that
    caused the resource or element to be labeled as an ad.
    '''
    ancestry_chain: typing.List[AdScriptIdentifier]
    root_script_filterlist_rule: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AdAncestry:
        ...



@dataclass
class AdProvenance:
    '''
    Represents the provenance of an ad resource or element. Only one of
    ``filterlistRule`` or ``adScriptAncestry`` can be set. If ``filterlistRule``
    is provided, the resource URL directly matches a filter list rule. If
    ``adScriptAncestry`` is provided, an ad script initiated the resource fetch or
    appended the element to the DOM. If neither is provided, the entity is
    known to be an ad, but provenance tracking information is unavailable.
    '''
    filterlist_rule: typing.Optional[str] = ...
    ad_script_ancestry: typing.Optional[AdAncestry] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AdProvenance:
        ...



class CrossOriginOpenerPolicyValue(enum.Enum):
    SAME_ORIGIN = ...
    SAME_ORIGIN_ALLOW_POPUPS = ...
    RESTRICT_PROPERTIES = ...
    UNSAFE_NONE = ...
    SAME_ORIGIN_PLUS_COEP = ...
    RESTRICT_PROPERTIES_PLUS_COEP = ...
    NOOPENER_ALLOW_POPUPS = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CrossOriginOpenerPolicyValue:
        ...



@dataclass
class CrossOriginOpenerPolicyStatus:
    value: CrossOriginOpenerPolicyValue
    report_only_value: CrossOriginOpenerPolicyValue
    reporting_endpoint: typing.Optional[str] = ...
    report_only_reporting_endpoint: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CrossOriginOpenerPolicyStatus:
        ...



class CrossOriginEmbedderPolicyValue(enum.Enum):
    NONE = ...
    CREDENTIALLESS = ...
    REQUIRE_CORP = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> CrossOriginEmbedderPolicyValue:
        ...



@dataclass
class CrossOriginEmbedderPolicyStatus:
    value: CrossOriginEmbedderPolicyValue
    report_only_value: CrossOriginEmbedderPolicyValue
    reporting_endpoint: typing.Optional[str] = ...
    report_only_reporting_endpoint: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CrossOriginEmbedderPolicyStatus:
        ...



class ContentSecurityPolicySource(enum.Enum):
    HTTP = ...
    META = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ContentSecurityPolicySource:
        ...



@dataclass
class ContentSecurityPolicyStatus:
    effective_directives: str
    is_enforced: bool
    source: ContentSecurityPolicySource
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ContentSecurityPolicyStatus:
        ...



@dataclass
class SecurityIsolationStatus:
    coop: typing.Optional[CrossOriginOpenerPolicyStatus] = ...
    coep: typing.Optional[CrossOriginEmbedderPolicyStatus] = ...
    csp: typing.Optional[typing.List[ContentSecurityPolicyStatus]] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SecurityIsolationStatus:
        ...



class ReportStatus(enum.Enum):
    '''
    The status of a Reporting API report.
    '''
    QUEUED = ...
    PENDING = ...
    MARKED_FOR_REMOVAL = ...
    SUCCESS = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ReportStatus:
        ...



class ReportId(str):
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ReportId:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class ReportingApiReport:
    '''
    An object representing a report generated by the Reporting API.
    '''
    id_: ReportId
    initiator_url: str
    destination: str
    type_: str
    timestamp: TimeSinceEpoch
    depth: int
    completed_attempts: int
    body: dict
    status: ReportStatus
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReportingApiReport:
        ...



@dataclass
class ReportingApiEndpoint:
    url: str
    group_name: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReportingApiEndpoint:
        ...



@dataclass
class DeviceBoundSessionKey:
    '''
    Unique identifier for a device bound session.
    '''
    site: str
    id_: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DeviceBoundSessionKey:
        ...



@dataclass
class DeviceBoundSessionWithUsage:
    '''
    How a device bound session was used during a request.
    '''
    session_key: DeviceBoundSessionKey
    usage: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DeviceBoundSessionWithUsage:
        ...



@dataclass
class DeviceBoundSessionCookieCraving:
    '''
    A device bound session's cookie craving.
    '''
    name: str
    domain: str
    path: str
    secure: bool
    http_only: bool
    same_site: typing.Optional[CookieSameSite] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DeviceBoundSessionCookieCraving:
        ...



@dataclass
class DeviceBoundSessionUrlRule:
    '''
    A device bound session's inclusion URL rule.
    '''
    rule_type: str
    host_pattern: str
    path_prefix: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DeviceBoundSessionUrlRule:
        ...



@dataclass
class DeviceBoundSessionInclusionRules:
    '''
    A device bound session's inclusion rules.
    '''
    origin: str
    include_site: bool
    url_rules: typing.List[DeviceBoundSessionUrlRule]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DeviceBoundSessionInclusionRules:
        ...



@dataclass
class DeviceBoundSession:
    '''
    A device bound session.
    '''
    key: DeviceBoundSessionKey
    refresh_url: str
    inclusion_rules: DeviceBoundSessionInclusionRules
    cookie_cravings: typing.List[DeviceBoundSessionCookieCraving]
    expiry_date: TimeSinceEpoch
    allowed_refresh_initiators: typing.List[str]
    cached_challenge: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DeviceBoundSession:
        ...



class DeviceBoundSessionEventId(str):
    '''
    A unique identifier for a device bound session event.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> DeviceBoundSessionEventId:
        ...

    def __repr__(self) -> str:
        ...



class DeviceBoundSessionFetchResult(enum.Enum):
    '''
    A fetch result for a device bound session creation or refresh.
    '''
    SUCCESS = ...
    KEY_ERROR = ...
    SIGNING_ERROR = ...
    TRANSIENT_SIGNING_ERROR = ...
    SERVER_REQUESTED_TERMINATION = ...
    INVALID_SESSION_ID = ...
    INVALID_CHALLENGE = ...
    TOO_MANY_CHALLENGES = ...
    INVALID_FETCHER_URL = ...
    INVALID_REFRESH_URL = ...
    TRANSIENT_HTTP_ERROR = ...
    SCOPE_ORIGIN_SAME_SITE_MISMATCH = ...
    REFRESH_URL_SAME_SITE_MISMATCH = ...
    MISMATCHED_SESSION_ID = ...
    MISSING_SCOPE = ...
    NO_CREDENTIALS = ...
    SUBDOMAIN_REGISTRATION_WELL_KNOWN_UNAVAILABLE = ...
    SUBDOMAIN_REGISTRATION_UNAUTHORIZED = ...
    SUBDOMAIN_REGISTRATION_WELL_KNOWN_MALFORMED = ...
    SESSION_PROVIDER_WELL_KNOWN_UNAVAILABLE = ...
    RELYING_PARTY_WELL_KNOWN_UNAVAILABLE = ...
    FEDERATED_KEY_THUMBPRINT_MISMATCH = ...
    INVALID_FEDERATED_SESSION_URL = ...
    INVALID_FEDERATED_KEY = ...
    TOO_MANY_RELYING_ORIGIN_LABELS = ...
    BOUND_COOKIE_SET_FORBIDDEN = ...
    NET_ERROR = ...
    PROXY_ERROR = ...
    EMPTY_SESSION_CONFIG = ...
    INVALID_CREDENTIALS_CONFIG = ...
    INVALID_CREDENTIALS_TYPE = ...
    INVALID_CREDENTIALS_EMPTY_NAME = ...
    INVALID_CREDENTIALS_COOKIE = ...
    PERSISTENT_HTTP_ERROR = ...
    REGISTRATION_ATTEMPTED_CHALLENGE = ...
    INVALID_SCOPE_ORIGIN = ...
    SCOPE_ORIGIN_CONTAINS_PATH = ...
    REFRESH_INITIATOR_NOT_STRING = ...
    REFRESH_INITIATOR_INVALID_HOST_PATTERN = ...
    INVALID_SCOPE_SPECIFICATION = ...
    MISSING_SCOPE_SPECIFICATION_TYPE = ...
    EMPTY_SCOPE_SPECIFICATION_DOMAIN = ...
    EMPTY_SCOPE_SPECIFICATION_PATH = ...
    INVALID_SCOPE_SPECIFICATION_TYPE = ...
    INVALID_SCOPE_INCLUDE_SITE = ...
    MISSING_SCOPE_INCLUDE_SITE = ...
    FEDERATED_NOT_AUTHORIZED_BY_PROVIDER = ...
    FEDERATED_NOT_AUTHORIZED_BY_RELYING_PARTY = ...
    SESSION_PROVIDER_WELL_KNOWN_MALFORMED = ...
    SESSION_PROVIDER_WELL_KNOWN_HAS_PROVIDER_ORIGIN = ...
    RELYING_PARTY_WELL_KNOWN_MALFORMED = ...
    RELYING_PARTY_WELL_KNOWN_HAS_RELYING_ORIGINS = ...
    INVALID_FEDERATED_SESSION_PROVIDER_SESSION_MISSING = ...
    INVALID_FEDERATED_SESSION_WRONG_PROVIDER_ORIGIN = ...
    INVALID_CREDENTIALS_COOKIE_CREATION_TIME = ...
    INVALID_CREDENTIALS_COOKIE_NAME = ...
    INVALID_CREDENTIALS_COOKIE_PARSING = ...
    INVALID_CREDENTIALS_COOKIE_UNPERMITTED_ATTRIBUTE = ...
    INVALID_CREDENTIALS_COOKIE_INVALID_DOMAIN = ...
    INVALID_CREDENTIALS_COOKIE_PREFIX = ...
    INVALID_SCOPE_RULE_PATH = ...
    INVALID_SCOPE_RULE_HOST_PATTERN = ...
    SCOPE_RULE_ORIGIN_SCOPED_HOST_PATTERN_MISMATCH = ...
    SCOPE_RULE_SITE_SCOPED_HOST_PATTERN_MISMATCH = ...
    SIGNING_QUOTA_EXCEEDED = ...
    INVALID_CONFIG_JSON = ...
    INVALID_FEDERATED_SESSION_PROVIDER_FAILED_TO_RESTORE_KEY = ...
    FAILED_TO_UNWRAP_KEY = ...
    SESSION_DELETED_DURING_REFRESH = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> DeviceBoundSessionFetchResult:
        ...



@dataclass
class DeviceBoundSessionFailedRequest:
    '''
    Details about a failed device bound session network request.
    '''
    request_url: str
    net_error: typing.Optional[str] = ...
    response_error: typing.Optional[int] = ...
    response_error_body: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DeviceBoundSessionFailedRequest:
        ...



@dataclass
class CreationEventDetails:
    '''
    Session event details specific to creation.
    '''
    fetch_result: DeviceBoundSessionFetchResult
    new_session: typing.Optional[DeviceBoundSession] = ...
    failed_request: typing.Optional[DeviceBoundSessionFailedRequest] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CreationEventDetails:
        ...



@dataclass
class RefreshEventDetails:
    '''
    Session event details specific to refresh.
    '''
    refresh_result: str
    was_fully_proactive_refresh: bool
    fetch_result: typing.Optional[DeviceBoundSessionFetchResult] = ...
    new_session: typing.Optional[DeviceBoundSession] = ...
    failed_request: typing.Optional[DeviceBoundSessionFailedRequest] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RefreshEventDetails:
        ...



@dataclass
class TerminationEventDetails:
    '''
    Session event details specific to termination.
    '''
    deletion_reason: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TerminationEventDetails:
        ...



@dataclass
class ChallengeEventDetails:
    '''
    Session event details specific to challenges.
    '''
    challenge_result: str
    challenge: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ChallengeEventDetails:
        ...



@dataclass
class LoadNetworkResourcePageResult:
    '''
    An object providing the result of a network resource load.
    '''
    success: bool
    net_error: typing.Optional[float] = ...
    net_error_name: typing.Optional[str] = ...
    http_status_code: typing.Optional[float] = ...
    stream: typing.Optional[io.StreamHandle] = ...
    headers: typing.Optional[Headers] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LoadNetworkResourcePageResult:
        ...



@dataclass
class LoadNetworkResourceOptions:
    '''
    An options object that may be extended later to better support CORS,
    CORB and streaming.
    '''
    disable_cache: bool
    include_credentials: bool
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LoadNetworkResourceOptions:
        ...



def set_accepted_encodings(encodings: typing.List[ContentEncoding]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets a list of content encodings that will be accepted. Empty list means no encoding is accepted.

    **EXPERIMENTAL**

    :param encodings: List of accepted content encodings.
    '''
    ...

def clear_accepted_encodings_override() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Clears accepted encodings set by setAcceptedEncodings

    **EXPERIMENTAL**
    '''
    ...

@deprecated(version="1.3")
def can_clear_browser_cache() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, bool]:
    '''
    Tells whether clearing browser cache is supported.

    .. deprecated:: 1.3

    :returns: True if browser cache can be cleared.
    '''
    ...

@deprecated(version="1.3")
def can_clear_browser_cookies() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, bool]:
    '''
    Tells whether clearing browser cookies is supported.

    .. deprecated:: 1.3

    :returns: True if browser cookies can be cleared.
    '''
    ...

@deprecated(version="1.3")
def can_emulate_network_conditions() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, bool]:
    '''
    Tells whether emulation of network conditions is supported.

    .. deprecated:: 1.3

    :returns: True if emulation of network conditions is supported.
    '''
    ...

def clear_browser_cache() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Clears browser cache.
    '''
    ...

def clear_browser_cookies() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Clears browser cookies.
    '''
    ...

@deprecated(version="1.3")
def continue_intercepted_request(interception_id: InterceptionId, error_reason: typing.Optional[ErrorReason] = ..., raw_response: typing.Optional[str] = ..., url: typing.Optional[str] = ..., method: typing.Optional[str] = ..., post_data: typing.Optional[str] = ..., headers: typing.Optional[Headers] = ..., auth_challenge_response: typing.Optional[AuthChallengeResponse] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Response to Network.requestIntercepted which either modifies the request to continue with any
    modifications, or blocks it, or completes it with the provided response bytes. If a network
    fetch occurs as a result which encounters a redirect an additional Network.requestIntercepted
    event will be sent with the same InterceptionId.
    Deprecated, use Fetch.continueRequest, Fetch.fulfillRequest and Fetch.failRequest instead.

    .. deprecated:: 1.3

    **EXPERIMENTAL**

    :param interception_id:
    :param error_reason: *(Optional)* If set this causes the request to fail with the given reason. Passing ```Aborted```` for requests marked with ````isNavigationRequest``` also cancels the navigation. Must not be set in response to an authChallenge.
    :param raw_response: *(Optional)* If set the requests completes using with the provided base64 encoded raw response, including HTTP status line and headers etc... Must not be set in response to an authChallenge. (Encoded as a base64 string when passed over JSON)
    :param url: *(Optional)* If set the request url will be modified in a way that's not observable by page. Must not be set in response to an authChallenge.
    :param method: *(Optional)* If set this allows the request method to be overridden. Must not be set in response to an authChallenge.
    :param post_data: *(Optional)* If set this allows postData to be set. Must not be set in response to an authChallenge.
    :param headers: *(Optional)* If set this allows the request headers to be changed. Must not be set in response to an authChallenge.
    :param auth_challenge_response: *(Optional)* Response to a requestIntercepted with an authChallenge. Must not be set otherwise.
    '''
    ...

def delete_cookies(name: str, url: typing.Optional[str] = ..., domain: typing.Optional[str] = ..., path: typing.Optional[str] = ..., partition_key: typing.Optional[CookiePartitionKey] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Deletes browser cookies with matching name and url or domain/path/partitionKey pair.

    :param name: Name of the cookies to remove.
    :param url: *(Optional)* If specified, deletes all the cookies with the given name where domain and path match provided URL.
    :param domain: *(Optional)* If specified, deletes only cookies with the exact domain.
    :param path: *(Optional)* If specified, deletes only cookies with the exact path.
    :param partition_key: **(EXPERIMENTAL)** *(Optional)* If specified, deletes only cookies with the the given name and partitionKey where all partition key attributes match the cookie partition key attribute.
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disables network tracking, prevents network events from being sent to the client.
    '''
    ...

@deprecated(version="1.3")
def emulate_network_conditions(offline: bool, latency: float, download_throughput: float, upload_throughput: float, connection_type: typing.Optional[ConnectionType] = ..., packet_loss: typing.Optional[float] = ..., packet_queue_length: typing.Optional[int] = ..., packet_reordering: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Activates emulation of network conditions. This command is deprecated in favor of the emulateNetworkConditionsByRule
    and overrideNetworkState commands, which can be used together to the same effect.

    .. deprecated:: 1.3

    :param offline: True to emulate internet disconnection.
    :param latency: Minimum latency from request sent to response headers received (ms).
    :param download_throughput: Maximal aggregated download throughput (bytes/sec). -1 disables download throttling.
    :param upload_throughput: Maximal aggregated upload throughput (bytes/sec).  -1 disables upload throttling.
    :param connection_type: *(Optional)* Connection type if known.
    :param packet_loss: **(EXPERIMENTAL)** *(Optional)* WebRTC packet loss (percent, 0-100). 0 disables packet loss emulation, 100 drops all the packets.
    :param packet_queue_length: **(EXPERIMENTAL)** *(Optional)* WebRTC packet queue length (packet). 0 removes any queue length limitations.
    :param packet_reordering: **(EXPERIMENTAL)** *(Optional)* WebRTC packetReordering feature.
    '''
    ...

def emulate_network_conditions_by_rule(matched_network_conditions: typing.List[NetworkConditions], offline: typing.Optional[bool] = ..., emulate_offline_service_worker: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[str]]:
    '''
    Activates emulation of network conditions for individual requests using URL match patterns. Unlike the deprecated
    Network.emulateNetworkConditions this method does not affect ``navigator`` state. Use Network.overrideNetworkState to
    explicitly modify ``navigator`` behavior.

    **EXPERIMENTAL**

    :param offline: **(DEPRECATED)** *(Optional)* True to emulate internet disconnection. Deprecated, use the offline property in matchedNetworkConditions or emulateOfflineServiceWorker instead.
    :param emulate_offline_service_worker: *(Optional)* True to emulate offline service worker.
    :param matched_network_conditions: Configure conditions for matching requests. If multiple entries match a request, the first entry wins.  Global conditions can be configured by leaving the urlPattern for the conditions empty. These global conditions are also applied for throttling of p2p connections.
    :returns: An id for each entry in matchedNetworkConditions. The id will be included in the requestWillBeSentExtraInfo for requests affected by a rule.
    '''
    ...

def override_network_state(offline: bool, latency: float, download_throughput: float, upload_throughput: float, connection_type: typing.Optional[ConnectionType] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Override the state of navigator.onLine and navigator.connection.

    **EXPERIMENTAL**

    :param offline: True to emulate internet disconnection.
    :param latency: Minimum latency from request sent to response headers received (ms).
    :param download_throughput: Maximal aggregated download throughput (bytes/sec). -1 disables download throttling.
    :param upload_throughput: Maximal aggregated upload throughput (bytes/sec).  -1 disables upload throttling.
    :param connection_type: *(Optional)* Connection type if known.
    '''
    ...

def enable(max_total_buffer_size: typing.Optional[int] = ..., max_resource_buffer_size: typing.Optional[int] = ..., max_post_data_size: typing.Optional[int] = ..., report_direct_socket_traffic: typing.Optional[bool] = ..., enable_durable_messages: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables network tracking, network events will now be delivered to the client.

    :param max_total_buffer_size: **(EXPERIMENTAL)** *(Optional)* Buffer size in bytes to use when preserving network payloads (XHRs, etc). This is the maximum number of bytes that will be collected by this DevTools session.
    :param max_resource_buffer_size: **(EXPERIMENTAL)** *(Optional)* Per-resource buffer size in bytes to use when preserving network payloads (XHRs, etc).
    :param max_post_data_size: *(Optional)* Longest post body size (in bytes) that would be included in requestWillBeSent notification
    :param report_direct_socket_traffic: **(EXPERIMENTAL)** *(Optional)* Whether DirectSocket chunk send/receive events should be reported.
    :param enable_durable_messages: **(EXPERIMENTAL)** *(Optional)* Enable storing response bodies outside of renderer, so that these survive a cross-process navigation. Requires maxTotalBufferSize to be set. Currently defaults to false. This field is being deprecated in favor of the dedicated configureDurableMessages command, due to the possibility of deadlocks when awaiting Network.enable before issuing Runtime.runIfWaitingForDebugger.
    '''
    ...

def configure_durable_messages(max_total_buffer_size: typing.Optional[int] = ..., max_resource_buffer_size: typing.Optional[int] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Configures storing response bodies outside of renderer, so that these survive
    a cross-process navigation.
    If maxTotalBufferSize is not set, durable messages are disabled.

    **EXPERIMENTAL**

    :param max_total_buffer_size: *(Optional)* Buffer size in bytes to use when preserving network payloads (XHRs, etc).
    :param max_resource_buffer_size: *(Optional)* Per-resource buffer size in bytes to use when preserving network payloads (XHRs, etc).
    '''
    ...

@deprecated(version="1.3")
def get_all_cookies() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[Cookie]]:
    '''
    Returns all browser cookies. Depending on the backend support, will return detailed cookie
    information in the ``cookies`` field.
    Deprecated. Use Storage.getCookies instead.

    .. deprecated:: 1.3

    :returns: Array of cookie objects.
    '''
    ...

def get_certificate(origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[str]]:
    '''
    Returns the DER-encoded certificate.

    **EXPERIMENTAL**

    :param origin: Origin to get certificate for.
    :returns:
    '''
    ...

def get_cookies(urls: typing.Optional[typing.List[str]] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[Cookie]]:
    '''
    Returns all browser cookies for the current URL. Depending on the backend support, will return
    detailed cookie information in the ``cookies`` field.

    :param urls: *(Optional)* The list of URLs for which applicable cookies will be fetched. If not specified, it's assumed to be set to the list containing the URLs of the page and all of its subframes.
    :returns: Array of cookie objects.
    '''
    ...

def get_response_body(request_id: RequestId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[str, bool]]:
    '''
    Returns content served for the given request.

    :param request_id: Identifier of the network request to get content for.
    :returns: A tuple with the following items:

        0. **body** - Response body.
        1. **base64Encoded** - True, if content was sent as base64.
    '''
    ...

def get_request_post_data(request_id: RequestId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[str, bool]]:
    '''
    Returns post data sent with the request. Returns an error when no data was sent with the request.

    :param request_id: Identifier of the network request to get content for.
    :returns: A tuple with the following items:

        0. **postData** - Request body string, omitting files from multipart requests
        1. **base64Encoded** - True, if content was sent as base64.
    '''
    ...

def get_response_body_for_interception(interception_id: InterceptionId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[str, bool]]:
    '''
    Returns content served for the given currently intercepted request.

    **EXPERIMENTAL**

    :param interception_id: Identifier for the intercepted request to get body for.
    :returns: A tuple with the following items:

        0. **body** - Response body.
        1. **base64Encoded** - True, if content was sent as base64.
    '''
    ...

def take_response_body_for_interception_as_stream(interception_id: InterceptionId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, io.StreamHandle]:
    '''
    Returns a handle to the stream representing the response body. Note that after this command,
    the intercepted request can't be continued as is -- you either need to cancel it or to provide
    the response body. The stream only supports sequential read, IO.read will fail if the position
    is specified.

    **EXPERIMENTAL**

    :param interception_id:
    :returns:
    '''
    ...

def replay_xhr(request_id: RequestId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    This method sends a new XMLHttpRequest which is identical to the original one. The following
    parameters should be identical: method, url, async, request body, extra headers, withCredentials
    attribute, user, password.

    **EXPERIMENTAL**

    :param request_id: Identifier of XHR to replay.
    '''
    ...

def search_in_response_body(request_id: RequestId, query: str, case_sensitive: typing.Optional[bool] = ..., is_regex: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[debugger.SearchMatch]]:
    '''
    Searches for given string in response content.

    **EXPERIMENTAL**

    :param request_id: Identifier of the network response to search.
    :param query: String to search for.
    :param case_sensitive: *(Optional)* If true, search is case sensitive.
    :param is_regex: *(Optional)* If true, treats string parameter as regex.
    :returns: List of search matches.
    '''
    ...

def set_blocked_ur_ls(url_patterns: typing.Optional[typing.List[BlockPattern]] = ..., urls: typing.Optional[typing.List[str]] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Blocks URLs from loading.

    **EXPERIMENTAL**

    :param url_patterns: *(Optional)* Patterns to match in the order in which they are given. These patterns also take precedence over any wildcard patterns defined in ```urls```.
    :param urls: **(DEPRECATED)** *(Optional)* URL patterns to block. Wildcards ('*') are allowed.
    '''
    ...

def set_bypass_service_worker(bypass: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Toggles ignoring of service worker for each request.

    :param bypass: Bypass service worker and load from network.
    '''
    ...

def set_cache_disabled(cache_disabled: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Toggles ignoring cache for each request. If ``true``, cache will not be used.

    :param cache_disabled: Cache disabled state.
    '''
    ...

def set_cookie(name: str, value: str, url: typing.Optional[str] = ..., domain: typing.Optional[str] = ..., path: typing.Optional[str] = ..., secure: typing.Optional[bool] = ..., http_only: typing.Optional[bool] = ..., same_site: typing.Optional[CookieSameSite] = ..., expires: typing.Optional[TimeSinceEpoch] = ..., priority: typing.Optional[CookiePriority] = ..., source_scheme: typing.Optional[CookieSourceScheme] = ..., source_port: typing.Optional[int] = ..., partition_key: typing.Optional[CookiePartitionKey] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, bool]:
    '''
    Sets a cookie with the given cookie data; may overwrite equivalent cookies if they exist.

    :param name: Cookie name.
    :param value: Cookie value.
    :param url: *(Optional)* The request-URI to associate with the setting of the cookie. This value can affect the default domain, path, source port, and source scheme values of the created cookie.
    :param domain: *(Optional)* Cookie domain.
    :param path: *(Optional)* Cookie path.
    :param secure: *(Optional)* True if cookie is secure.
    :param http_only: *(Optional)* True if cookie is http-only.
    :param same_site: *(Optional)* Cookie SameSite type.
    :param expires: *(Optional)* Cookie expiration date, session cookie if not set
    :param priority: **(EXPERIMENTAL)** *(Optional)* Cookie Priority type.
    :param source_scheme: **(EXPERIMENTAL)** *(Optional)* Cookie source scheme type.
    :param source_port: **(EXPERIMENTAL)** *(Optional)* Cookie source port. Valid values are {-1, [1, 65535]}, -1 indicates an unspecified port. An unspecified port value allows protocol clients to emulate legacy cookie scope for the port. This is a temporary ability and it will be removed in the future.
    :param partition_key: **(EXPERIMENTAL)** *(Optional)* Cookie partition key. If not set, the cookie will be set as not partitioned.
    :returns: Always set to true. If an error occurs, the response indicates protocol error.
    '''
    ...

def set_cookies(cookies: typing.List[CookieParam]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets given cookies.

    :param cookies: Cookies to be set.
    '''
    ...

def set_extra_http_headers(headers: Headers) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Specifies whether to always send extra HTTP headers with the requests from this page.

    :param headers: Map with extra HTTP headers.
    '''
    ...

def set_attach_debug_stack(enabled: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Specifies whether to attach a page script stack id in requests

    **EXPERIMENTAL**

    :param enabled: Whether to attach a page script stack for debugging purpose.
    '''
    ...

@deprecated(version="1.3")
def set_request_interception(patterns: typing.List[RequestPattern]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets the requests to intercept that match the provided patterns and optionally resource types.
    Deprecated, please use Fetch.enable instead.

    .. deprecated:: 1.3

    **EXPERIMENTAL**

    :param patterns: Requests matching any of these patterns will be forwarded and wait for the corresponding continueInterceptedRequest call.
    '''
    ...

def set_user_agent_override(user_agent: str, accept_language: typing.Optional[str] = ..., platform: typing.Optional[str] = ..., user_agent_metadata: typing.Optional[emulation.UserAgentMetadata] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Allows overriding user agent with the given string.

    :param user_agent: User agent to use.
    :param accept_language: *(Optional)* Browser language to emulate.
    :param platform: *(Optional)* The platform navigator.platform should return.
    :param user_agent_metadata: **(EXPERIMENTAL)** *(Optional)* To be sent in Sec-CH-UA-* headers and returned in navigator.userAgentData
    '''
    ...

def stream_resource_content(request_id: RequestId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
    '''
    Enables streaming of the response for the given requestId.
    If enabled, the dataReceived event contains the data that was received during streaming.

    **EXPERIMENTAL**

    :param request_id: Identifier of the request to stream.
    :returns: Data that has been buffered until streaming is enabled. (Encoded as a base64 string when passed over JSON)
    '''
    ...

def get_security_isolation_status(frame_id: typing.Optional[page.FrameId] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SecurityIsolationStatus]:
    '''
    Returns information about the COEP/COOP isolation status.

    **EXPERIMENTAL**

    :param frame_id: *(Optional)* If no frameId is provided, the status of the target is provided.
    :returns:
    '''
    ...

def enable_reporting_api(enable: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables tracking for the Reporting API, events generated by the Reporting API will now be delivered to the client.
    Enabling triggers 'reportingApiReportAdded' for all existing reports.

    **EXPERIMENTAL**

    :param enable: Whether to enable or disable events for the Reporting API
    '''
    ...

def enable_device_bound_sessions(enable: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets up tracking device bound sessions and fetching of initial set of sessions.

    **EXPERIMENTAL**

    :param enable: Whether to enable or disable events.
    '''
    ...

def delete_device_bound_session(key: DeviceBoundSessionKey) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Deletes a device bound session.

    **EXPERIMENTAL**

    :param key:
    '''
    ...

def fetch_schemeful_site(origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
    '''
    Fetches the schemeful site for a specific origin.

    **EXPERIMENTAL**

    :param origin: The URL origin.
    :returns: The corresponding schemeful site.
    '''
    ...

def load_network_resource(url: str, options: LoadNetworkResourceOptions, frame_id: typing.Optional[page.FrameId] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, LoadNetworkResourcePageResult]:
    '''
    Fetches the resource and returns the content.

    **EXPERIMENTAL**

    :param frame_id: *(Optional)* Frame id to get the resource for. Mandatory for frame targets, and should be omitted for worker targets.
    :param url: URL of the resource to get content for.
    :param options: Options for the request.
    :returns:
    '''
    ...

def set_cookie_controls(enable_third_party_cookie_restriction: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets Controls for third-party cookie access
    Page reload is required before the new cookie behavior will be observed

    **EXPERIMENTAL**

    :param enable_third_party_cookie_restriction: Whether 3pc restriction is enabled.
    '''
    ...

@event_class('Network.dataReceived')
@dataclass
class DataReceived:
    '''
    Fired when data chunk was received over the network.
    '''
    request_id: RequestId
    timestamp: MonotonicTime
    data_length: int
    encoded_data_length: int
    data: typing.Optional[str]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DataReceived:
        ...



@event_class('Network.eventSourceMessageReceived')
@dataclass
class EventSourceMessageReceived:
    '''
    Fired when EventSource message is received.
    '''
    request_id: RequestId
    timestamp: MonotonicTime
    event_name: str
    event_id: str
    data: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> EventSourceMessageReceived:
        ...



@event_class('Network.loadingFailed')
@dataclass
class LoadingFailed:
    '''
    Fired when HTTP request has failed to load.
    '''
    request_id: RequestId
    timestamp: MonotonicTime
    type_: ResourceType
    error_text: str
    canceled: typing.Optional[bool]
    blocked_reason: typing.Optional[BlockedReason]
    cors_error_status: typing.Optional[CorsErrorStatus]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LoadingFailed:
        ...



@event_class('Network.loadingFinished')
@dataclass
class LoadingFinished:
    '''
    Fired when HTTP request has finished loading.
    '''
    request_id: RequestId
    timestamp: MonotonicTime
    encoded_data_length: float
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LoadingFinished:
        ...



@deprecated(version="1.3")
@event_class('Network.requestIntercepted')
@dataclass
class RequestIntercepted:
    '''
    **EXPERIMENTAL**

    Details of an intercepted HTTP request, which must be either allowed, blocked, modified or
    mocked.
    Deprecated, use Fetch.requestPaused instead.
    '''
    interception_id: InterceptionId
    request: Request
    frame_id: page.FrameId
    resource_type: ResourceType
    is_navigation_request: bool
    is_download: typing.Optional[bool]
    redirect_url: typing.Optional[str]
    auth_challenge: typing.Optional[AuthChallenge]
    response_error_reason: typing.Optional[ErrorReason]
    response_status_code: typing.Optional[int]
    response_headers: typing.Optional[Headers]
    request_id: typing.Optional[RequestId]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RequestIntercepted:
        ...



@event_class('Network.requestServedFromCache')
@dataclass
class RequestServedFromCache:
    '''
    Fired if request ended up loading from cache.
    '''
    request_id: RequestId
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RequestServedFromCache:
        ...



@event_class('Network.requestWillBeSent')
@dataclass
class RequestWillBeSent:
    '''
    Fired when page is about to send HTTP request.
    '''
    request_id: RequestId
    loader_id: LoaderId
    document_url: str
    request: Request
    timestamp: MonotonicTime
    wall_time: TimeSinceEpoch
    initiator: Initiator
    redirect_has_extra_info: bool
    redirect_response: typing.Optional[Response]
    type_: typing.Optional[ResourceType]
    frame_id: typing.Optional[page.FrameId]
    has_user_gesture: typing.Optional[bool]
    render_blocking_behavior: typing.Optional[RenderBlockingBehavior]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RequestWillBeSent:
        ...



@event_class('Network.resourceChangedPriority')
@dataclass
class ResourceChangedPriority:
    '''
    **EXPERIMENTAL**

    Fired when resource loading priority is changed
    '''
    request_id: RequestId
    new_priority: ResourcePriority
    timestamp: MonotonicTime
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ResourceChangedPriority:
        ...



@event_class('Network.signedExchangeReceived')
@dataclass
class SignedExchangeReceived:
    '''
    **EXPERIMENTAL**

    Fired when a signed exchange was received over the network
    '''
    request_id: RequestId
    info: SignedExchangeInfo
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SignedExchangeReceived:
        ...



@event_class('Network.responseReceived')
@dataclass
class ResponseReceived:
    '''
    Fired when HTTP response is available.
    '''
    request_id: RequestId
    loader_id: LoaderId
    timestamp: MonotonicTime
    type_: ResourceType
    response: Response
    has_extra_info: bool
    frame_id: typing.Optional[page.FrameId]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ResponseReceived:
        ...



@event_class('Network.webSocketClosed')
@dataclass
class WebSocketClosed:
    '''
    Fired when WebSocket is closed.
    '''
    request_id: RequestId
    timestamp: MonotonicTime
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebSocketClosed:
        ...



@event_class('Network.webSocketCreated')
@dataclass
class WebSocketCreated:
    '''
    Fired upon WebSocket creation.
    '''
    request_id: RequestId
    url: str
    initiator: typing.Optional[Initiator]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebSocketCreated:
        ...



@event_class('Network.webSocketFrameError')
@dataclass
class WebSocketFrameError:
    '''
    Fired when WebSocket message error occurs.
    '''
    request_id: RequestId
    timestamp: MonotonicTime
    error_message: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebSocketFrameError:
        ...



@event_class('Network.webSocketFrameReceived')
@dataclass
class WebSocketFrameReceived:
    '''
    Fired when WebSocket message is received.
    '''
    request_id: RequestId
    timestamp: MonotonicTime
    response: WebSocketFrame
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebSocketFrameReceived:
        ...



@event_class('Network.webSocketFrameSent')
@dataclass
class WebSocketFrameSent:
    '''
    Fired when WebSocket message is sent.
    '''
    request_id: RequestId
    timestamp: MonotonicTime
    response: WebSocketFrame
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebSocketFrameSent:
        ...



@event_class('Network.webSocketHandshakeResponseReceived')
@dataclass
class WebSocketHandshakeResponseReceived:
    '''
    Fired when WebSocket handshake response becomes available.
    '''
    request_id: RequestId
    timestamp: MonotonicTime
    response: WebSocketResponse
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebSocketHandshakeResponseReceived:
        ...



@event_class('Network.webSocketWillSendHandshakeRequest')
@dataclass
class WebSocketWillSendHandshakeRequest:
    '''
    Fired when WebSocket is about to initiate handshake.
    '''
    request_id: RequestId
    timestamp: MonotonicTime
    wall_time: TimeSinceEpoch
    request: WebSocketRequest
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebSocketWillSendHandshakeRequest:
        ...



@event_class('Network.webTransportCreated')
@dataclass
class WebTransportCreated:
    '''
    Fired upon WebTransport creation.
    '''
    transport_id: RequestId
    url: str
    timestamp: MonotonicTime
    initiator: typing.Optional[Initiator]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebTransportCreated:
        ...



@event_class('Network.webTransportConnectionEstablished')
@dataclass
class WebTransportConnectionEstablished:
    '''
    Fired when WebTransport handshake is finished.
    '''
    transport_id: RequestId
    timestamp: MonotonicTime
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebTransportConnectionEstablished:
        ...



@event_class('Network.webTransportClosed')
@dataclass
class WebTransportClosed:
    '''
    Fired when WebTransport is disposed.
    '''
    transport_id: RequestId
    timestamp: MonotonicTime
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WebTransportClosed:
        ...



@event_class('Network.directTCPSocketCreated')
@dataclass
class DirectTCPSocketCreated:
    '''
    **EXPERIMENTAL**

    Fired upon direct_socket.TCPSocket creation.
    '''
    identifier: RequestId
    remote_addr: str
    remote_port: int
    options: DirectTCPSocketOptions
    timestamp: MonotonicTime
    initiator: typing.Optional[Initiator]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectTCPSocketCreated:
        ...



@event_class('Network.directTCPSocketOpened')
@dataclass
class DirectTCPSocketOpened:
    '''
    **EXPERIMENTAL**

    Fired when direct_socket.TCPSocket connection is opened.
    '''
    identifier: RequestId
    remote_addr: str
    remote_port: int
    timestamp: MonotonicTime
    local_addr: typing.Optional[str]
    local_port: typing.Optional[int]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectTCPSocketOpened:
        ...



@event_class('Network.directTCPSocketAborted')
@dataclass
class DirectTCPSocketAborted:
    '''
    **EXPERIMENTAL**

    Fired when direct_socket.TCPSocket is aborted.
    '''
    identifier: RequestId
    error_message: str
    timestamp: MonotonicTime
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectTCPSocketAborted:
        ...



@event_class('Network.directTCPSocketClosed')
@dataclass
class DirectTCPSocketClosed:
    '''
    **EXPERIMENTAL**

    Fired when direct_socket.TCPSocket is closed.
    '''
    identifier: RequestId
    timestamp: MonotonicTime
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectTCPSocketClosed:
        ...



@event_class('Network.directTCPSocketChunkSent')
@dataclass
class DirectTCPSocketChunkSent:
    '''
    **EXPERIMENTAL**

    Fired when data is sent to tcp direct socket stream.
    '''
    identifier: RequestId
    data: str
    timestamp: MonotonicTime
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectTCPSocketChunkSent:
        ...



@event_class('Network.directTCPSocketChunkReceived')
@dataclass
class DirectTCPSocketChunkReceived:
    '''
    **EXPERIMENTAL**

    Fired when data is received from tcp direct socket stream.
    '''
    identifier: RequestId
    data: str
    timestamp: MonotonicTime
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectTCPSocketChunkReceived:
        ...



@event_class('Network.directUDPSocketJoinedMulticastGroup')
@dataclass
class DirectUDPSocketJoinedMulticastGroup:
    '''
    **EXPERIMENTAL**


    '''
    identifier: RequestId
    ip_address: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectUDPSocketJoinedMulticastGroup:
        ...



@event_class('Network.directUDPSocketLeftMulticastGroup')
@dataclass
class DirectUDPSocketLeftMulticastGroup:
    '''
    **EXPERIMENTAL**


    '''
    identifier: RequestId
    ip_address: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectUDPSocketLeftMulticastGroup:
        ...



@event_class('Network.directUDPSocketCreated')
@dataclass
class DirectUDPSocketCreated:
    '''
    **EXPERIMENTAL**

    Fired upon direct_socket.UDPSocket creation.
    '''
    identifier: RequestId
    options: DirectUDPSocketOptions
    timestamp: MonotonicTime
    initiator: typing.Optional[Initiator]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectUDPSocketCreated:
        ...



@event_class('Network.directUDPSocketOpened')
@dataclass
class DirectUDPSocketOpened:
    '''
    **EXPERIMENTAL**

    Fired when direct_socket.UDPSocket connection is opened.
    '''
    identifier: RequestId
    local_addr: str
    local_port: int
    timestamp: MonotonicTime
    remote_addr: typing.Optional[str]
    remote_port: typing.Optional[int]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectUDPSocketOpened:
        ...



@event_class('Network.directUDPSocketAborted')
@dataclass
class DirectUDPSocketAborted:
    '''
    **EXPERIMENTAL**

    Fired when direct_socket.UDPSocket is aborted.
    '''
    identifier: RequestId
    error_message: str
    timestamp: MonotonicTime
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectUDPSocketAborted:
        ...



@event_class('Network.directUDPSocketClosed')
@dataclass
class DirectUDPSocketClosed:
    '''
    **EXPERIMENTAL**

    Fired when direct_socket.UDPSocket is closed.
    '''
    identifier: RequestId
    timestamp: MonotonicTime
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectUDPSocketClosed:
        ...



@event_class('Network.directUDPSocketChunkSent')
@dataclass
class DirectUDPSocketChunkSent:
    '''
    **EXPERIMENTAL**

    Fired when message is sent to udp direct socket stream.
    '''
    identifier: RequestId
    message: DirectUDPMessage
    timestamp: MonotonicTime
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectUDPSocketChunkSent:
        ...



@event_class('Network.directUDPSocketChunkReceived')
@dataclass
class DirectUDPSocketChunkReceived:
    '''
    **EXPERIMENTAL**

    Fired when message is received from udp direct socket stream.
    '''
    identifier: RequestId
    message: DirectUDPMessage
    timestamp: MonotonicTime
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DirectUDPSocketChunkReceived:
        ...



@event_class('Network.requestWillBeSentExtraInfo')
@dataclass
class RequestWillBeSentExtraInfo:
    '''
    **EXPERIMENTAL**

    Fired when additional information about a requestWillBeSent event is available from the
    network stack. Not every requestWillBeSent event will have an additional
    requestWillBeSentExtraInfo fired for it, and there is no guarantee whether requestWillBeSent
    or requestWillBeSentExtraInfo will be fired first for the same request.
    '''
    request_id: RequestId
    associated_cookies: typing.List[AssociatedCookie]
    headers: Headers
    connect_timing: ConnectTiming
    device_bound_session_usages: typing.Optional[typing.List[DeviceBoundSessionWithUsage]]
    client_security_state: typing.Optional[ClientSecurityState]
    site_has_cookie_in_other_partition: typing.Optional[bool]
    applied_network_conditions_id: typing.Optional[str]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RequestWillBeSentExtraInfo:
        ...



@event_class('Network.responseReceivedExtraInfo')
@dataclass
class ResponseReceivedExtraInfo:
    '''
    **EXPERIMENTAL**

    Fired when additional information about a responseReceived event is available from the network
    stack. Not every responseReceived event will have an additional responseReceivedExtraInfo for
    it, and responseReceivedExtraInfo may be fired before or after responseReceived.
    '''
    request_id: RequestId
    blocked_cookies: typing.List[BlockedSetCookieWithReason]
    headers: Headers
    resource_ip_address_space: IPAddressSpace
    status_code: int
    headers_text: typing.Optional[str]
    cookie_partition_key: typing.Optional[CookiePartitionKey]
    cookie_partition_key_opaque: typing.Optional[bool]
    exempted_cookies: typing.Optional[typing.List[ExemptedSetCookieWithReason]]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ResponseReceivedExtraInfo:
        ...



@event_class('Network.responseReceivedEarlyHints')
@dataclass
class ResponseReceivedEarlyHints:
    '''
    **EXPERIMENTAL**

    Fired when 103 Early Hints headers is received in addition to the common response.
    Not every responseReceived event will have an responseReceivedEarlyHints fired.
    Only one responseReceivedEarlyHints may be fired for eached responseReceived event.
    '''
    request_id: RequestId
    headers: Headers
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ResponseReceivedEarlyHints:
        ...



@event_class('Network.trustTokenOperationDone')
@dataclass
class TrustTokenOperationDone:
    '''
    **EXPERIMENTAL**

    Fired exactly once for each Trust Token operation. Depending on
    the type of the operation and whether the operation succeeded or
    failed, the event is fired before the corresponding request was sent
    or after the response was received.
    '''
    status: str
    type_: TrustTokenOperationType
    request_id: RequestId
    top_level_origin: typing.Optional[str]
    issuer_origin: typing.Optional[str]
    issued_token_count: typing.Optional[int]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TrustTokenOperationDone:
        ...



@event_class('Network.policyUpdated')
@dataclass
class PolicyUpdated:
    '''
    **EXPERIMENTAL**

    Fired once security policy has been updated.
    '''
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PolicyUpdated:
        ...



@event_class('Network.reportingApiReportAdded')
@dataclass
class ReportingApiReportAdded:
    '''
    **EXPERIMENTAL**

    Is sent whenever a new report is added.
    And after 'enableReportingApi' for all existing reports.
    '''
    report: ReportingApiReport
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReportingApiReportAdded:
        ...



@event_class('Network.reportingApiReportUpdated')
@dataclass
class ReportingApiReportUpdated:
    '''
    **EXPERIMENTAL**


    '''
    report: ReportingApiReport
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReportingApiReportUpdated:
        ...



@event_class('Network.reportingApiEndpointsChangedForOrigin')
@dataclass
class ReportingApiEndpointsChangedForOrigin:
    '''
    **EXPERIMENTAL**


    '''
    origin: str
    endpoints: typing.List[ReportingApiEndpoint]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReportingApiEndpointsChangedForOrigin:
        ...



@event_class('Network.deviceBoundSessionsAdded')
@dataclass
class DeviceBoundSessionsAdded:
    '''
    **EXPERIMENTAL**

    Triggered when the initial set of device bound sessions is added.
    '''
    sessions: typing.List[DeviceBoundSession]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DeviceBoundSessionsAdded:
        ...



@event_class('Network.deviceBoundSessionEventOccurred')
@dataclass
class DeviceBoundSessionEventOccurred:
    '''
    **EXPERIMENTAL**

    Triggered when a device bound session event occurs.
    '''
    event_id: DeviceBoundSessionEventId
    site: str
    succeeded: bool
    session_id: typing.Optional[str]
    creation_event_details: typing.Optional[CreationEventDetails]
    refresh_event_details: typing.Optional[RefreshEventDetails]
    termination_event_details: typing.Optional[TerminationEventDetails]
    challenge_event_details: typing.Optional[ChallengeEventDetails]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DeviceBoundSessionEventOccurred:
        ...
