"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
from . import dom, page, runtime
from deprecated.sphinx import deprecated

@dataclass
class SourceOrderConfig:
    '''
    Configuration data for drawing the source order of an elements children.
    '''
    parent_outline_color: dom.RGBA
    child_outline_color: dom.RGBA
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SourceOrderConfig:
        ...



@dataclass
class GridHighlightConfig:
    '''
    Configuration data for the highlighting of Grid elements.
    '''
    show_grid_extension_lines: typing.Optional[bool] = ...
    show_positive_line_numbers: typing.Optional[bool] = ...
    show_negative_line_numbers: typing.Optional[bool] = ...
    show_area_names: typing.Optional[bool] = ...
    show_line_names: typing.Optional[bool] = ...
    show_track_sizes: typing.Optional[bool] = ...
    grid_border_color: typing.Optional[dom.RGBA] = ...
    cell_border_color: typing.Optional[dom.RGBA] = ...
    row_line_color: typing.Optional[dom.RGBA] = ...
    column_line_color: typing.Optional[dom.RGBA] = ...
    grid_border_dash: typing.Optional[bool] = ...
    cell_border_dash: typing.Optional[bool] = ...
    row_line_dash: typing.Optional[bool] = ...
    column_line_dash: typing.Optional[bool] = ...
    row_gap_color: typing.Optional[dom.RGBA] = ...
    row_hatch_color: typing.Optional[dom.RGBA] = ...
    column_gap_color: typing.Optional[dom.RGBA] = ...
    column_hatch_color: typing.Optional[dom.RGBA] = ...
    area_border_color: typing.Optional[dom.RGBA] = ...
    grid_background_color: typing.Optional[dom.RGBA] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> GridHighlightConfig:
        ...



@dataclass
class FlexContainerHighlightConfig:
    '''
    Configuration data for the highlighting of Flex container elements.
    '''
    container_border: typing.Optional[LineStyle] = ...
    line_separator: typing.Optional[LineStyle] = ...
    item_separator: typing.Optional[LineStyle] = ...
    main_distributed_space: typing.Optional[BoxStyle] = ...
    cross_distributed_space: typing.Optional[BoxStyle] = ...
    row_gap_space: typing.Optional[BoxStyle] = ...
    column_gap_space: typing.Optional[BoxStyle] = ...
    cross_alignment: typing.Optional[LineStyle] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> FlexContainerHighlightConfig:
        ...



@dataclass
class FlexItemHighlightConfig:
    '''
    Configuration data for the highlighting of Flex item elements.
    '''
    base_size_box: typing.Optional[BoxStyle] = ...
    base_size_border: typing.Optional[LineStyle] = ...
    flexibility_arrow: typing.Optional[LineStyle] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> FlexItemHighlightConfig:
        ...



@dataclass
class LineStyle:
    '''
    Style information for drawing a line.
    '''
    color: typing.Optional[dom.RGBA] = ...
    pattern: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> LineStyle:
        ...



@dataclass
class BoxStyle:
    '''
    Style information for drawing a box.
    '''
    fill_color: typing.Optional[dom.RGBA] = ...
    hatch_color: typing.Optional[dom.RGBA] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BoxStyle:
        ...



class ContrastAlgorithm(enum.Enum):
    AA = ...
    AAA = ...
    APCA = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ContrastAlgorithm:
        ...



@dataclass
class HighlightConfig:
    '''
    Configuration data for the highlighting of page elements.
    '''
    show_info: typing.Optional[bool] = ...
    show_styles: typing.Optional[bool] = ...
    show_rulers: typing.Optional[bool] = ...
    show_accessibility_info: typing.Optional[bool] = ...
    show_extension_lines: typing.Optional[bool] = ...
    content_color: typing.Optional[dom.RGBA] = ...
    padding_color: typing.Optional[dom.RGBA] = ...
    border_color: typing.Optional[dom.RGBA] = ...
    margin_color: typing.Optional[dom.RGBA] = ...
    event_target_color: typing.Optional[dom.RGBA] = ...
    shape_color: typing.Optional[dom.RGBA] = ...
    shape_margin_color: typing.Optional[dom.RGBA] = ...
    css_grid_color: typing.Optional[dom.RGBA] = ...
    color_format: typing.Optional[ColorFormat] = ...
    grid_highlight_config: typing.Optional[GridHighlightConfig] = ...
    flex_container_highlight_config: typing.Optional[FlexContainerHighlightConfig] = ...
    flex_item_highlight_config: typing.Optional[FlexItemHighlightConfig] = ...
    contrast_algorithm: typing.Optional[ContrastAlgorithm] = ...
    container_query_container_highlight_config: typing.Optional[ContainerQueryContainerHighlightConfig] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> HighlightConfig:
        ...



class ColorFormat(enum.Enum):
    RGB = ...
    HSL = ...
    HWB = ...
    HEX_ = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ColorFormat:
        ...



@dataclass
class GridNodeHighlightConfig:
    '''
    Configurations for Persistent Grid Highlight
    '''
    grid_highlight_config: GridHighlightConfig
    node_id: dom.NodeId
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> GridNodeHighlightConfig:
        ...



@dataclass
class FlexNodeHighlightConfig:
    flex_container_highlight_config: FlexContainerHighlightConfig
    node_id: dom.NodeId
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> FlexNodeHighlightConfig:
        ...



@dataclass
class ScrollSnapContainerHighlightConfig:
    snapport_border: typing.Optional[LineStyle] = ...
    snap_area_border: typing.Optional[LineStyle] = ...
    scroll_margin_color: typing.Optional[dom.RGBA] = ...
    scroll_padding_color: typing.Optional[dom.RGBA] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScrollSnapContainerHighlightConfig:
        ...



@dataclass
class ScrollSnapHighlightConfig:
    scroll_snap_container_highlight_config: ScrollSnapContainerHighlightConfig
    node_id: dom.NodeId
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScrollSnapHighlightConfig:
        ...



@dataclass
class HingeConfig:
    '''
    Configuration for dual screen hinge
    '''
    rect: dom.Rect
    content_color: typing.Optional[dom.RGBA] = ...
    outline_color: typing.Optional[dom.RGBA] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> HingeConfig:
        ...



@dataclass
class WindowControlsOverlayConfig:
    '''
    Configuration for Window Controls Overlay
    '''
    show_css: bool
    selected_platform: str
    theme_color: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WindowControlsOverlayConfig:
        ...



@dataclass
class ContainerQueryHighlightConfig:
    container_query_container_highlight_config: ContainerQueryContainerHighlightConfig
    node_id: dom.NodeId
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ContainerQueryHighlightConfig:
        ...



@dataclass
class ContainerQueryContainerHighlightConfig:
    container_border: typing.Optional[LineStyle] = ...
    descendant_border: typing.Optional[LineStyle] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ContainerQueryContainerHighlightConfig:
        ...



@dataclass
class IsolatedElementHighlightConfig:
    isolation_mode_highlight_config: IsolationModeHighlightConfig
    node_id: dom.NodeId
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> IsolatedElementHighlightConfig:
        ...



@dataclass
class IsolationModeHighlightConfig:
    resizer_color: typing.Optional[dom.RGBA] = ...
    resizer_handle_color: typing.Optional[dom.RGBA] = ...
    mask_color: typing.Optional[dom.RGBA] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> IsolationModeHighlightConfig:
        ...



class InspectMode(enum.Enum):
    SEARCH_FOR_NODE = ...
    SEARCH_FOR_UA_SHADOW_DOM = ...
    CAPTURE_AREA_SCREENSHOT = ...
    NONE = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> InspectMode:
        ...



@dataclass
class InspectedElementAnchorConfig:
    node_id: typing.Optional[dom.NodeId] = ...
    backend_node_id: typing.Optional[dom.BackendNodeId] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> InspectedElementAnchorConfig:
        ...



def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disables domain notifications.
    '''
    ...

def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables domain notifications.
    '''
    ...

def get_highlight_object_for_test(node_id: dom.NodeId, include_distance: typing.Optional[bool] = ..., include_style: typing.Optional[bool] = ..., color_format: typing.Optional[ColorFormat] = ..., show_accessibility_info: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, dict]:
    '''
    For testing.

    :param node_id: Id of the node to get highlight object for.
    :param include_distance: *(Optional)* Whether to include distance info.
    :param include_style: *(Optional)* Whether to include style info.
    :param color_format: *(Optional)* The color format to get config with (default: hex).
    :param show_accessibility_info: *(Optional)* Whether to show accessibility info (default: true).
    :returns: Highlight data for the node.
    '''
    ...

def get_grid_highlight_objects_for_test(node_ids: typing.List[dom.NodeId]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, dict]:
    '''
    For Persistent Grid testing.

    :param node_ids: Ids of the node to get highlight object for.
    :returns: Grid Highlight data for the node ids provided.
    '''
    ...

def get_source_order_highlight_object_for_test(node_id: dom.NodeId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, dict]:
    '''
    For Source Order Viewer testing.

    :param node_id: Id of the node to highlight.
    :returns: Source order highlight data for the node id provided.
    '''
    ...

def hide_highlight() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Hides any highlight.
    '''
    ...

@deprecated(version="1.3")
def highlight_frame(frame_id: page.FrameId, content_color: typing.Optional[dom.RGBA] = ..., content_outline_color: typing.Optional[dom.RGBA] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Highlights owner element of the frame with given id.
    Deprecated: Doesn't work reliably and cannot be fixed due to process
    separation (the owner node might be in a different process). Determine
    the owner node in the client and use highlightNode.

    .. deprecated:: 1.3

    :param frame_id: Identifier of the frame to highlight.
    :param content_color: *(Optional)* The content box highlight fill color (default: transparent).
    :param content_outline_color: *(Optional)* The content box highlight outline color (default: transparent).
    '''
    ...

def highlight_node(highlight_config: HighlightConfig, node_id: typing.Optional[dom.NodeId] = ..., backend_node_id: typing.Optional[dom.BackendNodeId] = ..., object_id: typing.Optional[runtime.RemoteObjectId] = ..., selector: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Highlights DOM node with given id or with the given JavaScript object wrapper. Either nodeId or
    objectId must be specified.

    :param highlight_config: A descriptor for the highlight appearance.
    :param node_id: *(Optional)* Identifier of the node to highlight.
    :param backend_node_id: *(Optional)* Identifier of the backend node to highlight.
    :param object_id: *(Optional)* JavaScript object id of the node to be highlighted.
    :param selector: *(Optional)* Selectors to highlight relevant nodes.
    '''
    ...

def highlight_quad(quad: dom.Quad, color: typing.Optional[dom.RGBA] = ..., outline_color: typing.Optional[dom.RGBA] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Highlights given quad. Coordinates are absolute with respect to the main frame viewport.

    :param quad: Quad to highlight
    :param color: *(Optional)* The highlight fill color (default: transparent).
    :param outline_color: *(Optional)* The highlight outline color (default: transparent).
    '''
    ...

def highlight_rect(x: int, y: int, width: int, height: int, color: typing.Optional[dom.RGBA] = ..., outline_color: typing.Optional[dom.RGBA] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Highlights given rectangle. Coordinates are absolute with respect to the main frame viewport.
    Issue: the method does not handle device pixel ratio (DPR) correctly.
    The coordinates currently have to be adjusted by the client
    if DPR is not 1 (see crbug.com/437807128).

    :param x: X coordinate
    :param y: Y coordinate
    :param width: Rectangle width
    :param height: Rectangle height
    :param color: *(Optional)* The highlight fill color (default: transparent).
    :param outline_color: *(Optional)* The highlight outline color (default: transparent).
    '''
    ...

def highlight_source_order(source_order_config: SourceOrderConfig, node_id: typing.Optional[dom.NodeId] = ..., backend_node_id: typing.Optional[dom.BackendNodeId] = ..., object_id: typing.Optional[runtime.RemoteObjectId] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Highlights the source order of the children of the DOM node with given id or with the given
    JavaScript object wrapper. Either nodeId or objectId must be specified.

    :param source_order_config: A descriptor for the appearance of the overlay drawing.
    :param node_id: *(Optional)* Identifier of the node to highlight.
    :param backend_node_id: *(Optional)* Identifier of the backend node to highlight.
    :param object_id: *(Optional)* JavaScript object id of the node to be highlighted.
    '''
    ...

def set_inspect_mode(mode: InspectMode, highlight_config: typing.Optional[HighlightConfig] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enters the 'inspect' mode. In this mode, elements that user is hovering over are highlighted.
    Backend then generates 'inspectNodeRequested' event upon element selection.

    :param mode: Set an inspection mode.
    :param highlight_config: *(Optional)* A descriptor for the highlight appearance of hovered-over nodes. May be omitted if ```enabled == false```.
    '''
    ...

def set_show_ad_highlights(show: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Highlights owner element of all frames detected to be ads.

    :param show: True for showing ad highlights
    '''
    ...

def set_paused_in_debugger_message(message: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param message: *(Optional)* The message to display, also triggers resume and step over controls.
    '''
    ...

def set_show_debug_borders(show: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Requests that backend shows debug borders on layers

    :param show: True for showing debug borders
    '''
    ...

def set_show_fps_counter(show: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Requests that backend shows the FPS counter

    :param show: True for showing the FPS counter
    '''
    ...

def set_show_grid_overlays(grid_node_highlight_configs: typing.List[GridNodeHighlightConfig]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Highlight multiple elements with the CSS Grid overlay.

    :param grid_node_highlight_configs: An array of node identifiers and descriptors for the highlight appearance.
    '''
    ...

def set_show_flex_overlays(flex_node_highlight_configs: typing.List[FlexNodeHighlightConfig]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param flex_node_highlight_configs: An array of node identifiers and descriptors for the highlight appearance.
    '''
    ...

def set_show_scroll_snap_overlays(scroll_snap_highlight_configs: typing.List[ScrollSnapHighlightConfig]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param scroll_snap_highlight_configs: An array of node identifiers and descriptors for the highlight appearance.
    '''
    ...

def set_show_container_query_overlays(container_query_highlight_configs: typing.List[ContainerQueryHighlightConfig]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param container_query_highlight_configs: An array of node identifiers and descriptors for the highlight appearance.
    '''
    ...

def set_show_inspected_element_anchor(inspected_element_anchor_config: InspectedElementAnchorConfig) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param inspected_element_anchor_config: Node identifier for which to show an anchor for.
    '''
    ...

def set_show_paint_rects(result: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Requests that backend shows paint rectangles

    :param result: True for showing paint rectangles
    '''
    ...

def set_show_layout_shift_regions(result: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Requests that backend shows layout shift regions

    :param result: True for showing layout shift regions
    '''
    ...

def set_show_scroll_bottleneck_rects(show: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Requests that backend shows scroll bottleneck rects

    :param show: True for showing scroll bottleneck rects
    '''
    ...

@deprecated(version="1.3")
def set_show_hit_test_borders(show: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Deprecated, no longer has any effect.

    .. deprecated:: 1.3

    :param show: True for showing hit-test borders
    '''
    ...

@deprecated(version="1.3")
def set_show_web_vitals(show: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Deprecated, no longer has any effect.

    .. deprecated:: 1.3

    :param show:
    '''
    ...

def set_show_viewport_size_on_resize(show: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Paints viewport size upon main frame resize.

    :param show: Whether to paint size or not.
    '''
    ...

def set_show_hinge(hinge_config: typing.Optional[HingeConfig] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Add a dual screen device hinge

    :param hinge_config: *(Optional)* hinge data, null means hideHinge
    '''
    ...

def set_show_isolated_elements(isolated_element_highlight_configs: typing.List[IsolatedElementHighlightConfig]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Show elements in isolation mode with overlays.

    :param isolated_element_highlight_configs: An array of node identifiers and descriptors for the highlight appearance.
    '''
    ...

def set_show_window_controls_overlay(window_controls_overlay_config: typing.Optional[WindowControlsOverlayConfig] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Show Window Controls Overlay for PWA

    :param window_controls_overlay_config: *(Optional)* Window Controls Overlay data, null means hide Window Controls Overlay
    '''
    ...

@event_class('Overlay.inspectNodeRequested')
@dataclass
class InspectNodeRequested:
    '''
    Fired when the node should be inspected. This happens after call to ``setInspectMode`` or when
    user manually inspects an element.
    '''
    backend_node_id: dom.BackendNodeId
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> InspectNodeRequested:
        ...



@event_class('Overlay.nodeHighlightRequested')
@dataclass
class NodeHighlightRequested:
    '''
    Fired when the node should be highlighted. This happens after call to ``setInspectMode``.
    '''
    node_id: dom.NodeId
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> NodeHighlightRequested:
        ...



@event_class('Overlay.screenshotRequested')
@dataclass
class ScreenshotRequested:
    '''
    Fired when user asks to capture screenshot of some area on the page.
    '''
    viewport: page.Viewport
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScreenshotRequested:
        ...



@event_class('Overlay.inspectPanelShowRequested')
@dataclass
class InspectPanelShowRequested:
    '''
    Fired when user asks to show the Inspect panel.
    '''
    backend_node_id: dom.BackendNodeId
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> InspectPanelShowRequested:
        ...



@event_class('Overlay.inspectedElementWindowRestored')
@dataclass
class InspectedElementWindowRestored:
    '''
    Fired when user asks to restore the Inspected Element floating window.
    '''
    backend_node_id: dom.BackendNodeId
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> InspectedElementWindowRestored:
        ...



@event_class('Overlay.inspectModeCanceled')
@dataclass
class InspectModeCanceled:
    '''
    Fired when user cancels the inspect mode.
    '''
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> InspectModeCanceled:
        ...
