"""
This type stub file was generated by pyright.
"""

import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
from deprecated.sphinx import deprecated

@dataclass
class Metric:
    '''
    Run-time execution metric.
    '''
    name: str
    value: float
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Metric:
        ...



def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disable collecting and reporting metrics.
    '''
    ...

def enable(time_domain: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enable collecting and reporting metrics.

    :param time_domain: *(Optional)* Time domain to use for collecting and reporting duration metrics.
    '''
    ...

@deprecated(version="1.3")
def set_time_domain(time_domain: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets time domain to use for collecting and reporting duration metrics.
    Note that this must be called before enabling metrics collection. Calling
    this method while metrics collection is enabled returns an error.

    .. deprecated:: 1.3

    **EXPERIMENTAL**

    :param time_domain: Time domain
    '''
    ...

def get_metrics() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[Metric]]:
    '''
    Retrieve current values of run-time metrics.

    :returns: Current values for run-time metrics.
    '''
    ...

@event_class('Performance.metrics')
@dataclass
class Metrics:
    '''
    Current values of the metrics.
    '''
    metrics: typing.List[Metric]
    title: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Metrics:
        ...
