"""
This type stub file was generated by pyright.
"""

import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
from . import debugger, runtime

@dataclass
class ProfileNode:
    '''
    Profile node. Holds callsite information, execution statistics and child nodes.
    '''
    id_: int
    call_frame: runtime.CallFrame
    hit_count: typing.Optional[int] = ...
    children: typing.Optional[typing.List[int]] = ...
    deopt_reason: typing.Optional[str] = ...
    position_ticks: typing.Optional[typing.List[PositionTickInfo]] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ProfileNode:
        ...



@dataclass
class Profile:
    '''
    Profile.
    '''
    nodes: typing.List[ProfileNode]
    start_time: float
    end_time: float
    samples: typing.Optional[typing.List[int]] = ...
    time_deltas: typing.Optional[typing.List[int]] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Profile:
        ...



@dataclass
class PositionTickInfo:
    '''
    Specifies a number of samples attributed to a certain source position.
    '''
    line: int
    ticks: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PositionTickInfo:
        ...



@dataclass
class CoverageRange:
    '''
    Coverage data for a source range.
    '''
    start_offset: int
    end_offset: int
    count: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CoverageRange:
        ...



@dataclass
class FunctionCoverage:
    '''
    Coverage data for a JavaScript function.
    '''
    function_name: str
    ranges: typing.List[CoverageRange]
    is_block_coverage: bool
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> FunctionCoverage:
        ...



@dataclass
class ScriptCoverage:
    '''
    Coverage data for a JavaScript script.
    '''
    script_id: runtime.ScriptId
    url: str
    functions: typing.List[FunctionCoverage]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ScriptCoverage:
        ...



def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ...

def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ...

def get_best_effort_coverage() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[ScriptCoverage]]:
    '''
    Collect coverage data for the current isolate. The coverage data may be incomplete due to
    garbage collection.

    :returns: Coverage data for the current isolate.
    '''
    ...

def set_sampling_interval(interval: int) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Changes CPU profiler sampling interval. Must be called before CPU profiles recording started.

    :param interval: New sampling interval in microseconds.
    '''
    ...

def start() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ...

def start_precise_coverage(call_count: typing.Optional[bool] = ..., detailed: typing.Optional[bool] = ..., allow_triggered_updates: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, float]:
    '''
    Enable precise code coverage. Coverage data for JavaScript executed before enabling precise code
    coverage may be incomplete. Enabling prevents running optimized code and resets execution
    counters.

    :param call_count: *(Optional)* Collect accurate call counts beyond simple 'covered' or 'not covered'.
    :param detailed: *(Optional)* Collect block-based coverage.
    :param allow_triggered_updates: *(Optional)* Allow the backend to send updates on its own initiative
    :returns: Monotonically increasing time (in seconds) when the coverage update was taken in the backend.
    '''
    ...

def stop() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, Profile]:
    '''


    :returns: Recorded profile.
    '''
    ...

def stop_precise_coverage() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disable precise code coverage. Disabling releases unnecessary execution count records and allows
    executing optimized code.
    '''
    ...

def take_precise_coverage() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[typing.List[ScriptCoverage], float]]:
    '''
    Collect coverage data for the current isolate, and resets execution counters. Precise code
    coverage needs to have started.

    :returns: A tuple with the following items:

        0. **result** - Coverage data for the current isolate.
        1. **timestamp** - Monotonically increasing time (in seconds) when the coverage update was taken in the backend.
    '''
    ...

@event_class('Profiler.consoleProfileFinished')
@dataclass
class ConsoleProfileFinished:
    id_: str
    location: debugger.Location
    profile: Profile
    title: typing.Optional[str]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ConsoleProfileFinished:
        ...



@event_class('Profiler.consoleProfileStarted')
@dataclass
class ConsoleProfileStarted:
    '''
    Sent when new profile recording is started using console.profile() call.
    '''
    id_: str
    location: debugger.Location
    title: typing.Optional[str]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ConsoleProfileStarted:
        ...



@event_class('Profiler.preciseCoverageDeltaUpdate')
@dataclass
class PreciseCoverageDeltaUpdate:
    '''
    **EXPERIMENTAL**

    Reports coverage delta since the last poll (either from an event like this, or from
    ``takePreciseCoverage`` for the current isolate. May only be sent if precise code
    coverage has been started. This event can be trigged by the embedder to, for example,
    trigger collection of coverage data immediately at a certain point in time.
    '''
    timestamp: float
    occasion: str
    result: typing.List[ScriptCoverage]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PreciseCoverageDeltaUpdate:
        ...
