"""
This type stub file was generated by pyright.
"""

import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class

class ScriptId(str):
    '''
    Unique script identifier.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ScriptId:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class SerializationOptions:
    '''
    Represents options for serialization. Overrides ``generatePreview`` and ``returnByValue``.
    '''
    serialization: str
    max_depth: typing.Optional[int] = ...
    additional_parameters: typing.Optional[dict] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SerializationOptions:
        ...



@dataclass
class DeepSerializedValue:
    '''
    Represents deep serialized value.
    '''
    type_: str
    value: typing.Optional[typing.Any] = ...
    object_id: typing.Optional[str] = ...
    weak_local_object_reference: typing.Optional[int] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DeepSerializedValue:
        ...



class RemoteObjectId(str):
    '''
    Unique object identifier.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> RemoteObjectId:
        ...

    def __repr__(self) -> str:
        ...



class UnserializableValue(str):
    '''
    Primitive value which cannot be JSON-stringified. Includes values ``-0``, ``NaN``, ``Infinity``,
    ``-Infinity``, and bigint literals.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> UnserializableValue:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class RemoteObject:
    '''
    Mirror object referencing original JavaScript object.
    '''
    type_: str
    subtype: typing.Optional[str] = ...
    class_name: typing.Optional[str] = ...
    value: typing.Optional[typing.Any] = ...
    unserializable_value: typing.Optional[UnserializableValue] = ...
    description: typing.Optional[str] = ...
    deep_serialized_value: typing.Optional[DeepSerializedValue] = ...
    object_id: typing.Optional[RemoteObjectId] = ...
    preview: typing.Optional[ObjectPreview] = ...
    custom_preview: typing.Optional[CustomPreview] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RemoteObject:
        ...



@dataclass
class CustomPreview:
    header: str
    body_getter_id: typing.Optional[RemoteObjectId] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CustomPreview:
        ...



@dataclass
class ObjectPreview:
    '''
    Object containing abbreviated remote object value.
    '''
    type_: str
    overflow: bool
    properties: typing.List[PropertyPreview]
    subtype: typing.Optional[str] = ...
    description: typing.Optional[str] = ...
    entries: typing.Optional[typing.List[EntryPreview]] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ObjectPreview:
        ...



@dataclass
class PropertyPreview:
    name: str
    type_: str
    value: typing.Optional[str] = ...
    value_preview: typing.Optional[ObjectPreview] = ...
    subtype: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PropertyPreview:
        ...



@dataclass
class EntryPreview:
    value: ObjectPreview
    key: typing.Optional[ObjectPreview] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> EntryPreview:
        ...



@dataclass
class PropertyDescriptor:
    '''
    Object property descriptor.
    '''
    name: str
    configurable: bool
    enumerable: bool
    value: typing.Optional[RemoteObject] = ...
    writable: typing.Optional[bool] = ...
    get: typing.Optional[RemoteObject] = ...
    set_: typing.Optional[RemoteObject] = ...
    was_thrown: typing.Optional[bool] = ...
    is_own: typing.Optional[bool] = ...
    symbol: typing.Optional[RemoteObject] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PropertyDescriptor:
        ...



@dataclass
class InternalPropertyDescriptor:
    '''
    Object internal property descriptor. This property isn't normally visible in JavaScript code.
    '''
    name: str
    value: typing.Optional[RemoteObject] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> InternalPropertyDescriptor:
        ...



@dataclass
class PrivatePropertyDescriptor:
    '''
    Object private field descriptor.
    '''
    name: str
    value: typing.Optional[RemoteObject] = ...
    get: typing.Optional[RemoteObject] = ...
    set_: typing.Optional[RemoteObject] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> PrivatePropertyDescriptor:
        ...



@dataclass
class CallArgument:
    '''
    Represents function call argument. Either remote object id ``objectId``, primitive ``value``,
    unserializable primitive value or neither of (for undefined) them should be specified.
    '''
    value: typing.Optional[typing.Any] = ...
    unserializable_value: typing.Optional[UnserializableValue] = ...
    object_id: typing.Optional[RemoteObjectId] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CallArgument:
        ...



class ExecutionContextId(int):
    '''
    Id of an execution context.
    '''
    def to_json(self) -> int:
        ...

    @classmethod
    def from_json(cls, json: int) -> ExecutionContextId:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class ExecutionContextDescription:
    '''
    Description of an isolated world.
    '''
    id_: ExecutionContextId
    origin: str
    name: str
    unique_id: str
    aux_data: typing.Optional[dict] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ExecutionContextDescription:
        ...



@dataclass
class ExceptionDetails:
    '''
    Detailed information about exception (or error) that was thrown during script compilation or
    execution.
    '''
    exception_id: int
    text: str
    line_number: int
    column_number: int
    script_id: typing.Optional[ScriptId] = ...
    url: typing.Optional[str] = ...
    stack_trace: typing.Optional[StackTrace] = ...
    exception: typing.Optional[RemoteObject] = ...
    execution_context_id: typing.Optional[ExecutionContextId] = ...
    exception_meta_data: typing.Optional[dict] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ExceptionDetails:
        ...



class Timestamp(float):
    '''
    Number of milliseconds since epoch.
    '''
    def to_json(self) -> float:
        ...

    @classmethod
    def from_json(cls, json: float) -> Timestamp:
        ...

    def __repr__(self) -> str:
        ...



class TimeDelta(float):
    '''
    Number of milliseconds.
    '''
    def to_json(self) -> float:
        ...

    @classmethod
    def from_json(cls, json: float) -> TimeDelta:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class CallFrame:
    '''
    Stack entry for runtime errors and assertions.
    '''
    function_name: str
    script_id: ScriptId
    url: str
    line_number: int
    column_number: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CallFrame:
        ...



@dataclass
class StackTrace:
    '''
    Call frames for assertions or error messages.
    '''
    call_frames: typing.List[CallFrame]
    description: typing.Optional[str] = ...
    parent: typing.Optional[StackTrace] = ...
    parent_id: typing.Optional[StackTraceId] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StackTrace:
        ...



class UniqueDebuggerId(str):
    '''
    Unique identifier of current debugger.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> UniqueDebuggerId:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class StackTraceId:
    '''
    If ``debuggerId`` is set stack trace comes from another debugger and can be resolved there. This
    allows to track cross-debugger calls. See ``Runtime.StackTrace`` and ``Debugger.paused`` for usages.
    '''
    id_: str
    debugger_id: typing.Optional[UniqueDebuggerId] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StackTraceId:
        ...



def await_promise(promise_object_id: RemoteObjectId, return_by_value: typing.Optional[bool] = ..., generate_preview: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[RemoteObject, typing.Optional[ExceptionDetails]]]:
    '''
    Add handler to promise with given promise object id.

    :param promise_object_id: Identifier of the promise.
    :param return_by_value: *(Optional)* Whether the result is expected to be a JSON object that should be sent by value.
    :param generate_preview: *(Optional)* Whether preview should be generated for the result.
    :returns: A tuple with the following items:

        0. **result** - Promise result. Will contain rejected value if promise was rejected.
        1. **exceptionDetails** - *(Optional)* Exception details if stack strace is available.
    '''
    ...

def call_function_on(function_declaration: str, object_id: typing.Optional[RemoteObjectId] = ..., arguments: typing.Optional[typing.List[CallArgument]] = ..., silent: typing.Optional[bool] = ..., return_by_value: typing.Optional[bool] = ..., generate_preview: typing.Optional[bool] = ..., user_gesture: typing.Optional[bool] = ..., await_promise: typing.Optional[bool] = ..., execution_context_id: typing.Optional[ExecutionContextId] = ..., object_group: typing.Optional[str] = ..., throw_on_side_effect: typing.Optional[bool] = ..., unique_context_id: typing.Optional[str] = ..., serialization_options: typing.Optional[SerializationOptions] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[RemoteObject, typing.Optional[ExceptionDetails]]]:
    '''
    Calls function with given declaration on the given object. Object group of the result is
    inherited from the target object.

    :param function_declaration: Declaration of the function to call.
    :param object_id: *(Optional)* Identifier of the object to call function on. Either objectId or executionContextId should be specified.
    :param arguments: *(Optional)* Call arguments. All call arguments must belong to the same JavaScript world as the target object.
    :param silent: *(Optional)* In silent mode exceptions thrown during evaluation are not reported and do not pause execution. Overrides ```setPauseOnException```` state.
    :param return_by_value: *(Optional)* Whether the result is expected to be a JSON object which should be sent by value. Can be overriden by ````serializationOptions````.
    :param generate_preview: **(EXPERIMENTAL)** *(Optional)* Whether preview should be generated for the result.
    :param user_gesture: *(Optional)* Whether execution should be treated as initiated by user in the UI.
    :param await_promise: *(Optional)* Whether execution should ````await```` for resulting value and return once awaited promise is resolved.
    :param execution_context_id: *(Optional)* Specifies execution context which global object will be used to call function on. Either executionContextId or objectId should be specified.
    :param object_group: *(Optional)* Symbolic group name that can be used to release multiple objects. If objectGroup is not specified and objectId is, objectGroup will be inherited from object.
    :param throw_on_side_effect: **(EXPERIMENTAL)** *(Optional)* Whether to throw an exception if side effect cannot be ruled out during evaluation.
    :param unique_context_id: **(EXPERIMENTAL)** *(Optional)* An alternative way to specify the execution context to call function on. Compared to contextId that may be reused across processes, this is guaranteed to be system-unique, so it can be used to prevent accidental function call in context different than intended (e.g. as a result of navigation across process boundaries). This is mutually exclusive with ````executionContextId````.
    :param serialization_options: **(EXPERIMENTAL)** *(Optional)* Specifies the result serialization. If provided, overrides ````generatePreview```` and ````returnByValue```.
    :returns: A tuple with the following items:

        0. **result** - Call result.
        1. **exceptionDetails** - *(Optional)* Exception details.
    '''
    ...

def compile_script(expression: str, source_url: str, persist_script: bool, execution_context_id: typing.Optional[ExecutionContextId] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[typing.Optional[ScriptId], typing.Optional[ExceptionDetails]]]:
    '''
    Compiles expression.

    :param expression: Expression to compile.
    :param source_url: Source url to be set for the script.
    :param persist_script: Specifies whether the compiled script should be persisted.
    :param execution_context_id: *(Optional)* Specifies in which execution context to perform script run. If the parameter is omitted the evaluation will be performed in the context of the inspected page.
    :returns: A tuple with the following items:

        0. **scriptId** - *(Optional)* Id of the script.
        1. **exceptionDetails** - *(Optional)* Exception details.
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disables reporting of execution contexts creation.
    '''
    ...

def discard_console_entries() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Discards collected exceptions and console API calls.
    '''
    ...

def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables reporting of execution contexts creation by means of ``executionContextCreated`` event.
    When the reporting gets enabled the event will be sent immediately for each existing execution
    context.
    '''
    ...

def evaluate(expression: str, object_group: typing.Optional[str] = ..., include_command_line_api: typing.Optional[bool] = ..., silent: typing.Optional[bool] = ..., context_id: typing.Optional[ExecutionContextId] = ..., return_by_value: typing.Optional[bool] = ..., generate_preview: typing.Optional[bool] = ..., user_gesture: typing.Optional[bool] = ..., await_promise: typing.Optional[bool] = ..., throw_on_side_effect: typing.Optional[bool] = ..., timeout: typing.Optional[TimeDelta] = ..., disable_breaks: typing.Optional[bool] = ..., repl_mode: typing.Optional[bool] = ..., allow_unsafe_eval_blocked_by_csp: typing.Optional[bool] = ..., unique_context_id: typing.Optional[str] = ..., serialization_options: typing.Optional[SerializationOptions] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[RemoteObject, typing.Optional[ExceptionDetails]]]:
    '''
    Evaluates expression on global object.

    :param expression: Expression to evaluate.
    :param object_group: *(Optional)* Symbolic group name that can be used to release multiple objects.
    :param include_command_line_api: *(Optional)* Determines whether Command Line API should be available during the evaluation.
    :param silent: *(Optional)* In silent mode exceptions thrown during evaluation are not reported and do not pause execution. Overrides ```setPauseOnException```` state.
    :param context_id: *(Optional)* Specifies in which execution context to perform evaluation. If the parameter is omitted the evaluation will be performed in the context of the inspected page. This is mutually exclusive with ````uniqueContextId````, which offers an alternative way to identify the execution context that is more reliable in a multi-process environment.
    :param return_by_value: *(Optional)* Whether the result is expected to be a JSON object that should be sent by value.
    :param generate_preview: **(EXPERIMENTAL)** *(Optional)* Whether preview should be generated for the result.
    :param user_gesture: *(Optional)* Whether execution should be treated as initiated by user in the UI.
    :param await_promise: *(Optional)* Whether execution should ````await```` for resulting value and return once awaited promise is resolved.
    :param throw_on_side_effect: **(EXPERIMENTAL)** *(Optional)* Whether to throw an exception if side effect cannot be ruled out during evaluation. This implies ````disableBreaks```` below.
    :param timeout: **(EXPERIMENTAL)** *(Optional)* Terminate execution after timing out (number of milliseconds).
    :param disable_breaks: **(EXPERIMENTAL)** *(Optional)* Disable breakpoints during execution.
    :param repl_mode: **(EXPERIMENTAL)** *(Optional)* Setting this flag to true enables ````let```` re-declaration and top-level ````await````. Note that ````let```` variables can only be re-declared if they originate from ````replMode```` themselves.
    :param allow_unsafe_eval_blocked_by_csp: **(EXPERIMENTAL)** *(Optional)* The Content Security Policy (CSP) for the target might block 'unsafe-eval' which includes eval(), Function(), setTimeout() and setInterval() when called with non-callable arguments. This flag bypasses CSP for this evaluation and allows unsafe-eval. Defaults to true.
    :param unique_context_id: **(EXPERIMENTAL)** *(Optional)* An alternative way to specify the execution context to evaluate in. Compared to contextId that may be reused across processes, this is guaranteed to be system-unique, so it can be used to prevent accidental evaluation of the expression in context different than intended (e.g. as a result of navigation across process boundaries). This is mutually exclusive with ````contextId````.
    :param serialization_options: **(EXPERIMENTAL)** *(Optional)* Specifies the result serialization. If provided, overrides ````generatePreview```` and ````returnByValue```.
    :returns: A tuple with the following items:

        0. **result** - Evaluation result.
        1. **exceptionDetails** - *(Optional)* Exception details.
    '''
    ...

def get_isolate_id() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, str]:
    '''
    Returns the isolate id.

    **EXPERIMENTAL**

    :returns: The isolate id.
    '''
    ...

def get_heap_usage() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[float, float, float, float]]:
    '''
    Returns the JavaScript heap usage.
    It is the total usage of the corresponding isolate not scoped to a particular Runtime.

    **EXPERIMENTAL**

    :returns: A tuple with the following items:

        0. **usedSize** - Used JavaScript heap size in bytes.
        1. **totalSize** - Allocated JavaScript heap size in bytes.
        2. **embedderHeapUsedSize** - Used size in bytes in the embedder's garbage-collected heap.
        3. **backingStorageSize** - Size in bytes of backing storage for array buffers and external strings.
    '''
    ...

def get_properties(object_id: RemoteObjectId, own_properties: typing.Optional[bool] = ..., accessor_properties_only: typing.Optional[bool] = ..., generate_preview: typing.Optional[bool] = ..., non_indexed_properties_only: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[typing.List[PropertyDescriptor], typing.Optional[typing.List[InternalPropertyDescriptor]], typing.Optional[typing.List[PrivatePropertyDescriptor]], typing.Optional[ExceptionDetails]]]:
    '''
    Returns properties of a given object. Object group of the result is inherited from the target
    object.

    :param object_id: Identifier of the object to return properties for.
    :param own_properties: *(Optional)* If true, returns properties belonging only to the element itself, not to its prototype chain.
    :param accessor_properties_only: **(EXPERIMENTAL)** *(Optional)* If true, returns accessor properties (with getter/setter) only; internal properties are not returned either.
    :param generate_preview: **(EXPERIMENTAL)** *(Optional)* Whether preview should be generated for the results.
    :param non_indexed_properties_only: **(EXPERIMENTAL)** *(Optional)* If true, returns non-indexed properties only.
    :returns: A tuple with the following items:

        0. **result** - Object properties.
        1. **internalProperties** - *(Optional)* Internal object properties (only of the element itself).
        2. **privateProperties** - *(Optional)* Object private properties.
        3. **exceptionDetails** - *(Optional)* Exception details.
    '''
    ...

def global_lexical_scope_names(execution_context_id: typing.Optional[ExecutionContextId] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[str]]:
    '''
    Returns all let, const and class variables from global scope.

    :param execution_context_id: *(Optional)* Specifies in which execution context to lookup global scope variables.
    :returns:
    '''
    ...

def query_objects(prototype_object_id: RemoteObjectId, object_group: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, RemoteObject]:
    '''
    :param prototype_object_id: Identifier of the prototype to return objects for.
    :param object_group: *(Optional)* Symbolic group name that can be used to release the results.
    :returns: Array with objects.
    '''
    ...

def release_object(object_id: RemoteObjectId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Releases remote object with given id.

    :param object_id: Identifier of the object to release.
    '''
    ...

def release_object_group(object_group: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Releases all remote objects that belong to a given group.

    :param object_group: Symbolic object group name.
    '''
    ...

def run_if_waiting_for_debugger() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Tells inspected instance to run if it was waiting for debugger to attach.
    '''
    ...

def run_script(script_id: ScriptId, execution_context_id: typing.Optional[ExecutionContextId] = ..., object_group: typing.Optional[str] = ..., silent: typing.Optional[bool] = ..., include_command_line_api: typing.Optional[bool] = ..., return_by_value: typing.Optional[bool] = ..., generate_preview: typing.Optional[bool] = ..., await_promise: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[RemoteObject, typing.Optional[ExceptionDetails]]]:
    '''
    Runs script with given id in a given context.

    :param script_id: Id of the script to run.
    :param execution_context_id: *(Optional)* Specifies in which execution context to perform script run. If the parameter is omitted the evaluation will be performed in the context of the inspected page.
    :param object_group: *(Optional)* Symbolic group name that can be used to release multiple objects.
    :param silent: *(Optional)* In silent mode exceptions thrown during evaluation are not reported and do not pause execution. Overrides ```setPauseOnException```` state.
    :param include_command_line_api: *(Optional)* Determines whether Command Line API should be available during the evaluation.
    :param return_by_value: *(Optional)* Whether the result is expected to be a JSON object which should be sent by value.
    :param generate_preview: *(Optional)* Whether preview should be generated for the result.
    :param await_promise: *(Optional)* Whether execution should ````await``` for resulting value and return once awaited promise is resolved.
    :returns: A tuple with the following items:

        0. **result** - Run result.
        1. **exceptionDetails** - *(Optional)* Exception details.
    '''
    ...

def set_async_call_stack_depth(max_depth: int) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables or disables async call stacks tracking.

    :param max_depth: Maximum depth of async call stacks. Setting to ```0``` will effectively disable collecting async call stacks (default).
    '''
    ...

def set_custom_object_formatter_enabled(enabled: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''


    **EXPERIMENTAL**

    :param enabled:
    '''
    ...

def set_max_call_stack_size_to_capture(size: int) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''


    **EXPERIMENTAL**

    :param size:
    '''
    ...

def terminate_execution() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Terminate current or next JavaScript execution.
    Will cancel the termination when the outer-most script execution ends.

    **EXPERIMENTAL**
    '''
    ...

def add_binding(name: str, execution_context_id: typing.Optional[ExecutionContextId] = ..., execution_context_name: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    If executionContextId is empty, adds binding with the given name on the
    global objects of all inspected contexts, including those created later,
    bindings survive reloads.
    Binding function takes exactly one argument, this argument should be string,
    in case of any other input, function throws an exception.
    Each binding function call produces Runtime.bindingCalled notification.

    :param name:
    :param execution_context_id: **(DEPRECATED)** **(EXPERIMENTAL)** *(Optional)* If specified, the binding would only be exposed to the specified execution context. If omitted and ```executionContextName```` is not set, the binding is exposed to all execution contexts of the target. This parameter is mutually exclusive with ````executionContextName````. Deprecated in favor of ````executionContextName```` due to an unclear use case and bugs in implementation (crbug.com/1169639). ````executionContextId```` will be removed in the future.
    :param execution_context_name: *(Optional)* If specified, the binding is exposed to the executionContext with matching name, even for contexts created after the binding is added. See also ````ExecutionContext.name```` and ````worldName```` parameter to ````Page.addScriptToEvaluateOnNewDocument````. This parameter is mutually exclusive with ````executionContextId```.
    '''
    ...

def remove_binding(name: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    This method does not remove binding function from global object but
    unsubscribes current runtime agent from Runtime.bindingCalled notifications.

    :param name:
    '''
    ...

def get_exception_details(error_object_id: RemoteObjectId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Optional[ExceptionDetails]]:
    '''
    This method tries to lookup and populate exception details for a
    JavaScript Error object.
    Note that the stackTrace portion of the resulting exceptionDetails will
    only be populated if the Runtime domain was enabled at the time when the
    Error was thrown.

    **EXPERIMENTAL**

    :param error_object_id: The error object for which to resolve the exception details.
    :returns:
    '''
    ...

@event_class('Runtime.bindingCalled')
@dataclass
class BindingCalled:
    '''
    **EXPERIMENTAL**

    Notification is issued every time when binding is called.
    '''
    name: str
    payload: str
    execution_context_id: ExecutionContextId
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BindingCalled:
        ...



@event_class('Runtime.consoleAPICalled')
@dataclass
class ConsoleAPICalled:
    '''
    Issued when console API was called.
    '''
    type_: str
    args: typing.List[RemoteObject]
    execution_context_id: ExecutionContextId
    timestamp: Timestamp
    stack_trace: typing.Optional[StackTrace]
    context: typing.Optional[str]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ConsoleAPICalled:
        ...



@event_class('Runtime.exceptionRevoked')
@dataclass
class ExceptionRevoked:
    '''
    Issued when unhandled exception was revoked.
    '''
    reason: str
    exception_id: int
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ExceptionRevoked:
        ...



@event_class('Runtime.exceptionThrown')
@dataclass
class ExceptionThrown:
    '''
    Issued when exception was thrown and unhandled.
    '''
    timestamp: Timestamp
    exception_details: ExceptionDetails
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ExceptionThrown:
        ...



@event_class('Runtime.executionContextCreated')
@dataclass
class ExecutionContextCreated:
    '''
    Issued when new execution context is created.
    '''
    context: ExecutionContextDescription
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ExecutionContextCreated:
        ...



@event_class('Runtime.executionContextDestroyed')
@dataclass
class ExecutionContextDestroyed:
    '''
    Issued when execution context is destroyed.
    '''
    execution_context_id: ExecutionContextId
    execution_context_unique_id: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ExecutionContextDestroyed:
        ...



@event_class('Runtime.executionContextsCleared')
@dataclass
class ExecutionContextsCleared:
    '''
    Issued when all executionContexts were cleared in browser
    '''
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ExecutionContextsCleared:
        ...



@event_class('Runtime.inspectRequested')
@dataclass
class InspectRequested:
    '''
    Issued when object should be inspected (for example, as a result of inspect() command line API
    call).
    '''
    object_: RemoteObject
    hints: dict
    execution_context_id: typing.Optional[ExecutionContextId]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> InspectRequested:
        ...
