"""
This type stub file was generated by pyright.
"""

import typing
from dataclasses import dataclass
from .util import T_JSON_DICT

@dataclass
class Domain:
    '''
    Description of the protocol domain.
    '''
    name: str
    version: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Domain:
        ...



def get_domains() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[Domain]]:
    '''
    Returns supported domains.

    :returns: List of supported domains.
    '''
    ...
