"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
from . import target

class RegistrationID(str):
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> RegistrationID:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class ServiceWorkerRegistration:
    '''
    ServiceWorker registration.
    '''
    registration_id: RegistrationID
    scope_url: str
    is_deleted: bool
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ServiceWorkerRegistration:
        ...



class ServiceWorkerVersionRunningStatus(enum.Enum):
    STOPPED = ...
    STARTING = ...
    RUNNING = ...
    STOPPING = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ServiceWorkerVersionRunningStatus:
        ...



class ServiceWorkerVersionStatus(enum.Enum):
    NEW = ...
    INSTALLING = ...
    INSTALLED = ...
    ACTIVATING = ...
    ACTIVATED = ...
    REDUNDANT = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ServiceWorkerVersionStatus:
        ...



@dataclass
class ServiceWorkerVersion:
    '''
    ServiceWorker version.
    '''
    version_id: str
    registration_id: RegistrationID
    script_url: str
    running_status: ServiceWorkerVersionRunningStatus
    status: ServiceWorkerVersionStatus
    script_last_modified: typing.Optional[float] = ...
    script_response_time: typing.Optional[float] = ...
    controlled_clients: typing.Optional[typing.List[target.TargetID]] = ...
    target_id: typing.Optional[target.TargetID] = ...
    router_rules: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ServiceWorkerVersion:
        ...



@dataclass
class ServiceWorkerErrorMessage:
    '''
    ServiceWorker error message.
    '''
    error_message: str
    registration_id: RegistrationID
    version_id: str
    source_url: str
    line_number: int
    column_number: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ServiceWorkerErrorMessage:
        ...



def deliver_push_message(origin: str, registration_id: RegistrationID, data: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param origin:
    :param registration_id:
    :param data:
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ...

def dispatch_sync_event(origin: str, registration_id: RegistrationID, tag: str, last_chance: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param origin:
    :param registration_id:
    :param tag:
    :param last_chance:
    '''
    ...

def dispatch_periodic_sync_event(origin: str, registration_id: RegistrationID, tag: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param origin:
    :param registration_id:
    :param tag:
    '''
    ...

def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ...

def set_force_update_on_page_load(force_update_on_page_load: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param force_update_on_page_load:
    '''
    ...

def skip_waiting(scope_url: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param scope_url:
    '''
    ...

def start_worker(scope_url: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param scope_url:
    '''
    ...

def stop_all_workers() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    ...

def stop_worker(version_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param version_id:
    '''
    ...

def unregister(scope_url: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param scope_url:
    '''
    ...

def update_registration(scope_url: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param scope_url:
    '''
    ...

@event_class('ServiceWorker.workerErrorReported')
@dataclass
class WorkerErrorReported:
    error_message: ServiceWorkerErrorMessage
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WorkerErrorReported:
        ...



@event_class('ServiceWorker.workerRegistrationUpdated')
@dataclass
class WorkerRegistrationUpdated:
    registrations: typing.List[ServiceWorkerRegistration]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WorkerRegistrationUpdated:
        ...



@event_class('ServiceWorker.workerVersionUpdated')
@dataclass
class WorkerVersionUpdated:
    versions: typing.List[ServiceWorkerVersion]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> WorkerVersionUpdated:
        ...
