"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class

class ResultCode(enum.Enum):
    '''
    Indicates the PC/SC error code.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__ErrorCodes.html
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/secauthn/authentication-return-values
    '''
    SUCCESS = ...
    REMOVED_CARD = ...
    RESET_CARD = ...
    UNPOWERED_CARD = ...
    UNRESPONSIVE_CARD = ...
    UNSUPPORTED_CARD = ...
    READER_UNAVAILABLE = ...
    SHARING_VIOLATION = ...
    NOT_TRANSACTED = ...
    NO_SMARTCARD = ...
    PROTO_MISMATCH = ...
    SYSTEM_CANCELLED = ...
    NOT_READY = ...
    CANCELLED = ...
    INSUFFICIENT_BUFFER = ...
    INVALID_HANDLE = ...
    INVALID_PARAMETER = ...
    INVALID_VALUE = ...
    NO_MEMORY = ...
    TIMEOUT = ...
    UNKNOWN_READER = ...
    UNSUPPORTED_FEATURE = ...
    NO_READERS_AVAILABLE = ...
    SERVICE_STOPPED = ...
    NO_SERVICE = ...
    COMM_ERROR = ...
    INTERNAL_ERROR = ...
    SERVER_TOO_BUSY = ...
    UNEXPECTED = ...
    SHUTDOWN = ...
    UNKNOWN_CARD = ...
    UNKNOWN = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ResultCode:
        ...



class ShareMode(enum.Enum):
    '''
    Maps to the ``SCARD_SHARE_*`` values.
    '''
    SHARED = ...
    EXCLUSIVE = ...
    DIRECT = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ShareMode:
        ...



class Disposition(enum.Enum):
    '''
    Indicates what the reader should do with the card.
    '''
    LEAVE_CARD = ...
    RESET_CARD = ...
    UNPOWER_CARD = ...
    EJECT_CARD = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> Disposition:
        ...



class ConnectionState(enum.Enum):
    '''
    Maps to ``SCARD_*`` connection state values.
    '''
    ABSENT = ...
    PRESENT = ...
    SWALLOWED = ...
    POWERED = ...
    NEGOTIABLE = ...
    SPECIFIC = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ConnectionState:
        ...



@dataclass
class ReaderStateFlags:
    '''
    Maps to the ``SCARD_STATE_*`` flags.
    '''
    unaware: typing.Optional[bool] = ...
    ignore: typing.Optional[bool] = ...
    changed: typing.Optional[bool] = ...
    unknown: typing.Optional[bool] = ...
    unavailable: typing.Optional[bool] = ...
    empty: typing.Optional[bool] = ...
    present: typing.Optional[bool] = ...
    exclusive: typing.Optional[bool] = ...
    inuse: typing.Optional[bool] = ...
    mute: typing.Optional[bool] = ...
    unpowered: typing.Optional[bool] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReaderStateFlags:
        ...



@dataclass
class ProtocolSet:
    '''
    Maps to the ``SCARD_PROTOCOL_*`` flags.
    '''
    t0: typing.Optional[bool] = ...
    t1: typing.Optional[bool] = ...
    raw: typing.Optional[bool] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ProtocolSet:
        ...



class Protocol(enum.Enum):
    '''
    Maps to the ``SCARD_PROTOCOL_*`` values.
    '''
    T0 = ...
    T1 = ...
    RAW = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> Protocol:
        ...



@dataclass
class ReaderStateIn:
    reader: str
    current_state: ReaderStateFlags
    current_insertion_count: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReaderStateIn:
        ...



@dataclass
class ReaderStateOut:
    reader: str
    event_state: ReaderStateFlags
    event_count: int
    atr: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReaderStateOut:
        ...



def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables the ``SmartCardEmulation`` domain.
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disables the ``SmartCardEmulation`` domain.
    '''
    ...

def report_establish_context_result(request_id: str, context_id: int) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Reports the successful result of a ``SCardEstablishContext`` call.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaa1b8970169fd4883a6dc4a8f43f19b67
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardestablishcontext

    :param request_id:
    :param context_id:
    '''
    ...

def report_release_context_result(request_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Reports the successful result of a ``SCardReleaseContext`` call.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga6aabcba7744c5c9419fdd6404f73a934
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardreleasecontext

    :param request_id:
    '''
    ...

def report_list_readers_result(request_id: str, readers: typing.List[str]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Reports the successful result of a ``SCardListReaders`` call.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga93b07815789b3cf2629d439ecf20f0d9
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardlistreadersa

    :param request_id:
    :param readers:
    '''
    ...

def report_get_status_change_result(request_id: str, reader_states: typing.List[ReaderStateOut]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Reports the successful result of a ``SCardGetStatusChange`` call.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga33247d5d1257d59e55647c3bb717db24
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetstatuschangea

    :param request_id:
    :param reader_states:
    '''
    ...

def report_begin_transaction_result(request_id: str, handle: int) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Reports the result of a ``SCardBeginTransaction`` call.
    On success, this creates a new transaction object.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaddb835dce01a0da1d6ca02d33ee7d861
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardbegintransaction

    :param request_id:
    :param handle:
    '''
    ...

def report_plain_result(request_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Reports the successful result of a call that returns only a result code.
    Used for: ``SCardCancel``, ``SCardDisconnect``, ``SCardSetAttrib``, ``SCardEndTransaction``.

    This maps to:
    1. SCardCancel
       PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaacbbc0c6d6c0cbbeb4f4debf6fbeeee6
       Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcancel

    2. SCardDisconnect
       PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga4be198045c73ec0deb79e66c0ca1738a
       Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scarddisconnect

    3. SCardSetAttrib
       PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga060f0038a4ddfd5dd2b8fadf3c3a2e4f
       Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardsetattrib

    4. SCardEndTransaction
       PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gae8742473b404363e5c587f570d7e2f3b
       Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardendtransaction

    :param request_id:
    '''
    ...

def report_connect_result(request_id: str, handle: int, active_protocol: typing.Optional[Protocol] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Reports the successful result of a ``SCardConnect`` call.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga4e515829752e0a8dbc4d630696a8d6a5
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardconnecta

    :param request_id:
    :param handle:
    :param active_protocol: *(Optional)*
    '''
    ...

def report_data_result(request_id: str, data: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Reports the successful result of a call that sends back data on success.
    Used for ``SCardTransmit``, ``SCardControl``, and ``SCardGetAttrib``.

    This maps to:
    1. SCardTransmit
       PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga9a2d77242a271310269065e64633ab99
       Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardtransmit

    2. SCardControl
       PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gac3454d4657110fd7f753b2d3d8f4e32f
       Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcontrol

    3. SCardGetAttrib
       PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaacfec51917255b7a25b94c5104961602
       Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetattrib

    :param request_id:
    :param data:
    '''
    ...

def report_status_result(request_id: str, reader_name: str, state: ConnectionState, atr: str, protocol: typing.Optional[Protocol] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Reports the successful result of a ``SCardStatus`` call.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gae49c3c894ad7ac12a5b896bde70d0382
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardstatusa

    :param request_id:
    :param reader_name:
    :param state:
    :param atr:
    :param protocol: *(Optional)*
    '''
    ...

def report_error(request_id: str, result_code: ResultCode) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Reports an error result for the given request.

    :param request_id:
    :param result_code:
    '''
    ...

@event_class('SmartCardEmulation.establishContextRequested')
@dataclass
class EstablishContextRequested:
    '''
    Fired when ``SCardEstablishContext`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaa1b8970169fd4883a6dc4a8f43f19b67
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardestablishcontext
    '''
    request_id: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> EstablishContextRequested:
        ...



@event_class('SmartCardEmulation.releaseContextRequested')
@dataclass
class ReleaseContextRequested:
    '''
    Fired when ``SCardReleaseContext`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga6aabcba7744c5c9419fdd6404f73a934
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardreleasecontext
    '''
    request_id: str
    context_id: int
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReleaseContextRequested:
        ...



@event_class('SmartCardEmulation.listReadersRequested')
@dataclass
class ListReadersRequested:
    '''
    Fired when ``SCardListReaders`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga93b07815789b3cf2629d439ecf20f0d9
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardlistreadersa
    '''
    request_id: str
    context_id: int
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ListReadersRequested:
        ...



@event_class('SmartCardEmulation.getStatusChangeRequested')
@dataclass
class GetStatusChangeRequested:
    '''
    Fired when ``SCardGetStatusChange`` is called. Timeout is specified in milliseconds.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga33247d5d1257d59e55647c3bb717db24
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetstatuschangea
    '''
    request_id: str
    context_id: int
    reader_states: typing.List[ReaderStateIn]
    timeout: typing.Optional[int]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> GetStatusChangeRequested:
        ...



@event_class('SmartCardEmulation.cancelRequested')
@dataclass
class CancelRequested:
    '''
    Fired when ``SCardCancel`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaacbbc0c6d6c0cbbeb4f4debf6fbeeee6
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcancel
    '''
    request_id: str
    context_id: int
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CancelRequested:
        ...



@event_class('SmartCardEmulation.connectRequested')
@dataclass
class ConnectRequested:
    '''
    Fired when ``SCardConnect`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga4e515829752e0a8dbc4d630696a8d6a5
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardconnecta
    '''
    request_id: str
    context_id: int
    reader: str
    share_mode: ShareMode
    preferred_protocols: ProtocolSet
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ConnectRequested:
        ...



@event_class('SmartCardEmulation.disconnectRequested')
@dataclass
class DisconnectRequested:
    '''
    Fired when ``SCardDisconnect`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga4be198045c73ec0deb79e66c0ca1738a
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scarddisconnect
    '''
    request_id: str
    handle: int
    disposition: Disposition
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DisconnectRequested:
        ...



@event_class('SmartCardEmulation.transmitRequested')
@dataclass
class TransmitRequested:
    '''
    Fired when ``SCardTransmit`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga9a2d77242a271310269065e64633ab99
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardtransmit
    '''
    request_id: str
    handle: int
    data: str
    protocol: typing.Optional[Protocol]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TransmitRequested:
        ...



@event_class('SmartCardEmulation.controlRequested')
@dataclass
class ControlRequested:
    '''
    Fired when ``SCardControl`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gac3454d4657110fd7f753b2d3d8f4e32f
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcontrol
    '''
    request_id: str
    handle: int
    control_code: int
    data: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ControlRequested:
        ...



@event_class('SmartCardEmulation.getAttribRequested')
@dataclass
class GetAttribRequested:
    '''
    Fired when ``SCardGetAttrib`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaacfec51917255b7a25b94c5104961602
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetattrib
    '''
    request_id: str
    handle: int
    attrib_id: int
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> GetAttribRequested:
        ...



@event_class('SmartCardEmulation.setAttribRequested')
@dataclass
class SetAttribRequested:
    '''
    Fired when ``SCardSetAttrib`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga060f0038a4ddfd5dd2b8fadf3c3a2e4f
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardsetattrib
    '''
    request_id: str
    handle: int
    attrib_id: int
    data: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SetAttribRequested:
        ...



@event_class('SmartCardEmulation.statusRequested')
@dataclass
class StatusRequested:
    '''
    Fired when ``SCardStatus`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gae49c3c894ad7ac12a5b896bde70d0382
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardstatusa
    '''
    request_id: str
    handle: int
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StatusRequested:
        ...



@event_class('SmartCardEmulation.beginTransactionRequested')
@dataclass
class BeginTransactionRequested:
    '''
    Fired when ``SCardBeginTransaction`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaddb835dce01a0da1d6ca02d33ee7d861
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardbegintransaction
    '''
    request_id: str
    handle: int
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BeginTransactionRequested:
        ...



@event_class('SmartCardEmulation.endTransactionRequested')
@dataclass
class EndTransactionRequested:
    '''
    Fired when ``SCardEndTransaction`` is called.

    This maps to:
    PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gae8742473b404363e5c587f570d7e2f3b
    Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardendtransaction
    '''
    request_id: str
    handle: int
    disposition: Disposition
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> EndTransactionRequested:
        ...
