"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
from . import browser, network, page, target
from deprecated.sphinx import deprecated

class SerializedStorageKey(str):
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> SerializedStorageKey:
        ...

    def __repr__(self) -> str:
        ...



class StorageType(enum.Enum):
    '''
    Enum of possible storage types.
    '''
    COOKIES = ...
    FILE_SYSTEMS = ...
    INDEXEDDB = ...
    LOCAL_STORAGE = ...
    SHADER_CACHE = ...
    WEBSQL = ...
    SERVICE_WORKERS = ...
    CACHE_STORAGE = ...
    INTEREST_GROUPS = ...
    SHARED_STORAGE = ...
    STORAGE_BUCKETS = ...
    ALL_ = ...
    OTHER = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> StorageType:
        ...



@dataclass
class UsageForType:
    '''
    Usage for a storage type.
    '''
    storage_type: StorageType
    usage: float
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> UsageForType:
        ...



@dataclass
class TrustTokens:
    '''
    Pair of issuer origin and number of available (signed, but not used) Trust
    Tokens from that issuer.
    '''
    issuer_origin: str
    count: float
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TrustTokens:
        ...



class InterestGroupAuctionId(str):
    '''
    Protected audience interest group auction identifier.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> InterestGroupAuctionId:
        ...

    def __repr__(self) -> str:
        ...



class InterestGroupAccessType(enum.Enum):
    '''
    Enum of interest group access types.
    '''
    JOIN = ...
    LEAVE = ...
    UPDATE = ...
    LOADED = ...
    BID = ...
    WIN = ...
    ADDITIONAL_BID = ...
    ADDITIONAL_BID_WIN = ...
    TOP_LEVEL_BID = ...
    TOP_LEVEL_ADDITIONAL_BID = ...
    CLEAR = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> InterestGroupAccessType:
        ...



class InterestGroupAuctionEventType(enum.Enum):
    '''
    Enum of auction events.
    '''
    STARTED = ...
    CONFIG_RESOLVED = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> InterestGroupAuctionEventType:
        ...



class InterestGroupAuctionFetchType(enum.Enum):
    '''
    Enum of network fetches auctions can do.
    '''
    BIDDER_JS = ...
    BIDDER_WASM = ...
    SELLER_JS = ...
    BIDDER_TRUSTED_SIGNALS = ...
    SELLER_TRUSTED_SIGNALS = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> InterestGroupAuctionFetchType:
        ...



class SharedStorageAccessScope(enum.Enum):
    '''
    Enum of shared storage access scopes.
    '''
    WINDOW = ...
    SHARED_STORAGE_WORKLET = ...
    PROTECTED_AUDIENCE_WORKLET = ...
    HEADER = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> SharedStorageAccessScope:
        ...



class SharedStorageAccessMethod(enum.Enum):
    '''
    Enum of shared storage access methods.
    '''
    ADD_MODULE = ...
    CREATE_WORKLET = ...
    SELECT_URL = ...
    RUN = ...
    BATCH_UPDATE = ...
    SET_ = ...
    APPEND = ...
    DELETE = ...
    CLEAR = ...
    GET = ...
    KEYS = ...
    VALUES = ...
    ENTRIES = ...
    LENGTH = ...
    REMAINING_BUDGET = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> SharedStorageAccessMethod:
        ...



@dataclass
class SharedStorageEntry:
    '''
    Struct for a single key-value pair in an origin's shared storage.
    '''
    key: str
    value: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageEntry:
        ...



@dataclass
class SharedStorageMetadata:
    '''
    Details for an origin's shared storage.
    '''
    creation_time: network.TimeSinceEpoch
    length: int
    remaining_budget: float
    bytes_used: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageMetadata:
        ...



@dataclass
class SharedStoragePrivateAggregationConfig:
    '''
    Represents a dictionary object passed in as privateAggregationConfig to
    run or selectURL.
    '''
    filtering_id_max_bytes: int
    aggregation_coordinator_origin: typing.Optional[str] = ...
    context_id: typing.Optional[str] = ...
    max_contributions: typing.Optional[int] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStoragePrivateAggregationConfig:
        ...



@dataclass
class SharedStorageReportingMetadata:
    '''
    Pair of reporting metadata details for a candidate URL for ``selectURL()``.
    '''
    event_type: str
    reporting_url: str
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageReportingMetadata:
        ...



@dataclass
class SharedStorageUrlWithMetadata:
    '''
    Bundles a candidate URL with its reporting metadata.
    '''
    url: str
    reporting_metadata: typing.List[SharedStorageReportingMetadata]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageUrlWithMetadata:
        ...



@dataclass
class SharedStorageAccessParams:
    '''
    Bundles the parameters for shared storage access events whose
    presence/absence can vary according to SharedStorageAccessType.
    '''
    script_source_url: typing.Optional[str] = ...
    data_origin: typing.Optional[str] = ...
    operation_name: typing.Optional[str] = ...
    operation_id: typing.Optional[str] = ...
    keep_alive: typing.Optional[bool] = ...
    private_aggregation_config: typing.Optional[SharedStoragePrivateAggregationConfig] = ...
    serialized_data: typing.Optional[str] = ...
    urls_with_metadata: typing.Optional[typing.List[SharedStorageUrlWithMetadata]] = ...
    urn_uuid: typing.Optional[str] = ...
    key: typing.Optional[str] = ...
    value: typing.Optional[str] = ...
    ignore_if_present: typing.Optional[bool] = ...
    worklet_ordinal: typing.Optional[int] = ...
    worklet_target_id: typing.Optional[target.TargetID] = ...
    with_lock: typing.Optional[str] = ...
    batch_update_id: typing.Optional[str] = ...
    batch_size: typing.Optional[int] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageAccessParams:
        ...



class StorageBucketsDurability(enum.Enum):
    RELAXED = ...
    STRICT = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> StorageBucketsDurability:
        ...



@dataclass
class StorageBucket:
    storage_key: SerializedStorageKey
    name: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StorageBucket:
        ...



@dataclass
class StorageBucketInfo:
    bucket: StorageBucket
    id_: str
    expiration: network.TimeSinceEpoch
    quota: float
    persistent: bool
    durability: StorageBucketsDurability
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StorageBucketInfo:
        ...



@dataclass
class RelatedWebsiteSet:
    '''
    A single Related Website Set object.
    '''
    primary_sites: typing.List[str]
    associated_sites: typing.List[str]
    service_sites: typing.List[str]
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RelatedWebsiteSet:
        ...



@deprecated(version="1.3")
def get_storage_key_for_frame(frame_id: page.FrameId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SerializedStorageKey]:
    '''
    Returns a storage key given a frame id.
    Deprecated. Please use Storage.getStorageKey instead.

    .. deprecated:: 1.3

    :param frame_id:
    :returns:
    '''
    ...

def get_storage_key(frame_id: typing.Optional[page.FrameId] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SerializedStorageKey]:
    '''
    Returns storage key for the given frame. If no frame ID is provided,
    the storage key of the target executing this command is returned.

    **EXPERIMENTAL**

    :param frame_id: *(Optional)*
    :returns:
    '''
    ...

def clear_data_for_origin(origin: str, storage_types: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Clears storage for origin.

    :param origin: Security origin.
    :param storage_types: Comma separated list of StorageType to clear.
    '''
    ...

def clear_data_for_storage_key(storage_key: str, storage_types: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Clears storage for storage key.

    :param storage_key: Storage key.
    :param storage_types: Comma separated list of StorageType to clear.
    '''
    ...

def get_cookies(browser_context_id: typing.Optional[browser.BrowserContextID] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[network.Cookie]]:
    '''
    Returns all browser cookies.

    :param browser_context_id: *(Optional)* Browser context to use when called on the browser endpoint.
    :returns: Array of cookie objects.
    '''
    ...

def set_cookies(cookies: typing.List[network.CookieParam], browser_context_id: typing.Optional[browser.BrowserContextID] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets given cookies.

    :param cookies: Cookies to be set.
    :param browser_context_id: *(Optional)* Browser context to use when called on the browser endpoint.
    '''
    ...

def clear_cookies(browser_context_id: typing.Optional[browser.BrowserContextID] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Clears cookies.

    :param browser_context_id: *(Optional)* Browser context to use when called on the browser endpoint.
    '''
    ...

def get_usage_and_quota(origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[float, float, bool, typing.List[UsageForType]]]:
    '''
    Returns usage and quota in bytes.

    :param origin: Security origin.
    :returns: A tuple with the following items:

        0. **usage** - Storage usage (bytes).
        1. **quota** - Storage quota (bytes).
        2. **overrideActive** - Whether or not the origin has an active storage quota override
        3. **usageBreakdown** - Storage usage per type (bytes).
    '''
    ...

def override_quota_for_origin(origin: str, quota_size: typing.Optional[float] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Override quota for the specified origin

    **EXPERIMENTAL**

    :param origin: Security origin.
    :param quota_size: *(Optional)* The quota size (in bytes) to override the original quota with. If this is called multiple times, the overridden quota will be equal to the quotaSize provided in the final call. If this is called without specifying a quotaSize, the quota will be reset to the default value for the specified origin. If this is called multiple times with different origins, the override will be maintained for each origin until it is disabled (called without a quotaSize).
    '''
    ...

def track_cache_storage_for_origin(origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Registers origin to be notified when an update occurs to its cache storage list.

    :param origin: Security origin.
    '''
    ...

def track_cache_storage_for_storage_key(storage_key: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Registers storage key to be notified when an update occurs to its cache storage list.

    :param storage_key: Storage key.
    '''
    ...

def track_indexed_db_for_origin(origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Registers origin to be notified when an update occurs to its IndexedDB.

    :param origin: Security origin.
    '''
    ...

def track_indexed_db_for_storage_key(storage_key: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Registers storage key to be notified when an update occurs to its IndexedDB.

    :param storage_key: Storage key.
    '''
    ...

def untrack_cache_storage_for_origin(origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Unregisters origin from receiving notifications for cache storage.

    :param origin: Security origin.
    '''
    ...

def untrack_cache_storage_for_storage_key(storage_key: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Unregisters storage key from receiving notifications for cache storage.

    :param storage_key: Storage key.
    '''
    ...

def untrack_indexed_db_for_origin(origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Unregisters origin from receiving notifications for IndexedDB.

    :param origin: Security origin.
    '''
    ...

def untrack_indexed_db_for_storage_key(storage_key: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Unregisters storage key from receiving notifications for IndexedDB.

    :param storage_key: Storage key.
    '''
    ...

def get_trust_tokens() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[TrustTokens]]:
    '''
    Returns the number of stored Trust Tokens per issuer for the
    current browsing context.

    **EXPERIMENTAL**

    :returns:
    '''
    ...

def clear_trust_tokens(issuer_origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, bool]:
    '''
    Removes all Trust Tokens issued by the provided issuerOrigin.
    Leaves other stored data, including the issuer's Redemption Records, intact.

    **EXPERIMENTAL**

    :param issuer_origin:
    :returns: True if any tokens were deleted, false otherwise.
    '''
    ...

def get_interest_group_details(owner_origin: str, name: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, dict]:
    '''
    Gets details for a named interest group.

    **EXPERIMENTAL**

    :param owner_origin:
    :param name:
    :returns: This largely corresponds to: https://wicg.github.io/turtledove/#dictdef-generatebidinterestgroup but has absolute expirationTime instead of relative lifetimeMs and also adds joiningOrigin.
    '''
    ...

def set_interest_group_tracking(enable: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables/Disables issuing of interestGroupAccessed events.

    **EXPERIMENTAL**

    :param enable:
    '''
    ...

def set_interest_group_auction_tracking(enable: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables/Disables issuing of interestGroupAuctionEventOccurred and
    interestGroupAuctionNetworkRequestCreated.

    **EXPERIMENTAL**

    :param enable:
    '''
    ...

def get_shared_storage_metadata(owner_origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SharedStorageMetadata]:
    '''
    Gets metadata for an origin's shared storage.

    **EXPERIMENTAL**

    :param owner_origin:
    :returns:
    '''
    ...

def get_shared_storage_entries(owner_origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[SharedStorageEntry]]:
    '''
    Gets the entries in an given origin's shared storage.

    **EXPERIMENTAL**

    :param owner_origin:
    :returns:
    '''
    ...

def set_shared_storage_entry(owner_origin: str, key: str, value: str, ignore_if_present: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets entry with ``key`` and ``value`` for a given origin's shared storage.

    **EXPERIMENTAL**

    :param owner_origin:
    :param key:
    :param value:
    :param ignore_if_present: *(Optional)* If ```ignoreIfPresent```` is included and true, then only sets the entry if ````key``` doesn't already exist.
    '''
    ...

def delete_shared_storage_entry(owner_origin: str, key: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Deletes entry for ``key`` (if it exists) for a given origin's shared storage.

    **EXPERIMENTAL**

    :param owner_origin:
    :param key:
    '''
    ...

def clear_shared_storage_entries(owner_origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Clears all entries for a given origin's shared storage.

    **EXPERIMENTAL**

    :param owner_origin:
    '''
    ...

def reset_shared_storage_budget(owner_origin: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Resets the budget for ``ownerOrigin`` by clearing all budget withdrawals.

    **EXPERIMENTAL**

    :param owner_origin:
    '''
    ...

def set_shared_storage_tracking(enable: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables/disables issuing of sharedStorageAccessed events.

    **EXPERIMENTAL**

    :param enable:
    '''
    ...

def set_storage_bucket_tracking(storage_key: str, enable: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Set tracking for a storage key's buckets.

    **EXPERIMENTAL**

    :param storage_key:
    :param enable:
    '''
    ...

def delete_storage_bucket(bucket: StorageBucket) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Deletes the Storage Bucket with the given storage key and bucket name.

    **EXPERIMENTAL**

    :param bucket:
    '''
    ...

def run_bounce_tracking_mitigations() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[str]]:
    '''
    Deletes state for sites identified as potential bounce trackers, immediately.

    **EXPERIMENTAL**

    :returns:
    '''
    ...

def get_related_website_sets() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[RelatedWebsiteSet]]:
    '''
    Returns the effective Related Website Sets in use by this profile for the browser
    session. The effective Related Website Sets will not change during a browser session.

    **EXPERIMENTAL**

    :returns:
    '''
    ...

def set_protected_audience_k_anonymity(owner: str, name: str, hashes: typing.List[str]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    :param owner:
    :param name:
    :param hashes:
    '''
    ...

@event_class('Storage.cacheStorageContentUpdated')
@dataclass
class CacheStorageContentUpdated:
    '''
    A cache's contents have been modified.
    '''
    origin: str
    storage_key: str
    bucket_id: str
    cache_name: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CacheStorageContentUpdated:
        ...



@event_class('Storage.cacheStorageListUpdated')
@dataclass
class CacheStorageListUpdated:
    '''
    A cache has been added/deleted.
    '''
    origin: str
    storage_key: str
    bucket_id: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CacheStorageListUpdated:
        ...



@event_class('Storage.indexedDBContentUpdated')
@dataclass
class IndexedDBContentUpdated:
    '''
    The origin's IndexedDB object store has been modified.
    '''
    origin: str
    storage_key: str
    bucket_id: str
    database_name: str
    object_store_name: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> IndexedDBContentUpdated:
        ...



@event_class('Storage.indexedDBListUpdated')
@dataclass
class IndexedDBListUpdated:
    '''
    The origin's IndexedDB database list has been modified.
    '''
    origin: str
    storage_key: str
    bucket_id: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> IndexedDBListUpdated:
        ...



@event_class('Storage.interestGroupAccessed')
@dataclass
class InterestGroupAccessed:
    '''
    One of the interest groups was accessed. Note that these events are global
    to all targets sharing an interest group store.
    '''
    access_time: network.TimeSinceEpoch
    type_: InterestGroupAccessType
    owner_origin: str
    name: str
    component_seller_origin: typing.Optional[str]
    bid: typing.Optional[float]
    bid_currency: typing.Optional[str]
    unique_auction_id: typing.Optional[InterestGroupAuctionId]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> InterestGroupAccessed:
        ...



@event_class('Storage.interestGroupAuctionEventOccurred')
@dataclass
class InterestGroupAuctionEventOccurred:
    '''
    An auction involving interest groups is taking place. These events are
    target-specific.
    '''
    event_time: network.TimeSinceEpoch
    type_: InterestGroupAuctionEventType
    unique_auction_id: InterestGroupAuctionId
    parent_auction_id: typing.Optional[InterestGroupAuctionId]
    auction_config: typing.Optional[dict]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> InterestGroupAuctionEventOccurred:
        ...



@event_class('Storage.interestGroupAuctionNetworkRequestCreated')
@dataclass
class InterestGroupAuctionNetworkRequestCreated:
    '''
    Specifies which auctions a particular network fetch may be related to, and
    in what role. Note that it is not ordered with respect to
    Network.requestWillBeSent (but will happen before loadingFinished
    loadingFailed).
    '''
    type_: InterestGroupAuctionFetchType
    request_id: network.RequestId
    auctions: typing.List[InterestGroupAuctionId]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> InterestGroupAuctionNetworkRequestCreated:
        ...



@event_class('Storage.sharedStorageAccessed')
@dataclass
class SharedStorageAccessed:
    '''
    Shared storage was accessed by the associated page.
    The following parameters are included in all events.
    '''
    access_time: network.TimeSinceEpoch
    scope: SharedStorageAccessScope
    method: SharedStorageAccessMethod
    main_frame_id: page.FrameId
    owner_origin: str
    owner_site: str
    params: SharedStorageAccessParams
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageAccessed:
        ...



@event_class('Storage.sharedStorageWorkletOperationExecutionFinished')
@dataclass
class SharedStorageWorkletOperationExecutionFinished:
    '''
    A shared storage run or selectURL operation finished its execution.
    The following parameters are included in all events.
    '''
    finished_time: network.TimeSinceEpoch
    execution_time: int
    method: SharedStorageAccessMethod
    operation_id: str
    worklet_target_id: target.TargetID
    main_frame_id: page.FrameId
    owner_origin: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> SharedStorageWorkletOperationExecutionFinished:
        ...



@event_class('Storage.storageBucketCreatedOrUpdated')
@dataclass
class StorageBucketCreatedOrUpdated:
    bucket_info: StorageBucketInfo
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StorageBucketCreatedOrUpdated:
        ...



@event_class('Storage.storageBucketDeleted')
@dataclass
class StorageBucketDeleted:
    bucket_id: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> StorageBucketDeleted:
        ...
