"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT

@dataclass
class GPUDevice:
    '''
    Describes a single graphics processor (GPU).
    '''
    vendor_id: float
    device_id: float
    vendor_string: str
    device_string: str
    driver_vendor: str
    driver_version: str
    sub_sys_id: typing.Optional[float] = ...
    revision: typing.Optional[float] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> GPUDevice:
        ...



@dataclass
class Size:
    '''
    Describes the width and height dimensions of an entity.
    '''
    width: int
    height: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Size:
        ...



@dataclass
class VideoDecodeAcceleratorCapability:
    '''
    Describes a supported video decoding profile with its associated minimum and
    maximum resolutions.
    '''
    profile: str
    max_resolution: Size
    min_resolution: Size
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> VideoDecodeAcceleratorCapability:
        ...



@dataclass
class VideoEncodeAcceleratorCapability:
    '''
    Describes a supported video encoding profile with its associated maximum
    resolution and maximum framerate.
    '''
    profile: str
    max_resolution: Size
    max_framerate_numerator: int
    max_framerate_denominator: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> VideoEncodeAcceleratorCapability:
        ...



class SubsamplingFormat(enum.Enum):
    '''
    YUV subsampling type of the pixels of a given image.
    '''
    YUV420 = ...
    YUV422 = ...
    YUV444 = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> SubsamplingFormat:
        ...



class ImageType(enum.Enum):
    '''
    Image format of a given image.
    '''
    JPEG = ...
    WEBP = ...
    UNKNOWN = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ImageType:
        ...



@dataclass
class GPUInfo:
    '''
    Provides information about the GPU(s) on the system.
    '''
    devices: typing.List[GPUDevice]
    driver_bug_workarounds: typing.List[str]
    video_decoding: typing.List[VideoDecodeAcceleratorCapability]
    video_encoding: typing.List[VideoEncodeAcceleratorCapability]
    aux_attributes: typing.Optional[dict] = ...
    feature_status: typing.Optional[dict] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> GPUInfo:
        ...



@dataclass
class ProcessInfo:
    '''
    Represents process info.
    '''
    type_: str
    id_: int
    cpu_time: float
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ProcessInfo:
        ...



def get_info() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[GPUInfo, str, str, str]]:
    '''
    Returns information about the system.

    :returns: A tuple with the following items:

        0. **gpu** - Information about the GPUs on the system.
        1. **modelName** - A platform-dependent description of the model of the machine. On Mac OS, this is, for example, 'MacBookPro'. Will be the empty string if not supported.
        2. **modelVersion** - A platform-dependent description of the version of the machine. On Mac OS, this is, for example, '10.1'. Will be the empty string if not supported.
        3. **commandLine** - The command line string used to launch the browser. Will be the empty string if not supported.
    '''
    ...

def get_feature_state(feature_state: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, bool]:
    '''
    Returns information about the feature state.

    :param feature_state:
    :returns:
    '''
    ...

def get_process_info() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[ProcessInfo]]:
    '''
    Returns information about all running processes.

    :returns: An array of process info blocks.
    '''
    ...
