"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class
from . import browser, page
from deprecated.sphinx import deprecated

class TargetID(str):
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> TargetID:
        ...

    def __repr__(self) -> str:
        ...



class SessionID(str):
    '''
    Unique identifier of attached debugging session.
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> SessionID:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class TargetInfo:
    target_id: TargetID
    type_: str
    title: str
    url: str
    attached: bool
    can_access_opener: bool
    parent_id: typing.Optional[TargetID] = ...
    opener_id: typing.Optional[TargetID] = ...
    opener_frame_id: typing.Optional[page.FrameId] = ...
    parent_frame_id: typing.Optional[page.FrameId] = ...
    browser_context_id: typing.Optional[browser.BrowserContextID] = ...
    subtype: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetInfo:
        ...



@dataclass
class FilterEntry:
    '''
    A filter used by target query/discovery/auto-attach operations.
    '''
    exclude: typing.Optional[bool] = ...
    type_: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> FilterEntry:
        ...



class TargetFilter(list):
    '''
    The entries in TargetFilter are matched sequentially against targets and
    the first entry that matches determines if the target is included or not,
    depending on the value of ``exclude`` field in the entry.
    If filter is not specified, the one assumed is
    [{type: "browser", exclude: true}, {type: "tab", exclude: true}, {}]
    (i.e. include everything but ``browser`` and ``tab``).
    '''
    def to_json(self) -> typing.List[FilterEntry]:
        ...

    @classmethod
    def from_json(cls, json: typing.List[FilterEntry]) -> TargetFilter:
        ...

    def __repr__(self) -> str:
        ...



@dataclass
class RemoteLocation:
    host: str
    port: int
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> RemoteLocation:
        ...



class WindowState(enum.Enum):
    '''
    The state of the target window.
    '''
    NORMAL = ...
    MINIMIZED = ...
    MAXIMIZED = ...
    FULLSCREEN = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> WindowState:
        ...



def activate_target(target_id: TargetID) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Activates (focuses) the target.

    :param target_id:
    '''
    ...

def attach_to_target(target_id: TargetID, flatten: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SessionID]:
    '''
    Attaches to the target with given id.

    :param target_id:
    :param flatten: *(Optional)* Enables "flat" access to the session via specifying sessionId attribute in the commands. We plan to make this the default, deprecate non-flattened mode, and eventually retire it. See crbug.com/991325.
    :returns: Id assigned to the session.
    '''
    ...

def attach_to_browser_target() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, SessionID]:
    '''
    Attaches to the browser target, only uses flat sessionId mode.

    **EXPERIMENTAL**

    :returns: Id assigned to the session.
    '''
    ...

def close_target(target_id: TargetID) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, bool]:
    '''
    Closes the target. If the target is a page that gets closed too.

    :param target_id:
    :returns: Always set to true. If an error occurs, the response indicates protocol error.
    '''
    ...

def expose_dev_tools_protocol(target_id: TargetID, binding_name: typing.Optional[str] = ..., inherit_permissions: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Inject object to the target's main frame that provides a communication
    channel with browser target.

    Injected object will be available as ``window[bindingName]``.

    The object has the following API:
    - ``binding.send(json)`` - a method to send messages over the remote debugging protocol
    - ``binding.onmessage = json => handleMessage(json)`` - a callback that will be called for the protocol notifications and command responses.

    **EXPERIMENTAL**

    :param target_id:
    :param binding_name: *(Optional)* Binding name, 'cdp' if not specified.
    :param inherit_permissions: *(Optional)* If true, inherits the current root session's permissions (default: false).
    '''
    ...

def create_browser_context(dispose_on_detach: typing.Optional[bool] = ..., proxy_server: typing.Optional[str] = ..., proxy_bypass_list: typing.Optional[str] = ..., origins_with_universal_network_access: typing.Optional[typing.List[str]] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, browser.BrowserContextID]:
    '''
    Creates a new empty BrowserContext. Similar to an incognito profile but you can have more than
    one.

    :param dispose_on_detach: **(EXPERIMENTAL)** *(Optional)* If specified, disposes this context when debugging session disconnects.
    :param proxy_server: **(EXPERIMENTAL)** *(Optional)* Proxy server, similar to the one passed to --proxy-server
    :param proxy_bypass_list: **(EXPERIMENTAL)** *(Optional)* Proxy bypass list, similar to the one passed to --proxy-bypass-list
    :param origins_with_universal_network_access: **(EXPERIMENTAL)** *(Optional)* An optional list of origins to grant unlimited cross-origin access to. Parts of the URL other than those constituting origin are ignored.
    :returns: The id of the context created.
    '''
    ...

def get_browser_contexts() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Tuple[typing.List[browser.BrowserContextID], typing.Optional[browser.BrowserContextID]]]:
    '''
    Returns all browser contexts created with ``Target.createBrowserContext`` method.

    :returns: A tuple with the following items:

        0. **browserContextIds** - An array of browser context ids.
        1. **defaultBrowserContextId** - *(Optional)* The id of the default browser context if available.
    '''
    ...

def create_target(url: str, left: typing.Optional[int] = ..., top: typing.Optional[int] = ..., width: typing.Optional[int] = ..., height: typing.Optional[int] = ..., window_state: typing.Optional[WindowState] = ..., browser_context_id: typing.Optional[browser.BrowserContextID] = ..., enable_begin_frame_control: typing.Optional[bool] = ..., new_window: typing.Optional[bool] = ..., background: typing.Optional[bool] = ..., for_tab: typing.Optional[bool] = ..., hidden: typing.Optional[bool] = ..., focus: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, TargetID]:
    '''
    Creates a new page.

    :param url: The initial URL the page will be navigated to. An empty string indicates about:blank.
    :param left: **(EXPERIMENTAL)** *(Optional)* Frame left origin in DIP (requires newWindow to be true or headless shell).
    :param top: **(EXPERIMENTAL)** *(Optional)* Frame top origin in DIP (requires newWindow to be true or headless shell).
    :param width: *(Optional)* Frame width in DIP (requires newWindow to be true or headless shell).
    :param height: *(Optional)* Frame height in DIP (requires newWindow to be true or headless shell).
    :param window_state: *(Optional)* Frame window state (requires newWindow to be true or headless shell). Default is normal.
    :param browser_context_id: **(EXPERIMENTAL)** *(Optional)* The browser context to create the page in.
    :param enable_begin_frame_control: **(EXPERIMENTAL)** *(Optional)* Whether BeginFrames for this target will be controlled via DevTools (headless shell only, not supported on MacOS yet, false by default).
    :param new_window: *(Optional)* Whether to create a new Window or Tab (false by default, not supported by headless shell).
    :param background: *(Optional)* Whether to create the target in background or foreground (false by default, not supported by headless shell).
    :param for_tab: **(EXPERIMENTAL)** *(Optional)* Whether to create the target of type "tab".
    :param hidden: **(EXPERIMENTAL)** *(Optional)* Whether to create a hidden target. The hidden target is observable via protocol, but not present in the tab UI strip. Cannot be created with ```forTab: true````, ````newWindow: true```` or ````background: false```. The life-time of the tab is limited to the life-time of the session.
    :param focus: **(EXPERIMENTAL)** *(Optional)* If specified, the option is used to determine if the new target should be focused or not. By default, the focus behavior depends on the value of the background field. For example, background=false and focus=false will result in the target tab being opened but the browser window remain unchanged (if it was in the background, it will remain in the background) and background=false with focus=undefined will result in the window being focused. Using background: true and focus: true is not supported and will result in an error.
    :returns: The id of the page opened.
    '''
    ...

def detach_from_target(session_id: typing.Optional[SessionID] = ..., target_id: typing.Optional[TargetID] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Detaches session with given id.

    :param session_id: *(Optional)* Session to detach.
    :param target_id: **(DEPRECATED)** *(Optional)* Deprecated.
    '''
    ...

def dispose_browser_context(browser_context_id: browser.BrowserContextID) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Deletes a BrowserContext. All the belonging pages will be closed without calling their
    beforeunload hooks.

    :param browser_context_id:
    '''
    ...

def get_target_info(target_id: typing.Optional[TargetID] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, TargetInfo]:
    '''
    Returns information about a target.

    **EXPERIMENTAL**

    :param target_id: *(Optional)*
    :returns:
    '''
    ...

def get_targets(filter_: typing.Optional[TargetFilter] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[TargetInfo]]:
    '''
    Retrieves a list of available targets.

    :param filter_: **(EXPERIMENTAL)** *(Optional)* Only targets matching filter will be reported. If filter is not specified and target discovery is currently enabled, a filter used for target discovery is used for consistency.
    :returns: The list of targets.
    '''
    ...

@deprecated(version="1.3")
def send_message_to_target(message: str, session_id: typing.Optional[SessionID] = ..., target_id: typing.Optional[TargetID] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sends protocol message over session with given id.
    Consider using flat mode instead; see commands attachToTarget, setAutoAttach,
    and crbug.com/991325.

    .. deprecated:: 1.3

    :param message:
    :param session_id: *(Optional)* Identifier of the session.
    :param target_id: **(DEPRECATED)** *(Optional)* Deprecated.
    '''
    ...

def set_auto_attach(auto_attach: bool, wait_for_debugger_on_start: bool, flatten: typing.Optional[bool] = ..., filter_: typing.Optional[TargetFilter] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Controls whether to automatically attach to new targets which are considered
    to be directly related to this one (for example, iframes or workers).
    When turned on, attaches to all existing related targets as well. When turned off,
    automatically detaches from all currently attached targets.
    This also clears all targets added by ``autoAttachRelated`` from the list of targets to watch
    for creation of related targets.
    You might want to call this recursively for auto-attached targets to attach
    to all available targets.

    :param auto_attach: Whether to auto-attach to related targets.
    :param wait_for_debugger_on_start: Whether to pause new targets when attaching to them. Use ```Runtime.runIfWaitingForDebugger``` to run paused targets.
    :param flatten: **(EXPERIMENTAL)** *(Optional)* Enables "flat" access to the session via specifying sessionId attribute in the commands. We plan to make this the default, deprecate non-flattened mode, and eventually retire it. See crbug.com/991325.
    :param filter_: **(EXPERIMENTAL)** *(Optional)* Only targets matching filter will be attached.
    '''
    ...

def auto_attach_related(target_id: TargetID, wait_for_debugger_on_start: bool, filter_: typing.Optional[TargetFilter] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Adds the specified target to the list of targets that will be monitored for any related target
    creation (such as child frames, child workers and new versions of service worker) and reported
    through ``attachedToTarget``. The specified target is also auto-attached.
    This cancels the effect of any previous ``setAutoAttach`` and is also cancelled by subsequent
    ``setAutoAttach``. Only available at the Browser target.

    **EXPERIMENTAL**

    :param target_id:
    :param wait_for_debugger_on_start: Whether to pause new targets when attaching to them. Use ```Runtime.runIfWaitingForDebugger``` to run paused targets.
    :param filter_: **(EXPERIMENTAL)** *(Optional)* Only targets matching filter will be attached.
    '''
    ...

def set_discover_targets(discover: bool, filter_: typing.Optional[TargetFilter] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Controls whether to discover available targets and notify via
    ``targetCreated/targetInfoChanged/targetDestroyed`` events.

    :param discover: Whether to discover available targets.
    :param filter_: **(EXPERIMENTAL)** *(Optional)* Only targets matching filter will be attached. If ```discover```` is false, ````filter``` must be omitted or empty.
    '''
    ...

def set_remote_locations(locations: typing.List[RemoteLocation]) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables target discovery for the specified locations, when ``setDiscoverTargets`` was set to
    ``true``.

    **EXPERIMENTAL**

    :param locations: List of remote locations.
    '''
    ...

def get_dev_tools_target(target_id: TargetID) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.Optional[TargetID]]:
    '''
    Gets the targetId of the DevTools page target opened for the given target
    (if any).

    **EXPERIMENTAL**

    :param target_id: Page or tab target ID.
    :returns: *(Optional)* The targetId of DevTools page target if exists.
    '''
    ...

def open_dev_tools(target_id: TargetID, panel_id: typing.Optional[str] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, TargetID]:
    '''
    Opens a DevTools window for the target.

    **EXPERIMENTAL**

    :param target_id: This can be the page or tab target ID.
    :param panel_id: *(Optional)* The id of the panel we want DevTools to open initially. Currently supported panels are elements, console, network, sources, resources and performance.
    :returns: The targetId of DevTools page target.
    '''
    ...

@event_class('Target.attachedToTarget')
@dataclass
class AttachedToTarget:
    '''
    **EXPERIMENTAL**

    Issued when attached to target because of auto-attach or ``attachToTarget`` command.
    '''
    session_id: SessionID
    target_info: TargetInfo
    waiting_for_debugger: bool
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AttachedToTarget:
        ...



@event_class('Target.detachedFromTarget')
@dataclass
class DetachedFromTarget:
    '''
    **EXPERIMENTAL**

    Issued when detached from target for any reason (including ``detachFromTarget`` command). Can be
    issued multiple times per target if multiple sessions have been attached to it.
    '''
    session_id: SessionID
    target_id: typing.Optional[TargetID]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> DetachedFromTarget:
        ...



@event_class('Target.receivedMessageFromTarget')
@dataclass
class ReceivedMessageFromTarget:
    '''
    Notifies about a new protocol message received from the session (as reported in
    ``attachedToTarget`` event).
    '''
    session_id: SessionID
    message: str
    target_id: typing.Optional[TargetID]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ReceivedMessageFromTarget:
        ...



@event_class('Target.targetCreated')
@dataclass
class TargetCreated:
    '''
    Issued when a possible inspection target is created.
    '''
    target_info: TargetInfo
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetCreated:
        ...



@event_class('Target.targetDestroyed')
@dataclass
class TargetDestroyed:
    '''
    Issued when a target is destroyed.
    '''
    target_id: TargetID
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetDestroyed:
        ...



@event_class('Target.targetCrashed')
@dataclass
class TargetCrashed:
    '''
    Issued when a target has crashed.
    '''
    target_id: TargetID
    status: str
    error_code: int
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetCrashed:
        ...



@event_class('Target.targetInfoChanged')
@dataclass
class TargetInfoChanged:
    '''
    Issued when some information about a target has changed. This only happens between
    ``targetCreated`` and ``targetDestroyed``.
    '''
    target_info: TargetInfo
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> TargetInfoChanged:
        ...
