"""
This type stub file was generated by pyright.
"""

import typing

T_JSON_DICT = typing.Dict[str, typing.Any]
_event_parsers = ...
def event_class(method) -> Callable[..., Any]:
    ''' A decorator that registers a class as an event class. '''
    ...

def parse_json_event(json: T_JSON_DICT) -> typing.Any:
    ''' Parse a JSON dictionary into a CDP event. '''
    ...
