"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class

class GraphObjectId(str):
    '''
    An unique ID for a graph object (AudioContext, AudioNode, AudioParam) in Web Audio API
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> GraphObjectId:
        ...

    def __repr__(self) -> str:
        ...



class ContextType(enum.Enum):
    '''
    Enum of BaseAudioContext types
    '''
    REALTIME = ...
    OFFLINE = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ContextType:
        ...



class ContextState(enum.Enum):
    '''
    Enum of AudioContextState from the spec
    '''
    SUSPENDED = ...
    RUNNING = ...
    CLOSED = ...
    INTERRUPTED = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ContextState:
        ...



class NodeType(str):
    '''
    Enum of AudioNode types
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> NodeType:
        ...

    def __repr__(self) -> str:
        ...



class ChannelCountMode(enum.Enum):
    '''
    Enum of AudioNode::ChannelCountMode from the spec
    '''
    CLAMPED_MAX = ...
    EXPLICIT = ...
    MAX_ = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ChannelCountMode:
        ...



class ChannelInterpretation(enum.Enum):
    '''
    Enum of AudioNode::ChannelInterpretation from the spec
    '''
    DISCRETE = ...
    SPEAKERS = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ChannelInterpretation:
        ...



class ParamType(str):
    '''
    Enum of AudioParam types
    '''
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> ParamType:
        ...

    def __repr__(self) -> str:
        ...



class AutomationRate(enum.Enum):
    '''
    Enum of AudioParam::AutomationRate from the spec
    '''
    A_RATE = ...
    K_RATE = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> AutomationRate:
        ...



@dataclass
class ContextRealtimeData:
    '''
    Fields in AudioContext that change in real-time.
    '''
    current_time: float
    render_capacity: float
    callback_interval_mean: float
    callback_interval_variance: float
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ContextRealtimeData:
        ...



@dataclass
class BaseAudioContext:
    '''
    Protocol object for BaseAudioContext
    '''
    context_id: GraphObjectId
    context_type: ContextType
    context_state: ContextState
    callback_buffer_size: float
    max_output_channel_count: float
    sample_rate: float
    realtime_data: typing.Optional[ContextRealtimeData] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> BaseAudioContext:
        ...



@dataclass
class AudioListener:
    '''
    Protocol object for AudioListener
    '''
    listener_id: GraphObjectId
    context_id: GraphObjectId
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioListener:
        ...



@dataclass
class AudioNode:
    '''
    Protocol object for AudioNode
    '''
    node_id: GraphObjectId
    context_id: GraphObjectId
    node_type: NodeType
    number_of_inputs: float
    number_of_outputs: float
    channel_count: float
    channel_count_mode: ChannelCountMode
    channel_interpretation: ChannelInterpretation
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioNode:
        ...



@dataclass
class AudioParam:
    '''
    Protocol object for AudioParam
    '''
    param_id: GraphObjectId
    node_id: GraphObjectId
    context_id: GraphObjectId
    param_type: ParamType
    rate: AutomationRate
    default_value: float
    min_value: float
    max_value: float
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioParam:
        ...



def enable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enables the WebAudio domain and starts sending context lifetime events.
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disables the WebAudio domain.
    '''
    ...

def get_realtime_data(context_id: GraphObjectId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, ContextRealtimeData]:
    '''
    Fetch the realtime data from the registered contexts.

    :param context_id:
    :returns:
    '''
    ...

@event_class('WebAudio.contextCreated')
@dataclass
class ContextCreated:
    '''
    Notifies that a new BaseAudioContext has been created.
    '''
    context: BaseAudioContext
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ContextCreated:
        ...



@event_class('WebAudio.contextWillBeDestroyed')
@dataclass
class ContextWillBeDestroyed:
    '''
    Notifies that an existing BaseAudioContext will be destroyed.
    '''
    context_id: GraphObjectId
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ContextWillBeDestroyed:
        ...



@event_class('WebAudio.contextChanged')
@dataclass
class ContextChanged:
    '''
    Notifies that existing BaseAudioContext has changed some properties (id stays the same)..
    '''
    context: BaseAudioContext
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> ContextChanged:
        ...



@event_class('WebAudio.audioListenerCreated')
@dataclass
class AudioListenerCreated:
    '''
    Notifies that the construction of an AudioListener has finished.
    '''
    listener: AudioListener
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioListenerCreated:
        ...



@event_class('WebAudio.audioListenerWillBeDestroyed')
@dataclass
class AudioListenerWillBeDestroyed:
    '''
    Notifies that a new AudioListener has been created.
    '''
    context_id: GraphObjectId
    listener_id: GraphObjectId
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioListenerWillBeDestroyed:
        ...



@event_class('WebAudio.audioNodeCreated')
@dataclass
class AudioNodeCreated:
    '''
    Notifies that a new AudioNode has been created.
    '''
    node: AudioNode
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioNodeCreated:
        ...



@event_class('WebAudio.audioNodeWillBeDestroyed')
@dataclass
class AudioNodeWillBeDestroyed:
    '''
    Notifies that an existing AudioNode has been destroyed.
    '''
    context_id: GraphObjectId
    node_id: GraphObjectId
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioNodeWillBeDestroyed:
        ...



@event_class('WebAudio.audioParamCreated')
@dataclass
class AudioParamCreated:
    '''
    Notifies that a new AudioParam has been created.
    '''
    param: AudioParam
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioParamCreated:
        ...



@event_class('WebAudio.audioParamWillBeDestroyed')
@dataclass
class AudioParamWillBeDestroyed:
    '''
    Notifies that an existing AudioParam has been destroyed.
    '''
    context_id: GraphObjectId
    node_id: GraphObjectId
    param_id: GraphObjectId
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> AudioParamWillBeDestroyed:
        ...



@event_class('WebAudio.nodesConnected')
@dataclass
class NodesConnected:
    '''
    Notifies that two AudioNodes are connected.
    '''
    context_id: GraphObjectId
    source_id: GraphObjectId
    destination_id: GraphObjectId
    source_output_index: typing.Optional[float]
    destination_input_index: typing.Optional[float]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> NodesConnected:
        ...



@event_class('WebAudio.nodesDisconnected')
@dataclass
class NodesDisconnected:
    '''
    Notifies that AudioNodes are disconnected. The destination can be null, and it means all the outgoing connections from the source are disconnected.
    '''
    context_id: GraphObjectId
    source_id: GraphObjectId
    destination_id: GraphObjectId
    source_output_index: typing.Optional[float]
    destination_input_index: typing.Optional[float]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> NodesDisconnected:
        ...



@event_class('WebAudio.nodeParamConnected')
@dataclass
class NodeParamConnected:
    '''
    Notifies that an AudioNode is connected to an AudioParam.
    '''
    context_id: GraphObjectId
    source_id: GraphObjectId
    destination_id: GraphObjectId
    source_output_index: typing.Optional[float]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> NodeParamConnected:
        ...



@event_class('WebAudio.nodeParamDisconnected')
@dataclass
class NodeParamDisconnected:
    '''
    Notifies that an AudioNode is disconnected to an AudioParam.
    '''
    context_id: GraphObjectId
    source_id: GraphObjectId
    destination_id: GraphObjectId
    source_output_index: typing.Optional[float]
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> NodeParamDisconnected:
        ...
