"""
This type stub file was generated by pyright.
"""

import enum
import typing
from dataclasses import dataclass
from .util import T_JSON_DICT, event_class

class AuthenticatorId(str):
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> AuthenticatorId:
        ...

    def __repr__(self) -> str:
        ...



class AuthenticatorProtocol(enum.Enum):
    U2F = ...
    CTAP2 = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> AuthenticatorProtocol:
        ...



class Ctap2Version(enum.Enum):
    CTAP2_0 = ...
    CTAP2_1 = ...
    CTAP2_2 = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> Ctap2Version:
        ...



class AuthenticatorTransport(enum.Enum):
    USB = ...
    NFC = ...
    BLE = ...
    CABLE = ...
    INTERNAL = ...
    def to_json(self) -> str:
        ...

    @classmethod
    def from_json(cls, json: str) -> AuthenticatorTransport:
        ...



@dataclass
class VirtualAuthenticatorOptions:
    protocol: AuthenticatorProtocol
    transport: AuthenticatorTransport
    ctap2_version: typing.Optional[Ctap2Version] = ...
    has_resident_key: typing.Optional[bool] = ...
    has_user_verification: typing.Optional[bool] = ...
    has_large_blob: typing.Optional[bool] = ...
    has_cred_blob: typing.Optional[bool] = ...
    has_min_pin_length: typing.Optional[bool] = ...
    has_prf: typing.Optional[bool] = ...
    has_hmac_secret: typing.Optional[bool] = ...
    has_hmac_secret_mc: typing.Optional[bool] = ...
    automatic_presence_simulation: typing.Optional[bool] = ...
    is_user_verified: typing.Optional[bool] = ...
    default_backup_eligibility: typing.Optional[bool] = ...
    default_backup_state: typing.Optional[bool] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> VirtualAuthenticatorOptions:
        ...



@dataclass
class Credential:
    credential_id: str
    is_resident_credential: bool
    private_key: str
    sign_count: int
    rp_id: typing.Optional[str] = ...
    user_handle: typing.Optional[str] = ...
    large_blob: typing.Optional[str] = ...
    backup_eligibility: typing.Optional[bool] = ...
    backup_state: typing.Optional[bool] = ...
    user_name: typing.Optional[str] = ...
    user_display_name: typing.Optional[str] = ...
    def to_json(self) -> T_JSON_DICT:
        ...

    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Credential:
        ...



def enable(enable_ui: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Enable the WebAuthn domain and start intercepting credential storage and
    retrieval with a virtual authenticator.

    :param enable_ui: *(Optional)* Whether to enable the WebAuthn user interface. Enabling the UI is recommended for debugging and demo purposes, as it is closer to the real experience. Disabling the UI is recommended for automated testing. Supported at the embedder's discretion if UI is available. Defaults to false.
    '''
    ...

def disable() -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Disable the WebAuthn domain.
    '''
    ...

def add_virtual_authenticator(options: VirtualAuthenticatorOptions) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, AuthenticatorId]:
    '''
    Creates and adds a virtual authenticator.

    :param options:
    :returns:
    '''
    ...

def set_response_override_bits(authenticator_id: AuthenticatorId, is_bogus_signature: typing.Optional[bool] = ..., is_bad_uv: typing.Optional[bool] = ..., is_bad_up: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Resets parameters isBogusSignature, isBadUV, isBadUP to false if they are not present.

    :param authenticator_id:
    :param is_bogus_signature: *(Optional)* If isBogusSignature is set, overrides the signature in the authenticator response to be zero. Defaults to false.
    :param is_bad_uv: *(Optional)* If isBadUV is set, overrides the UV bit in the flags in the authenticator response to be zero. Defaults to false.
    :param is_bad_up: *(Optional)* If isBadUP is set, overrides the UP bit in the flags in the authenticator response to be zero. Defaults to false.
    '''
    ...

def remove_virtual_authenticator(authenticator_id: AuthenticatorId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Removes the given authenticator.

    :param authenticator_id:
    '''
    ...

def add_credential(authenticator_id: AuthenticatorId, credential: Credential) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Adds the credential to the specified authenticator.

    :param authenticator_id:
    :param credential:
    '''
    ...

def get_credential(authenticator_id: AuthenticatorId, credential_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, Credential]:
    '''
    Returns a single credential stored in the given virtual authenticator that
    matches the credential ID.

    :param authenticator_id:
    :param credential_id:
    :returns:
    '''
    ...

def get_credentials(authenticator_id: AuthenticatorId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, typing.List[Credential]]:
    '''
    Returns all the credentials stored in the given virtual authenticator.

    :param authenticator_id:
    :returns:
    '''
    ...

def remove_credential(authenticator_id: AuthenticatorId, credential_id: str) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Removes a credential from the authenticator.

    :param authenticator_id:
    :param credential_id:
    '''
    ...

def clear_credentials(authenticator_id: AuthenticatorId) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Clears all the credentials from the specified device.

    :param authenticator_id:
    '''
    ...

def set_user_verified(authenticator_id: AuthenticatorId, is_user_verified: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets whether User Verification succeeds or fails for an authenticator.
    The default is true.

    :param authenticator_id:
    :param is_user_verified:
    '''
    ...

def set_automatic_presence_simulation(authenticator_id: AuthenticatorId, enabled: bool) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Sets whether tests of user presence will succeed immediately (if true) or fail to resolve (if false) for an authenticator.
    The default is true.

    :param authenticator_id:
    :param enabled:
    '''
    ...

def set_credential_properties(authenticator_id: AuthenticatorId, credential_id: str, backup_eligibility: typing.Optional[bool] = ..., backup_state: typing.Optional[bool] = ...) -> typing.Generator[T_JSON_DICT, T_JSON_DICT, None]:
    '''
    Allows setting credential properties.
    https://w3c.github.io/webauthn/#sctn-automation-set-credential-properties

    :param authenticator_id:
    :param credential_id:
    :param backup_eligibility: *(Optional)*
    :param backup_state: *(Optional)*
    '''
    ...

@event_class('WebAuthn.credentialAdded')
@dataclass
class CredentialAdded:
    '''
    Triggered when a credential is added to an authenticator.
    '''
    authenticator_id: AuthenticatorId
    credential: Credential
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CredentialAdded:
        ...



@event_class('WebAuthn.credentialDeleted')
@dataclass
class CredentialDeleted:
    '''
    Triggered when a credential is deleted, e.g. through
    PublicKeyCredential.signalUnknownCredential().
    '''
    authenticator_id: AuthenticatorId
    credential_id: str
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CredentialDeleted:
        ...



@event_class('WebAuthn.credentialUpdated')
@dataclass
class CredentialUpdated:
    '''
    Triggered when a credential is updated, e.g. through
    PublicKeyCredential.signalCurrentUserDetails().
    '''
    authenticator_id: AuthenticatorId
    credential: Credential
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CredentialUpdated:
        ...



@event_class('WebAuthn.credentialAsserted')
@dataclass
class CredentialAsserted:
    '''
    Triggered when a credential is used in a webauthn assertion.
    '''
    authenticator_id: AuthenticatorId
    credential: Credential
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> CredentialAsserted:
        ...
